### ISSUE TITLE
Can't remove tags/categories

### ISSUE THREAD

**Issue by IIISnowflakeIII** [hay-kot/mealie#10]
Hi,

Just deployed Mealie on Docker Swarm using the exact docker compose found on your site, only changed the volumes and DB password. Added a recipe from Bonappetit and played around with it, but after adding a tag or category, I'm unable to remove it.

Tested it on Firefox, Opera and Edge. Don't get any error logs either.

**Comment by hay-kot** [comment]
I never programmed the "x" button. I've fixed it for the next release. In mean time, you can remove tags/categories by removing them as you would with text. So place your cursor after the tag you want to delete and hit `backspace`
