### ISSUE TITLE
Incorrect recipe added to meal planner on search

### ISSUE THREAD

**Issue by nickcj931** [hay-kot/mealie#102]
## Problem
When I search to add a recipe to a meal planner, it selects  the wrong recipe. I believe it selects a recipe which is visible on the initial dropdown click before the search parameters are entered. 

Gif attached below to demonstrate what I am talking about. I have tried this on three browsers Safari/Chrome/Firefox on laptop and ios, same result. 

The only way I can add the correct recipe is by scrolling through all the lines.

## How to replicate issue
Planner-> Edit Meal Plans -> Click on day you wish to add recipe to -> Search for a recipe -> Select
Wrong recipe added to day.

![2021-01-20 16 04 10](https://user-images.githubusercontent.com/17556895/105208143-434bae80-5b40-11eb-80dd-b10d1a090c99.gif)
 
This issue may or may not be resolved when Fuzzy search #15 is implemented

**Comment by hay-kot** [comment]
I'm working on a redesign on a redesign of the meal-planner page and this is fixed. Hopefully, I'll be able to push something out early next week. 

![ezgif com-optimize](https://user-images.githubusercontent.com/64056131/105268282-64130480-5b3e-11eb-8110-85aba98e57e3.gif)

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉
