### ISSUE TITLE
recipe created from scratch it does not 'save'

### ISSUE THREAD

**Issue by slidewarrior** [hay-kot/mealie#104]
When adding a recipe created from scratch it does not 'save'.
I just get a blank page that looks 'bigger'

I can add then edit recipes from a URL with no issues.

This in on an HP-Gen-08 [x86] docker on an OMV/debian install.

**Comment by hay-kot** [comment]
Can you post your log file?

**Comment by slidewarrior** [comment]
[mealie.log](https://github.com/hay-kot/mealie/files/5852072/mealie.log)

I take it this is the file you're looking for?

**Comment by hay-kot** [comment]
My guess is the you're trying to save with empty data fields. Currently there is no client side data validation. I'm working on implementing this. In the mean time make sure you have at least some ingredients and steps, a description, and title. 
```
ValidationError (RecipeDocument:None) (Field is required and cannot be empty: ['recipeIngredient'])
```

**Comment by hay-kot** [comment]
This issue is resolved in the next release.

**Comment by slidewarrior** [comment]
Happy to close this but fyi:
looks like I need multiple ingredients and steps in place, I know now what to have ready before I hit save
