### ISSUE TITLE
[Feature Request] Recipes calculate nutriton data

### ISSUE THREAD

**Issue by adrkable** [hay-kot/mealie#109]
Myfitnesspal currently lets one create "meals" (or recipes)  where the total nutrtion value is a sum of the meal's parts (ingredients). Nutrition data need not be sourced from MFP, it can be any nutrition database. 

A few nutrition database APIs:

- https://www.myfitnesspal.com/api (pricing model isn't public)
- https://calorieninjas.com/api  (each user would have to sign up for their own API key to keep this "free")
- https://fdc.nal.usda.gov/api-guide.html   (each user would have to sign up for their own API key to keep this "free")
- https://www.nutritionix.com/business/api (each user would have to sign up for their own API key to keep this "free")
- https://world.openfoodfacts.org/data (has free API and a MondoDB dump)

**Comment by lorenalexm** [comment]
Following this, I think manual entry of nutritional data would be fantastic. It would also lay the groundwork for potentially using one of the above services, in the future, for automatic calculation.

**Comment by dpieski** [comment]
To calculate the nutrition information, the ingredients would have to be split into quantity and ingredient. 

Check out #70 for more information on the thoughts regarding separating out the quantity from ingredients.

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
