### ISSUE TITLE
Status of MongoDB Support

### ISSUE THREAD

**Issue by jonfairbanks** [hay-kot/mealie#111]
I had intended to set this project up and was in the process of deploying this in my kubernetes cluster with Mongo. 

Now when refreshing the setup guide, I see Mongo is marked as depreciated. I did a search around and could not find why this was the case. Is there any background available on this decision?

Thanks!

**Comment by hay-kot** [comment]
Thanks for the interest in the project! I found there was a lot of negative feedback for using Mongo. Most people didn't want to spin up a Mongo Database for a Recipe app. I really liked working with Mongo, and think a barrier was mostly artificial,  but I there's something to be set about SQL and SQLite support for self hosted applications. 

**Some Benefits** 
- Single Container Deployment with SQLite
- Makes database testing MUCH easier which helps keeps things stable
- Single ORM can be used for multiple database SQLite, PostgreSQL, MariaDB, etc...

**Why not Support Both?** Well, I'm doing this all on my own free time and frankly I'm already burying probably too much of my free time into this. Managing 2 completely different databases would hinder development on the project. 

It was a bummer to have to drop support so early, but doing it now while the user base was small seemed like the best option. PostgreSQL support will be coming in the future, additionally migrating from Mongo to SQL is as simple Backup/Import via the UI. 

The docs are a bit of a mess ATM, I'm hoping to get them cleaned up this weekend but my time seems to be disappearing more and more lately!

**Comment by dpieski** [comment]
Check out #70 for more information on this direction.

**Comment by jonfairbanks** [comment]
Thank you for the response. I will work on setting up the single container solution and go from there. Thanks for the project! 💯

**Comment by chrismast** [comment]
Great to hear that PSQL is coming as I would like to run it with my centralized PSQL db.
