### ISSUE TITLE
[Bug] Allow opening recipes in new tab

### ISSUE THREAD

**Issue by Elmardus** [hay-kot/mealie#112]
Is it possible to open recipes from the overview page in a new tab? Currently using middle click (scrollwheel) or CTRL+click does not open a recipe in a new tab.

**Comment by hay-kot** [comment]
I've found the error I made and have got it working. It will be working in the next release 👍

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉
