### ISSUE TITLE
Feature Request - add cooking times

### ISSUE THREAD

**Issue by slidewarrior** [hay-kot/mealie#114]
Would be great if there is a way to include the fields of PREP: time, COOK: time and possibly TOTAL: time in to the recipe cards, preferably near the top, even if these times need to entered manually like Notes are now.
Sometimes a quick recipe is a lifesaver.

**Comment by nickcj931** [comment]
This is already a thing.  there was a request which was closed #63
<img width="1988" alt="Screenshot 2021-01-22 at 18 41 58" src="https://user-images.githubusercontent.com/17556895/105531747-b3de0100-5ce1-11eb-9ae4-c5c463d58e73.png">

**Comment by slidewarrior** [comment]
Apologies, I checked the issues, but not those that were now closed doh!
cheers

**Comment by nickcj931** [comment]
Have you updated to latest version? Might be worth while doing a new pull of the docket image and redeploy the container (If that’s your setup)
