### ISSUE TITLE
[Feature Request] Add support to use url of recipe image instead of attaching a local image

### ISSUE THREAD

**Issue by StuGotz** [hay-kot/mealie#117]
When mealie is unable to parse a site for a recipe, I'd like to automate importing an image into the manually created recipe.  Currently the workflow requires you to download an image locally to import into the recipe.  I'd like to supply a URL of the image to use from the original site to automatically download the image and store it.

**Comment by palitu** [comment]
I agree! this would be easy, and i assume it would be relatively easy!

**Comment by QuaySo** [comment]
This is already supported, just paste the URL in the file open dialog (see example below)
![URL](https://user-images.githubusercontent.com/36159002/110212512-edd32300-7e9b-11eb-9c30-7bf6f06e3058.png)

**Comment by mdrichardson** [comment]
To add, pasting an image from the clipboard would be great, too.

**Comment by hay-kot** [comment]
This will be fixed in the next release. Ref #288 

<img width="1063" alt="Screen Shot 2021-04-11 at 12 48 42 PM" src="https://user-images.githubusercontent.com/64056131/114320837-5a0cfc00-9ac4-11eb-894c-2d500c55bb98.png">
