### ISSUE TITLE
[Feature Request] Add field for URL when manually adding a recipe

### ISSUE THREAD

**Issue by StuGotz** [hay-kot/mealie#118]
It would be nice to be able to store a URL for recipes that don't automatically parse, when entering the recipe manually.

**Comment by hay-kot** [comment]
I've added this in the development branch and it will be available in the next release. In the mean time you are able to update the recipe URL in the json editor.

**Comment by StuGotz** [comment]
Thank you!

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
