### ISSUE TITLE
[Feature Request] Insert ingredient anywhere in ingredients list

### ISSUE THREAD

**Issue by StuGotz** [hay-kot/mealie#120]
Currently when editing a recipe's list of ingredients, adding a new ingredient results in an additional item added to the end of the list.  Most recipe's ingredients list are sorted in the order of use.  It would be great to highlight a row, click add, and a row is inserted below the selected ingredient.  Currently using the json editor to manually change the order of ingredients when necessary.

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
