### ISSUE TITLE
[Feature Request] Grouping recipes by Category and sorting options

### ISSUE THREAD

**Issue by StuGotz** [hay-kot/mealie#121]
Request to group recipes on the main UI by category, with user definable display order.  Option to sort recipes alphabetically or by rating within each category.

**Comment by hay-kot** [comment]
This is currently being worked on, closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
