### ISSUE TITLE
Can't paste recipe from URL 

### ISSUE THREAD

**Issue by Maxile95** [hay-kot/mealie#127]
I can't paste a URL from Chefkoch.de.

Example: https://www.chefkoch.de/rezepte/2197631352629875/Haehnchenbrustfilets-mit-Karotten-Kaese-Kruste.html

Do I still need an addon for this?

**Comment by hay-kot** [comment]
This should be fixed in the next version. I'm unsure when the release may be out but I'm shooting for next weekend.

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉
