### ISSUE TITLE
Feature: Plugin Framework

### ISSUE THREAD

**Issue by gr33ngiant112** [hay-kot/mealie#13]
Oddly enough, I've been planning/designing something very similar to mealie for months but never managed to get it off of the ground. 

One of the thoughts behind my implementation was what about all of the other sites that don't adhere to to the recipe schema that `scrape-schema-recipe` can parse. For example, one of my favorite recipe sites, https://thesaltymarshmallow.com/, has their own templating system. Many of their recipes don't seem to be syndicated to other sites as well. 

For this reason, I was working on building a plugin framework to solve that problem. Mealie could benefit from it tremendously by allowing the community to supply their own plugins for additional sites who don't store recipes in a standard format. This could be done through a framework implementing just `requests` and `bs4` and allowing people to specify logic to parse into the format required by the app. 

Of course, the challenge would be allowing such a framework while maintaining speed -- you could use something like Celery or another job queueing system in order to offload imports from the main thread (which is something else you might want to look into, just in general). 

Love the work you've done so far, can't wait to see where this leads.

**Comment by hay-kot** [comment]
> Mealie could benefit from it tremendously by allowing the community to supply their own plugins for additional sites who don't store recipes in a standard format.

I've been thinking about this the past few days and I'm not really sure how to approach a plugin architecture. Currently the FastAPI backend provides API endpoint for nearly everything that is done on the backend, including creating a recipe from JSON data. A 3rd Part plugin just needs to filter/format the data according to the schema Mealie uses.

Mealie already uses a "normalization" process internally to parse through different types of the schemas used. A specific PR guideline/developer guide on improving the internal parser may be a better solution than a plugin architecture.

> you could use something like Celery or another job queueing system in order to offload imports from the main thread

This was also something I considered for scheduling. My main decision not to was, well do I really need to spin up 3 containers for a self-hosted recipe app? Seems kind of crazy, but it may be needed down the line. I think implementing async code would solve some speed problems in the application. I will say I don't have a lot of experience writing async python

I'm interested to hear others thoughts

**Comment by kophi** [comment]
I came across quite some (German) websites that do not work with Mealie and I think website specific parsers are a very good idea. Especially non-JSON ones are required for some big recipe sites out there. We could even extend this to say eBooks or YouTube video descriptions. Maybe match the website with url regex provided by the parser. I doubt that one single parser can be made smart enough to work with all the infinite variations of how recipes are formatted.

Really looking forward for that feature. It would very much improve this already fantastic piece of software!

**Comment by sephrat** [comment]
Mealie now uses recipe-scrapers library (https://github.com/hhursev/recipe-scrapers) starting from 0.5.0.
Any specific integration for a website should be considered there instead of inside Mealie.

**Comment by hay-kot** [comment]
Closing this for now. If anyone is interested in working on a plugin system, please use GitHub discussions.
