### ISSUE TITLE
Recipe with empty title returns "404 page not found"

### ISSUE THREAD

**Issue by maguilara** [hay-kot/mealie#131]
**Describe the bug**
Not handling correctly the creation of recipes with empty titles.

**Steps To Reproduce**
Please be specific!
1. Create recipe with an empty title
2. When going to the main screen and selecting the empty recipe, will be greeted with a screen with the following message "404 page not found. Take me home", which will take us back to the main screen

**Sample Code**

**Expected behavior**
Not being able to create recipes with an empty title, or maybe saving them to a tab for draft or incomplete recipes (feature request?)
**Actual Behavior**
Recipe with empty title created and not being able to modify it or even delete it.
**Screenshots**

**Device Information (please complete the following information):**
 - OS: raspberry pi os (debian)
 - Deployment: docker, armv7
 - Browser: firefox
 - Version: latest beta version I guess, i pulled the image from the docker hub

**Comment by maguilara** [comment]
If this is fixed by https://github.com/hay-kot/mealie/issues/104, please close this issue.

**Comment by hay-kot** [comment]
> If this is fixed along with the error in #104, please close this issue.

It's currently fixed in the dev branch. It will be fixed in release 0.2.0. I'm hoping to complete the release next weekend.

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉

**Comment by waynem-bris** [comment]
I have the same error with v0.5.6.
I can not delete the recipe and can not delete it.
It turns out I had not added ingredients.

Is there a way to remove the recipe from the database?

**Comment by dino9848** [comment]
Same issue with:
Version:  v1.1.1
Build:  [9bf2e3fabd4bb9dce72f472ae13e064b5e9f6b78](https://github.com/mealie-recipes/mealie/commit/9bf2e3fabd4bb9dce72f472ae13e064b5e9f6b78)
Recipe Scraper Version:[14.54.0](https://github.com/hhursev/recipe-scrapers/releases/tag/14.54.0)

Accidentally created a blank recipe and no way to remove it from db or delete it from the GUI.  I think this is the app with the most potential to create a "family" digital recipe book.  Passing some support your way.
