### ISSUE TITLE
Can't run mealie on sub path of domain

### ISSUE THREAD

**Issue by zjean** [hay-kot/mealie#136]
**Describe the bug**
It looks like I can't run mealie on a path in my domain (e.g. domain.com/mealie) since the html is served with paths pointing to the root like:
<link href="/static/css/chunk-vendors.6f7d5b0b.css" />

**Steps To Reproduce**
Please be specific!
1. Run mealie as a docker container
2. Behind a reverse proxy, on a sub path.
3. Homepage is blank, since the assets can't be found

**Sample Code**

**Expected behavior**
I would like to be able to pass a a path in via an environment variable, or

**Actual Behavior**
Blank home page

**Screenshots**

**Device Information (please complete the following information):**
 - OS: Linux
 - Deployment: Docker-compose latest
 - Browser: chrome
 - Version: latest released version

**Additional context**

**Comment by dpieski** [comment]
> with paths pointing to the root like:

Did you mean to include something here after "root like:"?

**Comment by zjean** [comment]
Yes github stripped my text I think. 
The paths pointing to the styles and resources start with a slash, like /static/c.css and such

**Comment by hay-kot** [comment]
I've looked into implementing this and unfortunately I don't see a way to do it after the frontend is built for production. It should be easy enough to use an ENV on the backend side to set the base path for the API, I'm not sure how to set the Frontend to dynamically know where the "base path" would start. Hopefully someone else can chime in with a solution.

**Comment by hay-kot** [comment]
Minor Update - I've split the static files and the API with Caddy v2 in the dev branch. I'm not sure if that alone will suffice for getting everything working. But if additional Caddy configuration is needed I believe someone should be able to use [env variables](https://caddyserver.com/docs/caddyfile/concepts#environment-variables) in the config to create user selectable base url. I don't have a ton of time/energy to dig too deep into this right now, but I'm hoping someone can bring this over the finish line. 👍

**Comment by alexbelgium** [comment]
Hi! I'm also looking at doing this. Would the ENV variable "BASE_URL" from mealie can be used for that?

Thanks !

**Comment by alexbelgium** [comment]
wouldn't simply using ./api/ instead of /api/ in the production wouldn't be enough to allow the api to be accessible from any custom base url ?

**Comment by hay-kot** [comment]
> wouldn't simply using ./api/ instead of /api/ in the production wouldn't be enough to allow the api to be accessible from any custom base url ?

I've tried that as well as a few other variations and it doesn't to work. The Vue router needs know what the base url is and as far a so can tell you can only set that during build time.
