### ISSUE TITLE
When in search, hitting the enter key on selection does not bring you to the recipe

### ISSUE THREAD

**Issue by evulhotdog** [hay-kot/mealie#139]
**Describe the bug**
When in search, hitting the enter key on selection does not bring you to the recipe

**Steps To Reproduce**
Please be specific!

1. From any page, start typing in the search box
2. Select the recipe that you want with your arrow keys (if needed.)
2. Hit enter.

**Expected behavior**
I expect the browser to navigate to that recipe.

**Actual Behavior**
It types the text in the search box. Continuing to hit enter does not do anything after that point.

**Screenshots**
![2021-02-06 00-17-51 2021-02-06 00_18_27](https://user-images.githubusercontent.com/365456/107109762-e6731800-6810-11eb-8b2b-0989cd7a24b5.gif)

**Device Information (please complete the following information):**
 - OS: MacOS  
 - Deployment: Docker
 - Browser: Chrome 88.x
 - Version: v0.1.0

**Comment by hay-kot** [comment]
Fixed in the next update, thanks!
