### ISSUE TITLE
in readme.md, https://hub.docker.com/repository/docker/hkotel/mealie prompts you to log in

### ISSUE THREAD

**Issue by evulhotdog** [hay-kot/mealie#140]
**Describe the bug**
in readme.md, https://hub.docker.com/repository/docker/hkotel/mealie prompts you to log in

**Steps To Reproduce**
Please be specific!
1. Navigate to https://hub.docker.com/repository/docker/hkotel/mealie
2. It will prompt for credentials

**Suggestion**
Replacing it with: https://hub.docker.com/r/hkotel/mealie should not prompt you to log in.

**Expected behavior**
It takes you to the repo. 

**Actual Behavior**
It prompts you to log in.

**Additional context**

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉
