### ISSUE TITLE
Feature: Search using tags and/or categories

### ISSUE THREAD

**Issue by cacack** [hay-kot/mealie#15]
I have imported a couple of reciepes, added them to categories (e.g. Fish, Salad), and applied a few labels (e.g. "meal prep", "breakfast").  When I attempt to search using any of those values, nothing is found.  Ideally the search system should provide the results of those recipes that contain the values.

**Comment by hay-kot** [comment]
Small update on this. I should have some version of fuzzy search rolled into the next release. Hopefully including searching tags and categories.

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
