### ISSUE TITLE
Crash when upgrading to v0.2.0

### ISSUE THREAD

**Issue by kllngtme** [hay-kot/mealie#151]
Thanks, I've just upgraded after realizing that, but I'm getting a hard crash with the latest build on a pi4:

mealie         | Fatal Python error: init_interp_main: can't initialize time
mealie         | Python runtime state: core initialized
mealie         | PermissionError: [Errno 1] Operation not permitted
mealie         | 
mealie         | Current thread 0xb6fd8390 (most recent call first):
mealie         | <no Python frame>
mealie exited with code 1

_Originally posted by @kllngtme in https://github.com/hay-kot/mealie/issues/122#issuecomment-775570157_

**Comment by kllngtme** [comment]
Also, it seemed to have wiped out all my recipes..

**Comment by kllngtme** [comment]
The fix for the python permission issue worked without an issue though:

1.  wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.4.4-1~bpo10+1_armhf.deb
2.  sudo dpkg -i libseccomp2_2.4.4-1~bpo10+1_armhf.deb

**Comment by hay-kot** [comment]
> Also, it seemed to have wiped out all my recipes..

Per the change log you have to export and import your recipes to perform the upgrade. This will likely be the case for most upgrades prior to v1.0.

https://hay-kot.github.io/mealie/changelog/

**Comment by gabrielbergeron** [comment]
I also get the same crash output even with a fresh data folder. I'm on Raspbian

**Comment by Tooa** [comment]
I am experiencing the same issue on my raspberry pi 4 too. However, I get this error for a fresh installation with the `v0.3.0` in docker. Is the `libseccomp2_2.4.4-1~bpo10+1_armhf.deb` a required dependency? If so, shouldn't it be part of the docker image?

**Comment by hay-kot** [comment]
> I am experiencing the same issue on my raspberry pi 4 too. However, I get this error for a fresh installation with the `v0.3.0` in docker. Is the `libseccomp2_2.4.4-1~bpo10+1_armhf.deb` a required dependency? If so, shouldn't it be part of the docker image? Or is this a required host dependency, because docker calls a host function here?  

This is due to a bug in the libseccomp2 library (dependency of docker itself). Mealie is not the direct cause of the issue.
