### ISSUE TITLE
Image quality and description issues when importing from links

### ISSUE THREAD

**Issue by tehniemer** [hay-kot/mealie#16]
I've been able to import these recipes, but the descriptions are not coming with and the preview image quality is very bad. 

https://hostthetoast.com/spicy-roasted-red-pepper-dip/
https://hostthetoast.com/cheesy-bacon-jalapeno-corn-dip/

**Comment by hay-kot** [comment]
This has to do with how your source site is exposing information via [the standards](https://schema.org/Recipe). I'm afraid there's not much I can do to support this at the moment. I don't want to open the door to providing scrappers for individual websites. In the future I'll look at creating a plugin framework to hopefully lend better support for more platforms for developers. For now I'm going to close the issue.
