### ISSUE TITLE
Can't downgrade to save data

### ISSUE THREAD

**Issue by alex-phillips** [hay-kot/mealie#162]
**Describe the bug**
Updated docker container with new image without realizing latest version was not backwards compatible. Now it looks like dockerhub doesn't have an older tagged version to pull down so I can retrieve / export my original data.

**Steps To Reproduce**
N/A

**Comment by hay-kot** [comment]
Currently, I think the only approach to fix this is to download the source code from the release and build to docker image yourself. I'm working on a GitHub workflow to create release specific images to resolve this in the future, but I'm dumb and having a hard time figuring it out.

Hopefully the auto-backup feature was working so in this case you wouldn't lose too much data.

**Comment by alex-phillips** [comment]
@hay-kot docker build from old repo worked. For some reason the only auto-backup I had didn't work. But all good now, thanks!
