### ISSUE TITLE
Reverse proxy conf

### ISSUE THREAD

**Issue by Cassock** [hay-kot/mealie#170]
**Describe the bug**
Probably not a bug at all, tbh. Just having some difficulty getting this secured with a reverse proxy and Authelia. 

**Steps To Reproduce**

- Mealie is up and running just fine locally. 
- Step 2 for me is sharing with mlady via internet via https://hub.docker.com/r/linuxserver/swag.
- Borrow heavily from another conf that's working for its own app. My conf looks like this: https://pastebin.com/P0u4acu4

**Expected behavior**
Homepage served at https://mealie.site.duckdns.org

**Actual Behavior**
502 error

**Screenshots**
N/A

**Device Information (please complete the following information):**
 - OS: Ubuntu server
 - Deployment: Docker-version 19.03.6
 - Browser: chrome
 - Version: 0.2.1-latest

**Additional context**
I am not super well versed in reverse proxy, but I have managed to get 20 or so other containers (hi LSIO) working fine with this method. Just wanted to make sure I wasn't spinning my wheels on something that may not be supported yet.

**Comment by hay-kot** [comment]
I'm not super sure. I wonder if caddy isn't passing something along to nginx? Does your mealie docker log have anything in it?

**Comment by Cassock** [comment]
Delete and ignore and I will punish myself later. I am dumb and didn't have this container on the same network as Authelia/LE. All is working correctly.

**Comment by hay-kot** [comment]
> Delete and ignore and I will punish myself later. I am dumb and didn't have this container on the same network as Authelia/LE. All is working correctly.

Ha! I've been there. Glad you got it working.
