### ISSUE TITLE
When typing fowardslash (/) in the ingredients list, it can trigger search

### ISSUE THREAD

**Issue by evulhotdog** [hay-kot/mealie#174]
**Describe the bug**
When typing ingredients into the ingredient list for a recipe, if you are typing quickly, this can accidentally trigger moving your cursor to the search bar.

**Steps To Reproduce**
Please be specific!
1. Open a recipe
2. Click the edit button.
3. Put cursor into an ingredient text box
4. type `1/2 cup`, but type the `2` quickly after the `/`, and it will put your cursor into the search box.

**Expected behavior**
It would not move my cursor to the search box.

**Actual Behavior**
My typing cursor (focus) is to the search box.

**Device Information (please complete the following information):**
 - OS: MacOS
 - Deployment: docker
 - Browser: Brave
 - Version: Version 1.20.108 Chromium: 88.0.4324.182 (Official Build) (x86_64)

**Comment by hay-kot** [comment]
That's annoying, I'm surprised I didn't run into that. I was able to add a check in the hot-key to see if you're in an input field. Seems to be working for me so it'll be fixed in the next release.

**Comment by evulhotdog** [comment]
Nice!

Yeah I noticed it at first, and I'm like hmm, that's weird, maybe I clicked my mouse... and just typed the slash trying to reproduce it, knowing `/` is often used for search shortcuts and it didn't do it. I then thought to myself, is it based upon the speed? Then I was able to reproduce.
