### ISSUE TITLE
Create a new meal plan allows selection of an end date that is prior to the start date

### ISSUE THREAD

**Issue by bjostad** [hay-kot/mealie#183]
**Describe the bug**
Create a New Meal Plan will allow you to save a meal plan with an end date that is before the selected start date. This results in a meal plan with no valid days.

**Steps To Reproduce**
1. Go to Menu
2. Click on Planner
3. Select March 1 on _start date_
4. Select Feb 7 on _end date_
5. Save

**Expected behavior**
Not allowed to create meal plan with end date before start date

**Actual Behavior**
Saves sucessfully

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: Docker
 - Browser: chrome
 - Version: 0.3.0-dev

**Additional context**
This occurred as we were creating a plan for the first week of march. Because Feb and March dates fall on the same day of the week, we did not notice that it was original showing Feb for the end date even though we had selected march to start. This resulted in creating a meal plan starting march 1 and ending feb 7th.

**Comment by waschinski** [comment]
Thanks for reporting this bug, I will provide an UI fix for this later. While looking at it, is it supposed to not show a single day when start and end date are the same?

**Comment by hay-kot** [comment]
Fixed in [v0.4.0](https://hay-kot.github.io/mealie/changelog/v0.4.0/)
