### ISSUE TITLE
Edited blank recipe in meal plan is not saved

### ISSUE THREAD

**Issue by bjostad** [hay-kot/mealie#184]
**Describe the bug**
When creating a new meal plan a blank entry appears for each day of the week. Clicking on any of those entries takes you to a blank recipe. If you click the edit button on that blank recipe and create a recipe, it will not save properly.

**Steps To Reproduce**
1. Go to _Menu_
2. Click on _Planner_
3. Create a new meal plan ( any dates work)
4. Click on any blank date from the meal plan
5. Click the edit button
6. Edit the blank recipe
7. click the save button

**Expected behavior**
New Recipe is saved

**Actual Behavior**
Recipe is not saved

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: Docker
 - Browser: Chrome
 - Version: 0.3.0-dev

**Additional context**
I'm not sure if this is a defect or more of an unintended side effect of the current state of the project. I wouldn't expect to be able to edit here, so maybe the solution is to only allow selection of a recipe if the existing date is blank.

**Comment by hay-kot** [comment]
This is a side-effect of my poor programming! Link are generated by meal.slug property, when that gets passed to the url it gets passed as 'null'. Which when you try to update a recipe 'null' from the database, well it does't like that. I've resolved the issue by removing the link if there's no meal.slug property on the meal plan recipe. 

Thanks for the report! 👍

**Comment by hay-kot** [comment]
Fixed in [v0.4.0](https://hay-kot.github.io/mealie/changelog/v0.4.0/)
