### ISSUE TITLE
Feature: Allow saving incomplete meal plans

### ISSUE THREAD

**Issue by belindax** [hay-kot/mealie#19]
Hi, not sure if this is a bug, but I'm guessing this might be by design, so logging it as a feature request. I tried to save a meal plan where I only selected recipes on some of the days and where the other ones are blank, but it looks like the meal plan won't save unless all of the days have a recipe selected. It would be awesome if I could still save an incomplete meal plan and go back and edit it once I decide on meals for those days.

**Comment by hay-kot** [comment]
This seems like a super reasonable feature, I've added to it to the todo's list in dev/dev-notes.md Thanks!

**Comment by hay-kot** [comment]
I've added this to the dev branch and will be available in the next patch sometime this week.
