### ISSUE TITLE
Norwegian characters imported incorrectly (varies from site to site)

### ISSUE THREAD

**Issue by conrad82** [hay-kot/mealie#191]
**Describe the bug**
Imported a norwegian recipe from https://www.tine.no/oppskrifter/middag-og-hovedretter/kjott/chili-con-carne
The norwegian characters æøå were imported incorrectly, e.g. smør becomes smÃ¸r (smør=butter)

However, importing from https://www.matoppskrift.no/oppskrift/sunnmoerslefse , the norwegian characters look OK.

I am not sure if this is an issue with the importer or the site www.tine.no , because on the web page it looks OK..
It looks like a character encoding issue.
If it is an easy fix, it would be great to fix it, but I understand if it is out of your hands.

**Steps To Reproduce**
Please be specific!
1. Use import from url and select https://www.tine.no/oppskrifter/middag-og-hovedretter/kjott/chili-con-carne
2. Observe that norwegian characters æ,ø,å become garbled in the imported recipe.

**Sample Code**
NA

**Expected behavior**
æ, ø, å imported as æ, ø, å

**Actual Behavior**
æ, ø, å imported as ?, Ã¸, Ã¥

**Screenshots**
www.tine.no: 
![image](https://user-images.githubusercontent.com/17353007/109317309-dddc9300-784c-11eb-80f0-54bc3335c131.png)

Mealie: ![image](https://user-images.githubusercontent.com/17353007/109317222-c69da580-784c-11eb-840c-99ae2653a9e1.png)

**Device Information (please complete the following information):**
 - OS: Server: Ubuntu Server LTS 20.04 (Raspberry Pi), Desktop: Manjaro
 - Deployment: docker-compose, image: hkotel/mealie:latest
 - Browser: Firefox
 - Version:  v0.3.0

**Additional context**
NA

**Comment by conrad82** [comment]
Related to https://github.com/hay-kot/mealie/issues/90 ?

**Comment by sephrat** [comment]
Looks like an encoding issue.
In the broken recipe, ø is represented as \u00c3\u00b8. The data comes from a json script tag.
In the working recipe, it is represented as \u00f8. The data is in the html body itself.

I can't quite grasp the root issue yet but my guess would be an issue in a module we reuse (scrape_schema_recipe).
@hay-kot Any experience with that?
