### ISSUE TITLE
Search results limited to 100 entries in database

### ISSUE THREAD

**Issue by jrhorrisberger** [hay-kot/mealie#198]
**Describe the bug**
Recipes over 100 do not show in search results due to &num=100 parameter in API call

**Steps To Reproduce**
1.) Add 101 recipes
2.) Only 100 recipes will be returned in API call for search

**Sample Code**
Assuming it is this line ` async allByKeys(recipeKeys, num = 100) {` in `mealie/frontend/src/api/recipe.js`

**Expected behavior**
All recipes added should be searchable

**Actual Behavior**
Results are truncated to 100 items

**Screenshots**

![image](https://user-images.githubusercontent.com/12725811/110196745-32af7900-7e0c-11eb-9d2c-dca8da008520.png)

**Device Information (please complete the following information):**
All

**Additional context**
Just want to say this is awesome and thank you for creating this! Using it to plan weekly meals and use home assistant to send notifications with meal name/photo/ingredients in the morning for that day

**Comment by hay-kot** [comment]
You've discovered I'm a bad programmer! That was a hold over from development way back when. I've adjusted it to 9999 for the time being until I have time to get proper pagination working. Once the new build is done, you should be able to pull more than 100! Thanks for the kind words.

> Just want to say this is awesome and thank you for creating this! Using it to plan weekly meals and use home assistant to send notifications with meal name/photo/ingredients in the morning for that day

This is exactly why I built this! love to see it in action.

**Comment by waschinski** [comment]
> get proper pagination working

Speaking of that, would you rather implement pagination, infinite loading or something like a "load more" button?

**Comment by hay-kot** [comment]
> Speaking of that, would you rather implement pagination, infinite loading or something like a "load more" button?

I think I'm more of a fan of infinite loading, but I know that can be polarizing.

**Comment by waschinski** [comment]
> I think I'm more of a fan of infinite loading, but I know that can be polarizing.

I think it's the preferred way for mobile usage so I think it could be a good fit for mealie.

**Comment by hay-kot** [comment]
Since this initial issue has been solved i'm going to close this issue. You can track #271 for proper infinite scroll support.
