### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#2]
Currently the "Logo" for the site is a Font Awesome Icon. I'd love to have a legit "logo" If anyone wants to submit a logo please do.

**Comment by obbardc** [comment]
also the logo in the readme is missing ;-)

**Comment by J-O-S-H-C** [comment]
Describe a message you want a logo to convey.

**Comment by ministryofsillywalks** [comment]
Maybe an upside down fork as the M?
Something nice and simple like this 
https://www.vecteezy.com/vector-art/561380-good-food-spoon-fork-knife-logo-icon-vector 
If you can go all caps a sideways fork could be the  last E?
Somewhat like this 
https://www.vecteezy.com/vector-art/1109882-food-with-spoon-and-fork-logotype-concept 
I'm not great at this and can't promise anything but I might try something later today.

**Comment by mtoohey31** [comment]
Once we've got a logo we should change the favicon for the frontend too.

**Comment by J-O-S-H-C** [comment]
![mealio](https://user-images.githubusercontent.com/39581053/103489010-081e5100-4dc6-11eb-89a7-1cea7a22658d.png)

**Comment by J-O-S-H-C** [comment]
![mealie](https://user-images.githubusercontent.com/39581053/103489013-12404f80-4dc6-11eb-977e-b7b57ea97266.png)

**Comment by J-O-S-H-C** [comment]
> 
> 
> Maybe an upside down fork as the M?
> Something nice and simple like this
> https://www.vecteezy.com/vector-art/561380-good-food-spoon-fork-knife-logo-icon-vector
> If you can go all caps a sideways fork could be the last E?
> Somewhat like this
> https://www.vecteezy.com/vector-art/1109882-food-with-spoon-and-fork-logotype-concept
> I'm not great at this and can't promise anything but I might try something later today.

![mealie](https://user-images.githubusercontent.com/39581053/103489029-3f8cfd80-4dc6-11eb-915e-84028c42a6f2.png)
