### ISSUE TITLE
Feature: multiple recipes per day in meal plans

### ISSUE THREAD

**Issue by apesic** [hay-kot/mealie#20]
Hi, thanks for releasing this--I've been searching for something like this for a while and even in its early state it's looking great. One feature that would be nice to have is support for selecting multiple recipes for a given day in a meal plan (for example, a side dish and a main course).

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
