### ISSUE TITLE
Random Button in Planner page doesn't work

### ISSUE THREAD

**Issue by XxTashToshxX** [hay-kot/mealie#201]
Currently trying to plan meals for the week and wanted to test out the random button however nothing happens when clicking on it.

**Comment by hay-kot** [comment]
Do you have meal categories selected in the settings page? If no categories are selected the random button won't work. This is fixed in the next release, but currently you need to have atleast one category included in the meal plan categories on the setting page.

**Comment by XxTashToshxX** [comment]
That fixed it, thanks!
