### ISSUE TITLE
Random Button on meal planner does not load random meals

### ISSUE THREAD

**Issue by Shaneo234** [hay-kot/mealie#202]
**Describe the bug**
When generating a random meal from /meal-plan/planner using "RANDOM" button a error is return in console:

![image](https://user-images.githubusercontent.com/36048324/110481461-80afcf80-80df-11eb-932f-08d78f00a565.png)

**Steps To Reproduce**
Please be specific!
1. Go to Planner
2. Ensure you have recipes 
3. Generate a meal plan for time frame
4. Hit "Random"

**Expected behavior**
A meal plan to be randomized and generated

**Actual Behavior**
A error is presented in the console (see image attached)

**Screenshots**
![image](https://user-images.githubusercontent.com/36048324/110481708-c371a780-80df-11eb-8d31-e5f0bbcfe052.png)
![image](https://user-images.githubusercontent.com/36048324/110481736-cb314c00-80df-11eb-88a0-3617bd02f6c9.png)

**Device Information (please complete the following information):**
 - OS: Docker 19.03.14 Running on Unraid version 6.9.1

**Comment by hay-kot** [comment]
Related to https://github.com/hay-kot/mealie/issues/201
?
