### ISSUE TITLE
Nothing in database: mealie_v0.2.0.sqlite -->  mealie_v0.2.1.sqlite

### ISSUE THREAD

**Issue by baj702** [hay-kot/mealie#205]
**Describe the bug**
Updated docker image (latest) on Mar 7 or 8. No recipes show up. Browsing the sqlite db doesn't show anything either. I have a _v0.2.0 and a _v0.2.1 sqlite db. Importing a backup before the update seems to get the recipes back, I'll have to play with it more to see...

**Comment by hay-kot** [comment]
This is to be expected when updating to a new beta version. I haven't implemented database migrations and don't plan on it until the database is in a steady place. When upgrading you'll need to export and import your recipes. When we get to a more stable position this will happen automatically. In the future I'll mark each release with a 'app' version and 'database' version, so database changes are more clear.
