### ISSUE TITLE
[dev] Giving a recipe stars deletes the ingredients & instructions of all other recipes

### ISSUE THREAD

**Issue by Artanicus** [hay-kot/mealie#216]
If a recipe is edited to add a star rating, all other recipes except the one edited lose their entire ingredient & instructions data.

Testing at d621e4e580

**Steps To Reproduce**
1. Take a backup of your recipes
2. Verify recipe A & B to have ingredients & instructions
3. Edit recipe A to give it 4 stars, save.
4. Verify recipe A & B to have ingredients & instructions

**Expected behavior**

both recipes A & B contain ingredients & instructions and recipe A has a rating of 4 stars.

**Actual Behavior**

Recipe A is as expected but recipe B has lost it's ingredients & instructions.

**Device Information **
 - OS: Ubuntu 20.04
 - Deployment: Python application
 - Browser: Chrome
 - Version: Version 89.0.4389.82 (Official Build) (64-bit)

**Additional context**
First triggered this by accident, after that managed to repro as above.

**Comment by Artanicus** [comment]
Adding tags after the fact also triggers the same issue, which I found out the hard way.

**Comment by hay-kot** [comment]
I was able to fix this in #218. Basically I wrote some hacky code because I didn't understand some of the options in SqlAlchemy. I've not set the columns up appropriately. After I made those changes I wasn't able to replicate the issue.

**Comment by Artanicus** [comment]
Have not been able to reproduce anymore, so lgtm!
