### ISSUE TITLE
Feature: Set Dates in Meal Planner to start(Sun) and end(Sat) of current week

### ISSUE THREAD

**Issue by ddouglas** [hay-kot/mealie#22]
Title says it all. right now, when you load the page, you have to select the dates. Also might be helpful to have an increment and decrement by week button

**Comment by obbardc** [comment]
sounds good, but my weeks start on mon and end on sun :p
so it would be great to be able to choose that also

**Comment by ddouglas** [comment]
Fair point, could be an env setting. I noticed there isn't the concept of
users yet. Is that intentional?

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
