### ISSUE TITLE
Random meal planner should not repeat options

### ISSUE THREAD

**Issue by Na3blis** [hay-kot/mealie#221]
I currently have about 10 items, and selected random, for a selection of 4 days. However, it it frequently chooses multiple duplicates, one time all 4 days it chose the same item. Random should be pseudo random and should not select an already selected meal. Either that, or there should be an option to disable repeat meals, in case people who want to plan out more days than they have different meal options.

**Comment by hay-kot** [comment]
This should be fairly easy to implement. Someone would just need to adjust the `get_random` function in the `frontend/src/components/MealPlan/MealPlanNew.vue` component to filter out selected items.

**Comment by hay-kot** [comment]
This has been added in [v0.4.0](https://hay-kot.github.io/mealie/changelog/v0.4.1/) 🎉
