### ISSUE TITLE
Modal dialogs such as login do not submit by pressing enter

### ISSUE THREAD

**Issue by Artanicus** [hay-kot/mealie#223]
**Describe the bug**
Modal dialogs such as the login modal and import by link modal do not perform the expected action when pressing enter.
- The login dialog does nothing on enter, would expect it to submit the form
- The link import modal refreshes the page but does not submit the form, this is especially confusing since one may assume it was imported.

**Steps To Reproduce**
1. Press `Log In` from menu (or import from recipe add)
2. Enter credentials / url
3. Hit the enter key

**Expected behavior**
Web form is submitted, login / import is performed.

**Actual Behavior**
Nothing happens for login / page refreshes without import. 

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: "dev"
 - Browser: Chrome
 - Version: dev branch @ 223c198e83, Chrome: 89.0.4389.90 (Official Build) (64-bit)

**Additional context**
I believe the issue is present in both master & dev branches.

**Comment by hay-kot** [comment]
Should be fixed with PR #244. Let me know if I missed any in the list over there.

**Comment by Artanicus** [comment]
- Works great now for login!
- Recipe import seems to work but has slightly different behavior. If you click submit, the page loads to the now imported recipe. If you hit enter the import seems to succeed but the page is reloaded instead of redirecting to the newly imported recipe.
- Group creation works!
- Signup via link seems to hang, but it starts the hang both by button & enter so that's good enough in the scope of this bug :D
- User creation works!
- Theme add works!

So all good except for the differing behavior for recipe import, i.e. refresh vs. open up imported recipe. Opening the recipe is less confusing so that would be nice to have also on enter.

**Comment by hay-kot** [comment]
> Recipe import seems to work but has slightly different behavior. If you click submit, the page loads to the now imported recipe. If you hit enter the import seems to succeed but the page is reloaded instead of redirecting to the newly imported recipe.

and 

> Signup via link seems to hang, but it starts the hang both by button & enter so that's good enough in the scope of this bug :D

Both should be fixed in PR 225 👍, I'm thinking we're super close to a release candidate 🎉
