### ISSUE TITLE
Dark Mode: Color issues

### ISSUE THREAD

**Issue by zackbcom** [hay-kot/mealie#23]
What a great app. Whole family loves it. Found one issue with the dark mode.
I saw that the colors are randomized. Maybe it would be good to set a default set of colors that are accessible, following the WCAG 2.1 Guidelines.

I'm currently working on updating our application at work, I might have some free time to work on some enhancements.

Saw some issues with the generated colors and the text.
![image](https://user-images.githubusercontent.com/1888323/103498102-35d8b980-4e09-11eb-97bc-e25f51ce6afe.png)

**Comment by hay-kot** [comment]
I've changed the default info color to #4990BA. I've also removed the random color generation and replaced it with the default theme colors when creating a new theme. I'll keep this in mind for future enhancements. Thanks!
