### ISSUE TITLE
[v1.0.0b] - Importing ingredients as decimal 

### ISSUE THREAD

**Issue by ThePagel** [hay-kot/mealie#2408]
### First Check

- [X] This is not a feature request
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Mealie documentation, with the integrated search.
- [X] I already read the docs and didn't find an answer.

### What is the issue you are experiencing?

If a ingredient is calling for 1/2 cup of something it will display as 0.5 in mealie. If it calls for 1 1/2 it displays as 1.5. I feel like I'm crazy because I do not see this mentioned anywhere. I was able to get one to import properly and the only difference I noticed was it import properly if the ingredient is the same font size as everything else. if it is a smaller font size it imports as a decimal. 

**Details**
Version: v1.0.0beta-5
Build: ee121a12f8db33ecb4db5f8582f7ea9788d019e4
Application Mode: Production
Demo Status: Not Demo
API Port: 9000
API Docs: Enabled
Database Type: sqlite
Recipe Scraper Version: 14.20.0

**Checks**
Secure Site: No
Server Side Base URL: Yes
LDAP Ready: No
Email Configured: No
Docker Volumes: success

### Deployment

Docker (Linux)

### Deployment Details

version: "3.7"
services:
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment:
    # Set Frontend ENV Variables Here
      - API_URL=http://mealie-api:9000 # 
    restart: always
    ports:
      - "9925:3000" # 
    volumes:
      - mealie-data:/app/data/ # 
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
    # Set Backend ENV Variables Here
      - ALLOW_SIGNUP=true
      - PUID=1000
      - PGID=1000
      - TZ=America/Anchorage
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.yourdomain.com
    restart: always

volumes:
  mealie-data:
    driver: local

**Comment by michael-genson** [comment]
Are you using the unit/food store? If yes, each unit has a setting to display as a fraction or a decimal.

You can edit your units at `https://YOUR-URL.com/group/data/units `

**Comment by ThePagel** [comment]
Thanks for the reply, I seeded fractions and it didn't help. Is this maybe a scraper issue? I got one to work properly in all recipes but can't find it now... below is a link to one that doesn't work right and one that does. 

imports decimal 
https://www.allrecipes.com/recipe/233070/dads-day-strata/

imports fraction 
https://www.tasteofhome.com/recipes/easy-seafood-salad/

**Comment by michael-genson** [comment]
Oh interesting, if you're scraping from websites and it's coming as a decimal it's probably an issue with the site. I'm away from a computer so I can't check, but I'd bet the site stores the quantities as decimals and they just render fractions

**Comment by michael-genson** [comment]
If you import the recipe, then parse it (using the food and unit stores) your fraction settings will then work

**Comment by ThePagel** [comment]
Got it working thanks, is there not a way to get to /group/data/units via the gui?

**Comment by michael-genson** [comment]
No problem! Yes, you have to click on your name (in the upper left), then scroll down to "Manage Data" and it takes you to the Food Data page (and from there you can switch to Units, Labels, etc.)
