### ISSUE TITLE
'detail: Not found' when trying to access the /docs (or API)

### ISSUE THREAD

**Issue by wtrdk** [hay-kot/mealie#247]
My mealie (v0.4) setup works just fine, except for the API. I can't get it to work. When I try to access 'https://mealie.mydomain.nl/docs' I get ```{"detail":"Not Found"}```

In the container logs it says:
```
Successfully started Caddy (pid=14) - Caddy is running in the background
INFO:     Started server process [23]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
Pending jobs:
    update_webhook_schedule (trigger: interval[0:30:00], pending)
    backups (trigger: cron[hour='0', minute='0'], pending)
    Home (trigger: cron[hour='0', minute='0'], pending)
INFO:     xxx.xxx.xxx.xxx:0 - "GET /docs HTTP/1.1" 404 Not Found
```

My docker-compose:
```
version: "3.1"
services:
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
      - 9000:9000
    environment:
      DB_TYPE: sqlite
      TZ: Europe/Amsterdam
      API_DOCS: 'true'
    volumes:
      - /opt/mealie/data/:/app/data
    labels:
         - "traefik.enable=true"
         - "traefik.http.routers.mealie.entrypoints=web"
         - "traefik.http.routers.mealie.rule=Host(`mealie.mydomain.nl`)"
         - "traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme=https"
         - "traefik.http.routers.mealie.middlewares=mealie-https-redirect"
         - "traefik.http.routers.mealie-secure.entrypoints=websecure"
         - "traefik.http.routers.mealie-secure.rule=Host(`mealie.mydomain.nl`)"
         - "traefik.http.routers.mealie-secure.tls=true"
         - "traefik.http.routers.mealie-secure.tls.certresolver=default"
         - "traefik.http.routers.mealie-secure.service=mealie"
         - "traefik.http.services.mealie.loadbalancer.server.port=80"
         - "traefik.docker.network=-proxy"
 ```
 
Result in browser and iOS shortcut:

https://imgur.com/a/ENT9tLT

**Comment by hay-kot** [comment]
Try setting it API_DOCS to "True" instead if "true"

**Comment by wtrdk** [comment]
Thanks, that worked for the docs part. The iOS shortcut still gives the
same repelt.


Op do 1 apr. 2021 om 16:38 schreef Hayden ***@***.***>

**Comment by hay-kot** [comment]
> The iOS shortcut still gives the same result, I'm not sure why that shortcut doesn't work...

This is because you are now required to have a token to create recipes on the server. I'm not sure how to address that with the iOS shortcut. I'm not an iOS user.

**Comment by wtrdk** [comment]
Can you help me with how to get a token and how to use it in an API post-method? I can't seem to find it in the documentation.... (Maybe my fault...)

**Comment by natpuch** [comment]
There is an example in the docs on the dev branch [API Usage](https://github.com/hay-kot/mealie/blob/dev/docs/docs/getting-started/api-usage.md). You should check the `authentification` function to see how to get a token.

**Comment by wtrdk** [comment]
Thanks!  I'll try to get it working!

**Comment by rastacalavera** [comment]
@wtrdk were you able to get the iOS shortcut working with a token? It would be great to update the docs to explain that process.

**Comment by wtrdk** [comment]
Hi, I'm sorry, but up until today I've not been able to get it working, unfortunately. It would be great if it works. So if anyone else has an idea how to get this shortcut working, that would be great!
