### ISSUE TITLE
RP4/docker - error: can't initialize time (workaround included)

### ISSUE THREAD

**Issue by cklann1** [hay-kot/mealie#249]
**Describe the bug**

Container fails startup on RP4 2g running:
Linux rp4-2g 5.10.17-v7l+ #1403 SMP Mon Feb 22 11:33:35 GMT 2021 armv7l GNU/Linux

Container log shows errors:

```bash
    Fatal Python error: init_interp_main: can't initialize time,
    Python runtime state: core initialized,
    PermissionError: [Errno 1] Operation not permitted,
    ,
    Current thread 0xb6f8a390 (most recent call first):,
    <no Python frame>,
    {"level":"info","ts":1617282122.7082403,"msg":"using provided configuration","config_file":"./Caddyfile","config_adapter":""},
    {"level":"warn","ts":1617282122.7122238,"logger":"admin","msg":"admin endpoint disabled"},
    {"level":"info","ts":1617282122.7126932,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x3cba140"},
    {"level":"info","ts":1617282122.7139606,"logger":"tls","msg":"cleaned up storage units"},
    {"level":"info","ts":1617282122.715005,"msg":"autosaved config","file":"/root/.config/caddy/autosave.json"},
    {"level":"info","ts":1617282122.71505,"msg":"serving initial configuration"},
    Successfully started Caddy (pid=14) - Caddy is running in the background,
    Fatal Python error: init_interp_main: can't initialize time,
    Python runtime state: core initialized,
    PermissionError: [Errno 1] Operation not permitted,
    ,
    Current thread 0xb6f33390 (most recent call first):,
    <no Python frame>,
```
**Steps To Reproduce**
1) Built container using docker-compose from <https://hay-kot.github.io/mealie/getting-started/install/>:
  ```bash
    pi@rp4-2g:~/mealie$ docker pull hkotel/mealie
    pi@rp4-2g:~/mealie$ nano docker-compose.yml
    pi@rp4-2g:~/mealie$ mkdir data
    pi@rp4-2g:~/mealie$ docker-compose up -d
  ```
2) Started container (using Portainer)

3) No joy :(

**Additional context**
Successfully implemented this workaround (fix?) on the host rp4-2g found here: <https://github.com/linuxserver/docker-papermerge/issues/4#issuecomment-735236388>
```bash
wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb

sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
```

**Joy!:)**

**Comment by sephrat** [comment]
I don't have a RP4 to play around but from what you shared, I think your solution is a fix, not a workaround. The guys at Linuxserver properly documented this issue: https://docs.linuxserver.io/faq#libseccomp
Maybe the one thing we can do is document it in our docs as well.

**Comment by cklann1** [comment]
Thanks! I'd be happy to help document with some guidance.

**Comment by sephrat** [comment]
You could help by creating a pull request with changes to the documentation.
The files that generate the docs website are here: https://github.com/hay-kot/mealie/tree/master/docs/docs

**Comment by Pyrrhu5** [comment]
As of today, this work-around doesn't solve the issue anymore

**Comment by Pyrrhu5** [comment]
Issue still raising on buster.

To fix (temporarily, it's quite lame on the security level) use `privileged: true` in `docker-compose.yml`

Example:

```yml
version: "3.1"
services:
  mealie:
    privileged: true
    container_name: mealie
    image: hkotel/mealie:latest
    restart: always
    ports:
      - 9925:80
    environment:
      DB_TYPE: sqlite
      TZ: Europe/Paris
    volumes:
      - ./mealie/data/:/app/data
```

**Comment by crixster** [comment]
> Issue still raising on buster.
> 
> To fix (temporarily, it's quite lame on the security level) use `privileged: true` in `docker-compose.yml`
> 
> Example:
> 
> ```yaml
> version: "3.1"
> services:
>   mealie:
>     privileged: true
>     container_name: mealie
>     image: hkotel/mealie:latest
>     restart: always
>     ports:
>       - 9925:80
>     environment:
>       DB_TYPE: sqlite
>       TZ: Europe/Paris
>     volumes:
>       - ./mealie/data/:/app/data
> ```

GOD BLESS YOU MAN! Finally got it working on my pi4
