### ISSUE TITLE
Unable to import from Nextcloud Recipes zip

### ISSUE THREAD

**Issue by dhcrain** [hay-kot/mealie#254]
**Describe the bug**
When importing a zip from my Nextcloud Recipes, as [described here](https://hay-kot.github.io/mealie/site-administration/migration-imports/), I get an error of 
```
Failed Imports
__MACOSX
nextcloud_recipes
```

**Steps To Reproduce**
Please be specific!
1. Go to admin/migrations
2. Upload Nextcloud Recipes .zip ([My File](https://www.dropbox.com/s/5zuthy5tf3w74mr/nextcloud_recipes.zip?dl=0))
3. Click Import

**Sample Code**
From the logs:
```
ERROR:root:Failed Nextcloud Import: nextcloud_recipes
ERROR:root:
Traceback (most recent call last):
  File "./mealie/services/migrations/nextcloud.py", line 79, in migrate
    recipe = import_recipes(dir)
  File "./mealie/services/migrations/nextcloud.py", line 34, in import_recipes
    with open(recipe_file, "r") as f:
UnboundLocalError: local variable 'recipe_file' referenced before assignment
```

**Expected behavior**
To import

**Actual Behavior**
Does not import

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Deployment: Docker, use instructions from [here](https://hay-kot.github.io/mealie/getting-started/install/)
 - Browser: Chrome
 - Version: 0.40

**Comment by hay-kot** [comment]
Your zipfile does not match the expected format. `nextcloud_recipes/Slow_Cooker_Chicken_Noodle_Soup/` is the path listed inside your .zip file. Each recipe should be a top level folder `Slow_Cooker_Chicken_Noodle_Soup/`. I also noticed a bunch of MacOS 'hidden' files. That may cause other problems as well, I'm not sure. There may be an underlying issues with how MacOS handles zipping files.

A better solution to this may be to recursively walk through the directory structure looking for `recipe.json` files or something or some sort of match statement... I may look into this at some point.

**Comment by mhzawadi** [comment]
This looks to handle my issue too

If it helps Im trying to import some 288 recipes from nextcloud, the only way to download the zip is to get the entire Recipes folder

**Comment by dhcrain** [comment]
If any Mac users want to re-zip their nextcloud with out the hidden files you can try this.
In the terminal, in the directory that has all the files you want to zip run `zip -r data.zip . -x ".*" -x "__MACOSX"`
