### ISSUE TITLE
Suggestion: individual and multi/shareable user recipes

### ISSUE THREAD

**Issue by Vinestou** [hay-kot/mealie#27]
I know there is no user implementation right now but maby something to think about:

I'm personally going to serve (pun intended) this application to my girlfriend, her mom, my mom and her sister to create a database of all family recipes and favorites.

What I would suggest is using per user recipes which are group shareable with a checkbox from the recipe edit page.

![example mealie](https://user-images.githubusercontent.com/52471580/103542672-931e4a80-4e9d-11eb-99bc-363b9feb2929.jpg)

The cleanest method would be a separate tab with shared recipes, preventing clutter on your personal recipe page/list.

EDIT:
Maby add a group model: friends, family

**Comment by mdrichardson** [comment]
On a related note, when implementing users, it would be great to be able to have user groups with read/write permissions. Something like an ability to create user groups and set R/W permissions for making changes to:

* users
* user groups
* Settings menu
* recipe groups
* R/W permissions within recipe groups, per user or group
  * For example. I might want to give my wife permissions to add recipes, but if I share them with her mother, I'd only want her mother to be able to view them, but if I share them with my mother, maybe I'd want her to only view some of my recipes and be able to add her own

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
