### ISSUE TITLE
Incorrect Label on Tag Add

### ISSUE THREAD

**Issue by kushfest** [hay-kot/mealie#272]
**Describe the bug**
Small wording error on the add tag modal. Instead of saying "Tag Name is required" it says "Theme Name is required"

**Steps To Reproduce**
Please be specific!
1. In the tags section of a recipe click "+" to add a tag.

**Screenshots**
<img width="488" alt="image" src="https://user-images.githubusercontent.com/13265036/113972442-7a506880-97ef-11eb-8384-e02ad2c45c98.png">

**Comment by hay-kot** [comment]
Weird. I though I caught this in the v0.4.1 release. Can you let me know what docker tag/version you're running?

**Comment by kushfest** [comment]
I'm running 0.4.1 using the 'dev' docker tag.

**Comment by hay-kot** [comment]
This should be fixed. Can you re-pull the image and tell me if you still have the same issue? What page are you seeing the issue?

**Comment by kushfest** [comment]
Awesome! Looks to be fixed. This is on a recipe page, when adding a tag. Here's what I see now:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/13265036/114133923-ae915b00-98bb-11eb-8df7-78fcc86e42fa.png">
