### ISSUE TITLE
Incorrect Port Show in Logs

### ISSUE THREAD

**Issue by kushfest** [hay-kot/mealie#273]
**Describe the bug**
This is another minor labeling thing I've noticed. When mealie starts up it shows in the logs that it's running on port 9000 even though that's not the case. I think port 9000 was recently phased out as the default port (I'm guessing because portainer uses that port), so this must be leftover from before that change.

**Screenshots**
<img width="527" alt="image" src="https://user-images.githubusercontent.com/13265036/114134201-324b4780-98bc-11eb-917e-8a1c51792c6a.png">

**Device Information (please complete the following information):**
 - OS: Ubuntu
 - Deployment: Docker using 'dev' tag
 - Browser: [e.g., chrome, safari]
 - Version: 0.4.1

**Comment by sephrat** [comment]
The log is correct: Uvicorn actually listens to port 9000.
What you don't see is that Caddy proxies traffic from external port 80 to internal port 9000.
https://github.com/hay-kot/mealie/blob/master/Caddyfile

**Comment by kushfest** [comment]
Oh! My bad. I misunderstood that change. Feel free to close this.

**Comment by hay-kot** [comment]
Thanks @sephrat!
