### ISSUE TITLE
Some recipes  cause backup to crash

### ISSUE THREAD

**Issue by natpuch** [hay-kot/mealie#275]
**Describe the bug**
Some recipes cause backup to crash. I have only found one recipe that causes problem (I think it worked in v0.3.0 but not sure).  
The problem is probably due to the `/` in the name of the recipe.

**Steps To Reproduce**
1. Import the following recipe [https://www.marmiton.org/recettes/recette_travers-de-porc-a-la-texane-loin-ribs_22510.aspx](https://www.marmiton.org/recettes/recette_travers-de-porc-a-la-texane-loin-ribs_22510.aspx)
2. Try to create backup from the settings
3. Backup is not created

**Expected behavior**
Backup is created.

**Actual Behavior**
Backup is not created. By checking in the temp files, it can be seen that the backup stopped just before the aforementioned recipe.

**Device Information (please complete the following information):**
 - OS: Synology DSM (Linux based)
 - Deployment: docker-compose
 - Browser: Firefox
 - Version: v0.4.1

**Additional context**

**Comment by sephrat** [comment]
Looks like it doesn't like the '/' in the recipe name when generating the json file.
```
File "mealie\services\backups\exports.py", line 85, in _write_json_file
    with open(out_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'mealie\\dev\\data\\.temp\\test_2021-Apr-09\\recipes\\Travers de porc à la texane \\ loin ribs.json'   
```
We need to sanitize the file name. I can look into that.

In the meantime, remove the '/' from your recipe name and it will work.

**Comment by natpuch** [comment]
Thank you. Removing the '/' in the recipe name worked.
