### ISSUE TITLE
Cannot restore from backup

### ISSUE THREAD

**Issue by legobuild** [hay-kot/mealie#280]
**Describe the bug**
Database was wiped out after upgrade to 4.0.  I have a full backup from before the upgrade, but nothing happens when I select it from the Backup pages. 

**Steps To Reproduce**
Please be specific!
1. Go to Settings->Backup
2. Select previous full backup from the Available Backups section
3. Uncheck all options except for Recipes and click Import
4. Popup goes away, no error or confirmation message appears

**Sample Code**

**Expected behavior**
Recipes in backup are uploaded.

**Actual Behavior**
Nothing.

**Screenshots**
Error log:
`/app/mealie/run.sh: line 8: syntax error: bad substitution
Skipping virtualenv creation, as specified in config file.
/usr/local/bin/python: can't open file '/app/db/init_db.py': [Errno 2] No such file or directory
Skipping virtualenv creation, as specified in config file.
/usr/local/bin/python: can't open file '/app/services/image/minify.py': [Errno 2] No such file or directory
Production
{"level":"info","ts":1618007282.048403,"msg":"using provided configuration","config_file":"./Caddyfile","config_adapter":""}
{"level":"warn","ts":1618007282.0530756,"logger":"admin","msg":"admin endpoint disabled"}
{"level":"info","ts":1618007282.0533345,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00035a9a0"}
{"level":"info","ts":1618007282.0537364,"logger":"tls","msg":"cleaned up storage units"}
{"level":"info","ts":1618007282.053978,"msg":"autosaved config","file":"/root/.config/caddy/autosave.json"}
{"level":"info","ts":1618007282.0539906,"msg":"serving initial configuration"}
Successfully started Caddy (pid=17) - Caddy is running in the background
INFO:     Started server process [26]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
Pending jobs:
    update_webhook_schedule (trigger: interval[0:30:00], pending)
    backups (trigger: cron[hour='0', minute='0'], pending)
    Home (trigger: cron[hour='0', minute='0'], pending)
INFO:     172.18.0.8:0 - "GET /api/debug/version HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/backups/available HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/recipes/summary HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/tags HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/categories HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/auth/refresh HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/groups/self HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/backups/available HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/recipes/grilled-chicken-fajitas/image?image_type=small HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/site-settings HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/site-settings/custom-pages HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/users/0/image HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/users/1/image HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/users/self HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/users/1/image HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/backups/available HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/backups/available HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "POST /api/backups/Post-Dokuwiki%20Migration%20Full%20Backup_2021-Mar-05.zip/import HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 111, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 566, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 201, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 150, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/site-packages/starlette/concurrency.py", line 34, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./mealie/routes/backup_routes.py", line 84, in import_database
    return imports.import_database(
  File "./mealie/services/backups/imports.py", line 304, in import_database
    recipe_report = import_session.import_recipes()
  File "./mealie/services/backups/imports.py", line 54, in import_recipes
    recipes = ImportDatabase.read_models_file(
  File "./mealie/services/backups/imports.py", line 237, in read_models_file
    all_models.append(model(**file_data))
  File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 400, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for Recipe
recipeInstructions -> 3 -> text
  none is not an allowed value (type=type_error.none.not_allowed)
INFO:     172.18.0.8:0 - "GET /api/recipes/summary HTTP/1.1" 200 OK
INFO:     172.18.0.8:0 - "GET /api/backups/available HTTP/1.1" 200 OK`

**Device Information (please complete the following information):**
 - OS: Windows 10, Mac
 - Deployment: docker-compose
 - Browser: Chrome on Windows, Safari on Mac, iOS
 - Version: 0.4.1

**Additional context**
All my previous backups show the same behavior. I tried creating a new recipe, creating a backup, deleting the recipe, and importing that backup. This works successfully.

**Comment by hay-kot** [comment]
Can you provide your backup file for testing?

**Comment by waschinski** [comment]
v0.4.1a still seems to have database issues. It now starts the application fine but all data is gone. I didn't try restoring a backup, but when switching back to v0.4.0 all was good again.

**Comment by legobuild** [comment]
Weird. v0.4.0 had the same result, but I went back to v.0.3.0 and it restored.

**Comment by hay-kot** [comment]
> Weird. v0.4.0 had the same result, but I went back to v.0.3.0 and it restored.

I believe you and @waschinski are experiencing unrelated issues. he was able to post his log, I created an issue to track the error he was experiencing #281. I believe you have an issue with the validation of a type on one of the recipes you are trying to import. I'd like to verify and see if I can't get the issue resolved, but I'd need your backup file to identify what the core issue is.

**Comment by legobuild** [comment]
[MealieBackup.zip](https://github.com/hay-kot/mealie/files/6289065/MealieBackup.zip)

Here's my backup file. I tried deleting all but one recipe but kept getting different error messages in the logs.

**Comment by hay-kot** [comment]
> [MealieBackup.zip](https://github.com/hay-kot/mealie/files/6289065/MealieBackup.zip)
> 
> Here's my backup file. I tried deleting all but one recipe but kept getting different error messages in the logs.

Looks like one of the steps in your recipes has a text of `null` which is not a valid option. No idea how it got that far...But I was able to remove it and get it to import. Give this archive a try on the new v0.4.1a version and let me know how it goes


[Archive.zip](https://github.com/hay-kot/mealie/files/6290723/Archive.zip)
