### ISSUE TITLE
[v0.4.1a] Mealie fails to parse ENV Variable PRODUCTION on startup

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#281]
**Describe the bug**
Some user experience an error on startup where the setup is halted when the environmental variable that determines if the app is running in production cannot be parsed to a bool. 

**Steps To Reproduce**
Please be specific!

Unsure of the cause

Relevant log
```
PRODUCTION

  value could not be parsed to a boolean (type=type_error.bool)
```

A potential solution may be to set the environmental variable `ENV=true`

**Comment by waschinski** [comment]
Thanks for pointing out about the `ENV=true`. For some reason in my environment it was set to `ENV=prod`. I don't remember explicitly setting it like that but my workflow for upgrading docker images is using Portainer and simply doing an `Duplicate/Edit` with just changing the image version (if not latest). Maybe `ENV` used to be different (non boolean) in an older version?

Anyway, completely removing that environment variable in my setup makes Mealie start again without the error popping up. But even though the log says `Database exists` no data is being used. This sounds to be a separate issue though. I will open an issue for that.

**Comment by hay-kot** [comment]
Before we should check to make sure that the `ENV` variable existed. If it existed, regardless of it's value we would run in production mode. It was changed to look for an actual boolean value and parse to text to determine what it was. So since `prod` has no boolean value, it caused a startup error.

 I'm thinking i'm going to depreciate the ENV variable and set an explicit `PRODUCTION` variable that accepts a True/False and will default to True. I think that's a more explicit way to deal with it.

**Comment by waschinski** [comment]
This sounds like a good idea. Also there seems to be a bug when the `ENV` env variable is not set at all. See https://github.com/hay-kot/mealie/issues/283#issuecomment-817209795.
