### ISSUE TITLE
After upgrading to v0.4.1a all data is missing

### ISSUE THREAD

**Issue by waschinski** [hay-kot/mealie#283]
**Describe the bug**
After upgrading from v0.4.0 to v0.4.1a, all data is missing even though the log says `Database exists`.

**Steps To Reproduce**
In my case, using Portainer:
1. `Duplicate/Edit` existing container and changing image version to v.0.4.1a
2. Container restarts, but all recipes, users etc are missing
3. Reverting back to v0.4.0 using the same method as in 1. all data is back again.

**Expected behavior**
All data from database is still available.

**Actual Behavior**
All data from database is missing.

**Device Information (please complete the following information):**
 - Device: Synology DS920+
 - Deployment: latest Docker Package available for the device and Portainer 2.1.1

**Comment by hay-kot** [comment]
Can you provide the following? 

- Values Listed on `/admin/about` Page
- Docker Compose or ENV Variables
- Startup/Log File (If different from the one you've already sent over)

**Comment by waschinski** [comment]
Thanks for pointing me to the `/admin/about` page. It was showing the app running in `Development` mode despite the logs saying `Production`. The fix basically was to set `ENV=true` instead of simply removing it.
