### ISSUE TITLE
Request: Delete Confirmation

### ISSUE THREAD

**Issue by Dulanic** [hay-kot/mealie#29]
The option to delete a recipe can easily be hit in error being next to other icons and no text. I recommend a confirmation prompt to delete a recipe when editing.

**Comment by zackbcom** [comment]
I would also like to see this. I can submit a PR for this.

**Comment by hay-kot** [comment]
This feature in now included in the Dev Branch and will be pushed to latest in the next patch. Kudos to @zackbcom for the PR!
