### ISSUE TITLE
Creating custom pages is currently broken

### ISSUE THREAD

**Issue by ltctceplrm** [hay-kot/mealie#290]
**Describe the bug**
In the previous update custom pages used categories and those that I added before this update still work fine but now making new custom pages require tags but it you can't actually save the custom page (presumably because underneath they still require categories and not tags). If I try editing my existing (and functional) custom pages then it tries removing the category.

**Steps To Reproduce**
Please be specific!
1. Create custom page
2. Add an existing tag
3. Press create to save it

**Expected behavior**
Creating a custom page

**Actual Behavior**
Failing to create the custom page

**Device Information (please complete the following information):**
 - OS: Debian
 - Deployment: docker-compose
 - Browser: Firefox
 - Version: 0.4.1a

**Additional context**
Pointed out by @describe19 here https://github.com/hay-kot/mealie/discussions/229#discussioncomment-599427

**Comment by hay-kot** [comment]
Ah, that pretty frustrating sorry about that. I was able to get a fix into the dev branch. Looks like I missed a `:` when assigning a property to the Vue component. Dev branch should be in a pretty solid state, I need to do some more testing and they I'll push a release in a day or two.

**Comment by ltctceplrm** [comment]
Ah that's great thanks for the very rapid response. So the custom pages will no longer use categories then and only tags or will they at one point potentially use both/either?
If custom pages only use tags then it might be handy then to have an option to add the categories on the left side of the page again, otherwise you'd have to open a recipe and then click on it's category to go to that category page.

**Comment by hay-kot** [comment]
Pages will still use Categories. Basically there's a switch on the Vue component to determine if a tag or a recipe is created and I had the wrong one selected. 

 #291 Bring up the point that having all categories as a fall back if no pages exists may be a good option. I think that might be a good middle ground if someone wasn't interested in creating pages.

**Comment by ltctceplrm** [comment]
That'd be a good solution indeed, it would also be pretty cool if pages could use a combination of categories and tags but that might become complex, adding a tag filter on category pages would be simpler to use.
