### ISSUE TITLE
Categories are never displayed in the sidebar, even when no custom pages are set

### ISSUE THREAD

**Issue by sephrat** [hay-kot/mealie#291]
**Describe the bug**
Categories are never displayed in the navigation sidebar. They used to show before custom pages were implemented.
Since there are still relics from categories in the code, is it intended behaviour or an actual bug?

**Expected behavior**
I believed categories would be a fallback in case no custom pages are set, but I can't find where I read that info.

**Actual Behavior**
No categories show up in the sidebar when no custom pages are set.

**Screenshots**

![image](https://user-images.githubusercontent.com/34862846/114423904-eba96600-9bb7-11eb-9938-d0c217ee7b2c.png)
![image](https://user-images.githubusercontent.com/34862846/114423975-fb28af00-9bb7-11eb-93df-f6f8ceb4a30a.png)
![image](https://user-images.githubusercontent.com/34862846/114424196-2d3a1100-9bb8-11eb-8cb2-8961b747c5ae.png)

**Comment by hay-kot** [comment]
This wasn't something I was looking at, It's not a bad idea though. It should be fairly easy to implement, probably a computed property on the sidebar would do the trick.

**Comment by sephrat** [comment]
OK I'll take a look then.
