### ISSUE TITLE
Top-left button in recipe list always gives a 404

### ISSUE THREAD

**Issue by sephrat** [hay-kot/mealie#297]
**Describe the bug**
I'm not sure what the purpose of this button is.
![image](https://user-images.githubusercontent.com/34862846/114583371-d13bbf00-9c81-11eb-8995-91a29974701e.png)

https://github.com/hay-kot/mealie/blob/764f85fb40e15ce56eb78f01485a59f669783040/frontend/src/components/UI/CardSection.vue#L7-L11

I've tried all possible tabs from the left sidebar, the button never leads to an existing page. 
I'd just remove the link if it were me, but maybe there's something smarter to do with this, like designing a proper title section.

**Comment by hay-kot** [comment]
I removed the link until I can get around to a proper toolbar
