### ISSUE TITLE
Add from URL

### ISSUE THREAD

**Issue by tmitchell0909** [hay-kot/mealie#3]
I don't see a way to add a recipe form a URL on mobile, since the URL option only seems to appear on mouse over? Unless i;m missing something. Otherwise, looks awesome so far!

**Comment by hay-kot** [comment]
If you hold down your finger on the floating + icon the add from URL will appear and you can click, at least I could on android. 

This is not ideal, so I'll work on a fix. Thanks!

**Comment by tmitchell0909** [comment]
So it does, thanks for the quick reply. Like I said so far so good, I'll keep testing if out!

**Comment by richardmitic** [comment]
Holding the button doesn’t work on iOS Safari. It tries to highlight the entire page instead.

**Comment by hay-kot** [comment]
Button set to open on click in the dev branch. Will push to the main branch later this week.
