### ISSUE TITLE
Use a dedicated platform to manage localization

### ISSUE THREAD

**Issue by sephrat** [hay-kot/mealie#303]
To make translations easier, both for translators and developers, we could make use of a platform that handles translations.
Such a platform should :
- Be able to pull new strings and push new translations automatically from and to this repository
- Be adapted to open-source projects: free of charge and collaborative
- Be compatible with the way Vue-i18n handles translations (i.e. not leave an untranslated string as an empty string, but drop the key from the file or use the source string)

I've participated in the translations of some projects over the years and got my hands on several tools: Crowdin, Weblate, OneSkyApp, Transifex. 
As a translator and proofreader, my preference goes to Crowdin: I've found many useful features such as a neural machine translator or some nice moderation tools. Also, it's free of charge for open-source projects, under some conditions that I find acceptable (basically feed their neural network with our translations) : https://crowdin.com/page/open-source-project-setup-request
I managed to set it up on my fork before my trial expired, it worked flawlessly. 

If we go this way, the next steps are:
- [x] Request a licence for open source projects https://crowdin.com/page/open-source-project-setup-request
- [x] Normalize our locale files, they use different formats that Crowdin may not like (fr.json VS zh-CN.json)
- [x] Build a config file in the repo for Crowdin to read
- [x] Do the final setup on Crowdin platform (connect to Github and configure the project)

I can work on a PR for items 2 and 3, the others can only be done by the project lead.

**Comment by hay-kot** [comment]
I've submitted the initial request. I'll provide an update when/if the project is approved. Thanks for pushing me on this one!

**Comment by hay-kot** [comment]
Approved! You can find the project at https://crowdin.com/project/mealie

@sephrat, are you still up for working on a PR for 2 & 3? Looks like I've got everything connected we just a need a valid config and then we can sync.

**Comment by sephrat** [comment]
That was quick!

PR published: https://github.com/hay-kot/mealie/pull/319

**Comment by wengtad** [comment]
Just want to ask, how about the dropdown list on UI? need to add in manually (submit PR) if new lang add in?

**Comment by sephrat** [comment]
We shouldn't need to add new languages every day so it's fine if it's still a manual operation to do. :-)
I would say the new workflow for adding a new language is yet to be defined. It's a simple developer task now. My take on this is we should reference the language only if the translation coverage reaches a certain amount (say >80%), and then someone can submit a PR to add this language.

**Comment by wengtad** [comment]
> 
> 
> We shouldn't need to add new languages every day so it's fine if it's still a manual operation to do. :-)
> I would say the new workflow for adding a new language is yet to be defined. It's a simple developer task now. My take on this is we should reference the language only if the translation coverage reaches a certain amount (say >80%), and then someone can submit a PR to add this language.

Ok agree with this.

**Comment by sephrat** [comment]
It's now done! 🥳  https://crowdin.com/project/mealie
Thank you hay-kot for setting up Crowdin.
