### ISSUE TITLE
Ingredients check boxes don't seem to work

### ISSUE THREAD

**Issue by 2fst4u** [hay-kot/mealie#304]
**Describe the bug**
After importing a recipe from a website, the checkboxes for the ingredients list don't work. Tapping them on mobile causes them to highlight (the confirmation that the tap was received) but the box never ticks.

**Steps To Reproduce**
1. Install on kubernetes k3s using docker container.
2. Import recipe from website
3. Open recipe after saving and attempt to tap chdckboxes

**Expected behavior**
Checkboxes should become tick marks and should be unticked if tapped again.

**Actual Behavior**
The checkbox just highlights with a greyed circle surrounding the box and the line the text is on highlights grey and just stays like that. Tapping away causes the highlight to go away.

**Screenshots**
![Screenshot_20210414-191630.jpg](https://user-images.githubusercontent.com/15257926/114669403-f0a41c00-9d55-11eb-8ee0-8d363aa7e2bc.jpg)

**Device Information (please complete the following information):**
 - OS: kubernetes k3s cluster on Ubuntu arm64
 - Deployment: docker container version using latest tag
 - Browser: Chrome on Android 
 - Version: v0.4.1a

**Comment by 2fst4u** [comment]
To provide context to the screenshot, that's what it looks like after tapping and letting go. It kind of looks like it's just stuck in the state of confirming the tap and never progresses.

**Comment by sephrat** [comment]
I can reproduce: the checkbox is actually triggered twice when you click on it: once because it is a checkbox, and another time because clicking on the line ticks the checkbox too. So in the end nothing happens.
I'll see what I can do.
FYI, if you click on the text instead of the checkbox, it works fine.

**Comment by ovizii** [comment]
btw. if you click on the text next to the checkbox, the checkbox gets ticked instead :-)
![image](https://user-images.githubusercontent.com/837902/114996564-3caea800-9e9f-11eb-86ca-e1976b507407.png)

**Comment by 2fst4u** [comment]
The latest fix does make the checkbox work but it's still doing a weird ghosting thing with the button.

Don't get me wrong, this is absolutely minor in the scheme of things but it's just a weird little quirk that would be good to polish.

I've attached another screenshot of how it looks after tapping a checkbox.

![Screenshot_20210418-115811.jpg](https://user-images.githubusercontent.com/15257926/115129814-9220bb80-a03d-11eb-96f6-6bd7ece5e901.jpg)

**Comment by sephrat** [comment]
I quite like this effect, it makes it obvious that you can click on the text as well to tick the checkbox.
