### ISSUE TITLE
Third party Password manager on iOS doesn’t auto fill password correctly. 

### ISSUE THREAD

**Issue by evulhotdog** [hay-kot/mealie#311]
**Describe the bug**
The template or predefined text doesn’t get removed until you put the cursor in it manually, and it the browser/password doesn’t get recognized until you do so. 

**Steps To Reproduce**
Please be specific!
1. Go to your instance of mealie
2. Go to log in
3. Use a password manager to auto fill the password field. 
4. The predefined text is not removed when it is filled in. 

**Expected behavior**
The password is entered and then you can hit enter / login. 

**Actual Behavior**
The password is put in the field, however you are required to put the cursor in the box manually for it to recognize the password. 

**Screenshots**
![59C7F479-5754-4136-A01F-CE543D612F2E](https://user-images.githubusercontent.com/365456/115162999-b1870b00-a074-11eb-91cf-9006a00e4e10.jpeg)
![81E3FB59-4281-4B9A-A395-AFB7B6F1C989](https://user-images.githubusercontent.com/365456/115163001-b1870b00-a074-11eb-9a88-368cfa21ad51.jpeg)

**Device Information (please complete the following information):**
 - OS: iOS 14.5 (18E5199a)
 - Deployment: docker 
 - Browser: Chrome
 - Version: 0.4.1

**Comment by hay-kot** [comment]
I'm unable to replicate the issue on Desktop or Android Mobile, with Bitwarden. I don't have any iOS devices, so I'm not sure how much I can help with this issue. Hopefully someone with an iOS device can jump in on this one.

**Comment by evulhotdog** [comment]
I believe it would be the same with any password manager but if it matters I’m also using Bitwarden.

**Comment by iPauloV** [comment]
Just to add an extra info on this : I'm using an iPhone with iOS 14.4.2, using Safari and Bitwarden, and everything is fine for me.
Could you test with Safari ? If you faces the same problem with Safari, it may comes with iOS 14.5...

**Comment by evulhotdog** [comment]
Safari works fine, Chrome exhibits the behavior above.

**Comment by jrabensc** [comment]
Got the same problem. The password manager is not shown when I load the login form.

Device: iPhone 8 Plus, iOS 14.6, native Safari.

**Comment by hay-kot** [comment]
> Got the same problem. The password manager is not shown when I load the login form.
> 
> Device: iPhone 8 Plus, iOS 14.6, native Safari.

Can you confirm that you experience the same issue when you use the  `/login` page instead of the dialog? Maybe it's an issue with the login dialog

**Comment by jrabensc** [comment]
No issue when using the /login page.

Just had an iOS update and the dialogue form is working again now. I'm thinking this issue might be related to my system and not to Mealie.

**Comment by hay-kot** [comment]
> I'm thinking this issue might be related to my system and not to Mealie.

That's my feeling as well. I don't believe this is a Mealie issue. The email and password fields are ID'd correctly in the DOM. I'm going to close this for now.
