### ISSUE TITLE
user email is treated case-sensitive

### ISSUE THREAD

**Issue by metalheim** [hay-kot/mealie#314]
**Describe the bug**

User emails are treated as case-sensitive. That causes fail to log in and is not complying with standards.

**Steps To Reproduce**

1. Create user with any email, lets say testperson@example.com
2. Logout
3. Try logging in with testperson@**E**xample.com
4. Login fails -> "Could Not Validate Credentials"

**Expected behavior**
I expected email to be treated as a case-insensitive field.
RFC 2821 (Section 2.4) defines that 
> Mailbox domains are not case sensitive.

So above Steps should not cause a login error.

While the local part (in the above example: testperson) as per RFC must be case-sensitive, it is also common practice to treat it as case-insensitive. So much so, that many users come to expect whole email strings (local@domain) to be treated case-insensitive.

http://www.faqs.org/rfcs/rfc2821.html

**Screenshots**
![image](https://user-images.githubusercontent.com/44159957/115277280-5f151f80-a144-11eb-80af-4221710ccd08.png)

This actually took me a good hour to figure out, including resetting the docker container completely (damn you chrome and auto-filling in different email addresses)

**Comment by hay-kot** [comment]
An obvious oversight on my part. I'll catch it in the next round of patches. Thanks for reporting the issue!

**Comment by metalheim** [comment]
Great, please keep up the good work 😀
