### ISSUE TITLE
Feature: Crosslink ingredients to Recipe's

### ISSUE THREAD

**Issue by afterthought325** [hay-kot/mealie#32]
e.g. have an ingredient be a link to another recipe within mealie (or maybe any link?).

An example of this would be a Jam filled Pastry. You'd make a recipe for the jam, the pastry dough, and then link those in the ingredient list of the Pastry ingredient. This is really useful for ingredients that are used across many recipes. Instead of copying that portion of the recipe to each thing that contains it. you can have a single recipe for it and just link to the rest.

I'm not sure the best way for this to be done, but I imagine a URL field below the ingredient name field would suffice as a start.

**Comment by hay-kot** [comment]
Recipe Ingredients now support markdown syntax as of v0.4.1 so you can now reference recipes in the ingredient field by url. 

```
[My Recipe as an Ingredient](https://linktomyrecipes.com)
```

Renders as...
[My Recipe as an Ingredient](https://linktomyrecipes.com)
