### ISSUE TITLE
When going from Profile, to Manage Users, and back to Profile, avatars don't appear

### ISSUE THREAD

**Issue by evulhotdog** [hay-kot/mealie#329]
**Describe the bug**
Title

**Steps To Reproduce**
Please be specific!
1. Log in 
2. Go to Profile page
3. Click Manage Users
4. Click Profile
5. The avatar consistently doesn't appear as it should, even if you refresh. You have to go to the root of the site to be able to see it again.

**Expected behavior**
Profile picture should appear.

**Actual Behavior**
My initials appear instead.

**Device Information (please complete the following information):**
 - OS: MacOS
 - Deployment: docker
 - Browser: Chrome
 - Version: 0.4.3

**Comment by sephrat** [comment]
Works fine for me in dev branch (which is basically 0.4.3), both on Firefox and Chrome for Windows.
However I see one weird thing. It's fetching two images: one for user 0, and another for user 1.
![image](https://user-images.githubusercontent.com/34862846/115519185-3fd3da80-a289-11eb-9a89-7c3335de9f52.png)
![image](https://user-images.githubusercontent.com/34862846/115519210-46fae880-a289-11eb-9451-fa5ba8d57a04.png)
Probably is that in your browser, user 0 wins the race and a non existent image is displayed.

**Comment by wengtad** [comment]
I'm able to reproduce in demo site.

1. Log in
2. Go to Profile page
3. Click Manage Users
4. Reload the page (Reload icon or F5)
5. The profile pic is gone.
6. Click Profile also same result.
7. Until you click on Home Page then reload the page, the image is appear back.

**Comment by hay-kot** [comment]
Okay. I think I actually fixed this... 🤞 

I wasn't able to replicate the error @wengtad described. Can one of you guys verify that I'm not going crazy and this is working on the demo site? 

https://mealie-demo.hay-kot.dev/

**Comment by wengtad** [comment]
@hay-kot Yes, I think you fixed it. Current demo version is working.
