### ISSUE TITLE
Language settings are saved for one browser

### ISSUE THREAD

**Issue by iPauloV** [hay-kot/mealie#332]
**Describe the bug**
When a language other than English is selected and settings are saved, site is still in English **when using another PC/browser with clean cache.**

**Steps To Reproduce**
Please be specific!
1. Login as admin
2. Go to the site settings
3. Click on the language icon
4. Select another language (anything except English)
5. Click on "Save"
6. Go to the website with another browser with clean cache

**Expected behavior**
Site is in the selected language with every browser.

**Actual Behavior**
Site is in English with other browser except the one used to apply settings.

**Device Information (please complete the following information):**
 - OS: Windows 10
 - Deployment: Docker on Synology
 - Browser: Chrome and Firefox
 - Version: 0.4.3

**Additional context**
Before opening this issue, I asked about this in the discussion #331

**Comment by hay-kot** [comment]
Sorry about this, I should have caught the problem. I think I've found the underlying issue though. During a rewrite of the settings, we missed a few sections on the frontend where the language was cached, some parts of the website were pulling from one 'store' some were pulling from another.

**Comment by sephrat** [comment]
Yes we never retrieve from the API but always from the store. So far I've tried a quick and simple fix but the API call comes too late after some frontend initialization (some items in the menu and Vuetify components). I'm still investigating.
As a fallback solution, maybe we could set an env var for it and be done with it.

**Comment by hay-kot** [comment]
> Yes we never retrieve from the API but always from the store. So far I've tried a quick and simple fix but the API call comes too late after some frontend initialization (some items in the menu and Vuetify components). I'm still investigating.
> As a fallback solution, maybe we could set an env var for it and be done with it.

I think I was able to get it sorted out in [this commit ](https://github.com/hay-kot/mealie/issues/332#issuecomment-824283735). I think it's as simple as caching the siteSettings, pulling the language from the siteSettings cache and cleaning up all the old references/assignment. I still need to do another pass and make sure I caught all the references.

**Comment by sephrat** [comment]
I like your solution better than mine, but it's still not enough for some texts:
![image](https://user-images.githubusercontent.com/34862846/115611391-4e061300-a2ea-11eb-80f8-97e81238701f.png)
Same goes for the top-right menu and the admin menu.
'Standard' texts get translated on the fly but some stuff like these were coded differently and are not updated when the locale changes after the initialization.

**Comment by iPauloV** [comment]
I think I just discovered than the same problem occurs when selecting a different color for the default theme : default colors are still displayed until I go to the Theme settings and reapply the default theme.
Do you want me to open a new issue for that problem ?
