### ISSUE TITLE
add to unraid app store

### ISSUE THREAD

**Issue by smartkid808** [hay-kot/mealie#37]
would be cool if you could have this published in the unraid app store, id buy you a couple coffees.  :-)

**Comment by KakersUK** [comment]
I've created an unraid repository with a template for mealie and got added to the community apps. This will pull down and install the latest docker image.

With this you should be added to run Mealie on unraid.

**Comment by smartkid808** [comment]
nice, thanks.. :-)
What's the default login.  Don't see it listed (unless I missed it)

**Comment by KakersUK** [comment]
> Username: changeme@email.com
> Password: MyPassword

I'll add those in as variables to the template, as otherwise people will need to go to the docs and it's a little less out of the box.

**Comment by wengtad** [comment]
Just to confirm, is Mealie added to unraid app store? If yes I think this could close?

**Comment by KakersUK** [comment]
Yes, this was added to the unraid community apps. So the issue can probably be closed now.

**Comment by hay-kot** [comment]
Thanks for everyone’s work on this 🚀

**Comment by WorldTeacher** [comment]
@KakersUK 
Sorry to post here, but the container on UnRaid is still using an older version. Would you be able to update it to the new version?

**Comment by KakersUK** [comment]
> @KakersUK Sorry to post here, but the container on UnRaid is still using an older version. Would you be able to update it to the new version?

Hey @WorldTeacher for Unraid it's just a XML template which pulls the docker image, I have no control over the versioning that is solely managed by the developer.

The template uses 'hkotel/mealie' for the repository which will be the latest branch (recommended), that was last updated 8 months ago. You're getting notifications of the latest beta software.

You could get to the latest version by going into the app configuration and setting the repository to "hkotel/mealie:frontend-v1.0.0beta-4" although I wouldn't recommend it as you might get breaking changes. But if you still want to then I'd suggest backing up and downloading your data via the dashboard. If it were me I'd just wait for the official latest release from hay-kot.

Would recommend reading this page also: https://nightly.mealie.io/documentation/getting-started/migrating-to-mealie-v1/

Hope this helps.
