### ISSUE TITLE
Perhaps no bug, User management question

### ISSUE THREAD

**Issue by mourningsun75** [hay-kot/mealie#375]
What I mean by user management is that when I create a recipe, I am the only one who can see it. I don't want my recipes to be visible without a login.

Did I misunderstand something?

That is the last reason that still keeps me from using it.

**Steps To Reproduce**
1. LogIn
2. Create Recipe
3. Logout
4. Recipe is still visible

**Comment by sephrat** [comment]
It's the expected behaviour. At the moment all recipes stored in Mealie are public. Logging in allows you to create or modify recipes, amongst other things.
A feature request was already made for the behaviour you expect: https://github.com/hay-kot/mealie/discussions/318#discussioncomment-633306

**Comment by mourningsun75** [comment]
Ok, thanx

**Comment by hay-kot** [comment]
FYI, this should be available in the next release.
