### ISSUE TITLE
Import from Open Eats .csv export 

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#4]
Example Export: [recipe_recipe.zip](https://github.com/hay-kot/mealie/files/5760945/recipe_recipe.zip)

**Comment by chansters** [comment]
> Example Export: [recipe_recipe.zip](https://github.com/hay-kot/mealie/files/5760945/recipe_recipe.zip)

Thank you!

**Comment by emblazened** [comment]
I'd like to add that as an alternative to dumping an OpenEats DB and importing it into Mealie, OpenEats does also expose its own API: https://github.com/open-eats/openeats-api. On the assumption that anyone wanting to go this migration route would start with a working OpenEats instance, it might be "nicer" to be able to simply point Mealie at the OpenEats server and let it pull whatever it needs using that API.

I guess there's a small discussion to be had as to whether this is a better or worse approach. Personally, I don't like that the only way (AFAIK?) to back up/restore OpenEats data is to `exec` onto one of its containers and talk to the database manually. Anything that avoids me having to do that is better in my opinion.

I'm not familiar with FastAPI and its project structure, but at a guess this could piggyback on the backup_services.py in the simplest case, or better, be implemented in an import_services.py?

**Comment by hay-kot** [comment]
> I'd like to add that as an alternative to dumping an OpenEats DB and importing it into Mealie, OpenEats does also expose its own API: https://github.com/open-eats/openeats-api. On the assumption that anyone wanting to go this migration route would start with a working OpenEats instance, it might be "nicer" to be able to simply point Mealie at the OpenEats server and let it pull whatever it needs using that API.
> 
> I guess there's a small discussion to be had as to whether this is a better or worse approach. Personally, I don't like that the only way (AFAIK?) to back up/restore OpenEats data is to `exec` onto one of its containers and talk to the database manually. Anything that avoids me having to do that is better in my opinion.
> 
> I'm not familiar with FastAPI and its project structure, but at a guess this could piggyback on the backup_services.py in the simplest case, or better, be implemented in an import_services.py?

I agree that point directly at the API may be a better approach. I'm hesitant to spin up an example just to test that at this point . I'd love to have it, but it's lower in my list for now. I'm happy to support a PR and/or help out on the Discord to get this done.

I'm unclear on what your second point is... Fast API structure is similar to flask, as such there isn't really one. I think I've structured the project fairly well and easy to understand, atleast on the backend. Mealie already offers an export to plain text json as well as supports jinja2 templating for additional formats. [See the docs for more details on this. ](https://hay-kot.github.io/mealie/1.3%20-%20admin-panel/)

To be clear, I never want to "hide" data in a database. As with all things self hosted, this project may dry up and I don't believe in making it difficult for user to access their data and migrate to another service.

**Comment by emblazened** [comment]
Fair enough! I just wanted to put it out there for anyone that might come to implement this.

> I'm unclear on what your second point is... Fast API structure is similar to flask, as such there isn't really one. I think I've structured the project fairly well and easy to understand, atleast on the backend. Mealie already offers an export to plain text json as well as supports jinja2 templating for additional formats. See the docs for more details on this.

Sorry, I wasn't trying to comment on the existing work and structure. I just meant I haven't worked with FastAPI before, and was projecting where I thought an implementation might start based on a quick look through what is there!

**Comment by hay-kot** [comment]
> Fair enough! I just wanted to put it out there for anyone that might come to implement this.
> 
> > I'm unclear on what your second point is... Fast API structure is similar to flask, as such there isn't really one. I think I've structured the project fairly well and easy to understand, atleast on the backend. Mealie already offers an export to plain text json as well as supports jinja2 templating for additional formats. See the docs for more details on this.
> 
> Sorry, I wasn't trying to comment on the existing work and structure. I just meant I haven't worked with FastAPI before, and was projecting where I thought an implementation might start based on a quick look through what is there!

No need to apologize, I just wasn't sure what you meant. I've already created a Chowdown migration in mealie/services/migrations/chowdown.py. Any other migrations can be added as additional files there. Chowdown.py can be used as an example of how someone might accomplish this. Thanks for your interest in the project! 

Cheers!

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.

**Comment by jachin** [comment]
I realize this issue is closed, but if anyone else finds this issue, I wrote a script that exports OpenEats recipes into the Nextcloud Cookbook format (a zip file with a bunch of json and images inside it) that Mealie can then import.

https://gist.github.com/jachin/508fe1b7b2717faa1da5a84ae793b027
