### ISSUE TITLE
sample docker-compose under getting-started doesn't persist mongo db

### ISSUE THREAD

**Issue by mrherman** [hay-kot/mealie#41]
On the Mealie website under getting started it gives a docker-compose file.  It doesn't persist the directory /data/db in the mongo container.  It also doesn't allow the user to access the logs easilt in the mealier container.  Suggest changing it to show

Under Mongo -
volumes:
      - ./mongo_data:/data/db

Under Mealie - 
volumes:
      - ./mealie_data:/app/data

Or whatever host subdirectory you think is appropriate.

**Comment by hay-kot** [comment]
Good catch! Not sure how I haven't come across that error myself. I updated the documentation to reflect the changes you suggested.

**Comment by gajewsky** [comment]
hey @hay-kot could you link commit with those changes? I was not able to find it :(

**Comment by hay-kot** [comment]
> hey @hay-kot could you link commit with those changes? I was not able to find it :(

Updated documentation can be found here https://hay-kot.github.io/mealie/getting-started/install/

Let me know if that helps!
