### ISSUE TITLE
Website URL doesn't pull the needed information

### ISSUE THREAD

**Issue by rastacalavera** [hay-kot/mealie#412]
**Describe the bug**
When trying to get a recipe from the website [thrivemagazine](www.thrivemagazine.com) the ingredients and steps and either not imported at all or in the wrong location.

**Steps To Reproduce**
1. Go to www.thrivemagazine.com
2. Click on any recipe 
3. Try to add it to mealie

**Expected behavior**
Scraped data should import properly into mealie 
**Actual Behavior**
Data doesn't import at all or in the wrong location
**Screenshots**
![image](https://user-images.githubusercontent.com/6867792/118659374-df19be00-b7b2-11eb-916d-44e15a922d68.png) https://www.thrivemagazine.com/single-post/2018/02/20/raw-berry-chia-pudding
![image](https://user-images.githubusercontent.com/6867792/118659449-f062ca80-b7b2-11eb-8991-43e96573c9f4.png) https://www.thrivemagazine.com/single-post/2019/07/22/quinoa-sushi-with-miso-tahini-dressing

**Device Information (please complete the following information):**
 - Deployment: Docker on raspberry pi 4
 - Browser: firefox
 - Version: 0.4.3

**Comment by TheZoker** [comment]
If I'm not mistaken this is caused by the fact, that they don't use any structured data for their recipes 🤔

**Comment by rastacalavera** [comment]
Yeah I realized this from a conversation in the discord. Is there a way to set up rules for a site to scrape based on keywords?

**Comment by hay-kot** [comment]
> Yeah I realized this from a conversation in the discord. Is there a way to set up rules for a site to scrape based on keywords?

There is not. Currently the way I go about this is to scrape the URL which will usually yield a name/description and then use the "Bulk Add" option to paste in the ingredients. 

I don't think that adding a site specific keyword search would be the best approach in mealie. I think a browser extension with some sort of parsing ability that can plugin to the Mealie API may be a better bet than trying to roll that functionality into the server its self.
