### ISSUE TITLE
Export Shopping list?

### ISSUE THREAD

**Issue by graner1** [hay-kot/mealie#418]
Ability to email or text shopping lists?

**Comment by hay-kot** [comment]
I don't know what this is. Are you requesting a feature? Asking if this is possible currently? 

There is no functionality for this. The meal-planner/shopping-list are going through a rewrite currently and I am looking into something like this. If you have additional feature requests please use the github discussion pages. It's likely someone has already requested what you requested.

**Comment by graner1** [comment]
Asking if it was possible currently. Sounds like it isn't! Sorry for the confusion. I am a big fan of Mealie!

**Comment by hay-kot** [comment]
Working on a new feature now for better shopping lists. At the start you'll be able to at least copy the text, but I'm hoping to get some sort of notification process. I'm not sure the best way to format the text though. 

<img width="1110" alt="Screen Shot 2021-05-22 at 7 27 45 PM" src="https://user-images.githubusercontent.com/64056131/119246135-7bcdba00-bb2b-11eb-9951-9ac7b9e295fa.png">

**Comment by vomov** [comment]
Looking for the same feature; shopping with the current shopping list is overly complicated. I would like the option to generate a shopping list with custom items (that don't appear in recipes, like coffee), and a way to sort it based on category or part of the meal ('veggies', 'meat', 'other'). 

I'm curious as to what you mean with 'notification process'.

**Comment by hay-kot** [comment]
The feature is live on the demo site. You can add ingredients directly from recipes or create from a MealPlan. You can also add custom items. You can also copy the list as raw text. Sorting a filter won't come along until I rewrite the recipe ingredients 

As for notifications. I'd like to have sole way to send a list, something like email, sms, or webhook into Google keep or something.
