### ISSUE TITLE
Meal Plans not shown on iOS devices

### ISSUE THREAD

**Issue by jrabensc** [hay-kot/mealie#428]
**Describe the bug**
The meal plans at https://mealie-demo.hay-kot.dev/meal-plan/planner are not shown on iOS devices (iPhone, iPad).

Happens on both demo and private instance.

**Steps To Reproduce**
Please be specific!
1. https://mealie-demo.hay-kot.dev/meal-plan/planner
2. Create plan
3. List of plans is not shown on iOS devices

**Screenshots**
![image](https://user-images.githubusercontent.com/6616405/119464641-3b488900-bd43-11eb-8784-d4ef3691d163.png)

**Device Information (please complete the following information):**
 - OS: iOS 14.6
 - Deployment: docker-compose
 - Browser: Safari
 - Version: 0.4.3 (private instance)

**Comment by hay-kot** [comment]
This is a Safari specific bug. I believe it has to do with how they handle javascript Dates. 

I think this article gives a little context on what is causing the issue. https://techtalkbook.com/javascripts-new-date-does-not-work-on-ie-and-safari/

**Comment by italy333333** [comment]
I have the same issue and have tested it with Chrome, Firefox, Edge, and Safari on iOS 14.6.

**Comment by hay-kot** [comment]
> I have the same issue and have tested it with Chrome, Firefox, Edge, and Safari on iOS 14.6.

I didn't realize that all web browsers on iOS use the same javascript engine and therefore suffer the same fate. I bought an iPad today and discovered the same.

**Comment by hay-kot** [comment]
I think I got it working.

If you can, please give it a try on the [demo site](https://mealie-demo.hay-kot.dev/meal-plan/planner) and let me know if it's working and I'll mark the issue as resolved pending release.

Thanks!

**Comment by italy333333** [comment]
Works fantastically, really appreciate the work on this, it is great!!

**Comment by jrabensc** [comment]
Working here. Thanks for the quick fix. When will this be available in the latest docker?

**Comment by zierbeek** [comment]
Confirming it works! 
@jrabensc upon release of 0.5.0. Will take some more time.
