### ISSUE TITLE
Not able to run correctly in docker if user permissions are specified

### ISSUE THREAD

**Issue by RichardMore** [hay-kot/mealie#429]
**Describe the bug**
When I try to run the container as a specific user due to folder permissions there are errors and login issues caused by the user the container runs as cannot access folders/files
Tried all run as user options, the preferred one would be like the linuxserver.io docker images PUID and PGID

**Steps To Reproduce**
Please be specific!
1. Run docker image as user specified
2. See logs and try to log in as well - it will fail

**Docker compose section**
  mealie:
    image: hkotel/mealie:latest
    user: 1000:1000
    ports:
      - 80:80
    environment:
      db_type: sqlite
      TZ: America/New_York
      UID: 1000
      PUID: 1000
      GUID: 1000
      PGID: 1000

**Expected behavior**
Create files and processes as the specified user

**Actual Behavior**
Errors

**Docker-compose logs**
Attaching to mealietest
mealietest   | /app/mealie/run.sh: line 10: poetry: Permission denied
mealietest   | /app/mealie/run.sh: line 11: poetry: Permission denied
mealietest   | Production
mealietest   | {"level":"info","ts":1621958901.1885612,"msg":"using provided configuration","config_file":"./Caddyfile","config_adapter":""}
mealietest   | {"level":"warn","ts":1621958901.1905532,"logger":"admin","msg":"admin endpoint disabled"}
mealietest   | {"level":"info","ts":1621958901.1908958,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000380a80"}
mealietest   | {"level":"error","ts":1621958901.1919827,"msg":"unable to create folder for config autosave","dir":"/.config/caddy","error":"mkdir /.config: permission denied"}
mealietest   | {"level":"info","ts":1621958901.1920056,"msg":"serving initial configuration"}
mealietest   | {"level":"info","ts":1621958901.1921408,"logger":"tls","msg":"cleaned up storage units"}
mealietest   | Successfully started Caddy (pid=15) - Caddy is running in the background
mealietest   | INFO:    Adding job tentatively -- it will be properly scheduled when the scheduler starts
mealietest   | INFO:    ----INIT SCHEDULE OBJECT-----
mealietest   | INFO:    Adding job tentatively -- it will be properly scheduled when the scheduler starts
mealietest   | Pending jobs:
mealietest   |     update_webhook_schedule (trigger: interval[0:30:00], pending)
mealietest   |     backups (trigger: cron[hour='0', minute='0'], pending)
mealietest   | INFO:    None
mealietest   | INFO:    -----SYSTEM STARTUP-----
mealietest   |
mealietest   | INFO:    ------APP SETTINGS------
mealietest   | INFO:    Added job "update_webhook_schedule" to job store "default"
mealietest   | INFO:    Added job "backups" to job store "default"
mealietest   | INFO:    Scheduler started
mealietest   | INFO:     Started server process [24]
mealietest   | INFO:    Started server process [24]
mealietest   | INFO:     Waiting for application startup.
mealietest   | INFO:    Waiting for application startup.
mealietest   | INFO:    {
mealietest   |     "PRODUCTION": true,
mealietest   |     "IS_DEMO": false,
mealietest   |     "API_PORT": 9000,
mealietest   |     "API_DOCS": true,
mealietest   |     "DATABASE_TYPE": "sqlite",
mealietest   |     "SQLITE_FILE": "/app/data/db/mealie_v0.4.0.sqlite",
mealietest   |     "DEFAULT_GROUP": "Home",
mealietest   |     "DEFAULT_EMAIL": "changeme@email.com",
mealietest   |     "TOKEN_TIME": 2
mealietest   | }
mealietest   | INFO:     Application startup complete.
mealietest   | INFO:    Application startup complete.
mealietest   | INFO:     Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)
mealietest   | INFO:    Uvicorn running on http://0.0.0.0:9000 (Press CTRL+C to quit)

**Device Information (please complete the following information):**
 - OS: CentOS 8
 - Deployment: docker-compose

**Comment by hay-kot** [comment]
This has been brought up before

[See #350](https://github.com/hay-kot/mealie/issues/350) and [This Comment](https://github.com/hay-kot/mealie/discussions/318#discussioncomment-711790)

The short of it is that I haven't been able to figure it out in the time I've spent looking at it. It seems to me to be a fairly complicated implementation process to have it work without other side effects. I don't have the time required to adequately look into implementing this. 

If someone in the community or from the linuxserver.io team wants to help out with this, or any other deployment improvements I'm absolutely open to supporting that work.
