### ISSUE TITLE
Images saved with no way to delete when add recipe via URL fails

### ISSUE THREAD

**Issue by mrherman** [hay-kot/mealie#43]
When adding a recipe via URL and it fails the image still gets saved to /data/img, with no way to delete or clean up the directory without manually deleting the file.

Expected behavior: If the import via URL fails then the image should never be saved (or deleted if previously saved).

It's probably worth checking if other things get saved/changed before an import fails and not cleaned up, database entries perhaps?  I didn't check.

**Comment by hay-kot** [comment]
Can you provide the URL you were using so I can replicate the error? Thanks!

**Comment by mrherman** [comment]
https://www.kitschencat.com/pressure-cooker-chicken-tortilla-soup/

Looking at the log, it looked like the JSON was properly parsed, but failed later?  I am not sure.  I am also using the current docker container (image: hkotel/mealie:latest) via docker-compose.

**Comment by hay-kot** [comment]
To follow up on this, I wasn't able to get any images from the website with mealie. The JSON parser did fail because the image property was null. This has been addressed in the update. Can you upgrade and advise if there is still an issue? 

[new release](https://github.com/hay-kot/mealie/releases/tag/v0.0.2)

**Comment by mrherman** [comment]
I wasn't able to reproduce the issue either (images being saved in /img when recipe isn't).  I am confused about that, but maybe I was wrong.  I did upgrade to v0.0.2 and now the recipe saves (without pulling an image).

**Comment by mrherman** [comment]
If I try to add an image to one of these after adding (without an image being imported) it saves the image to /img but it doesn't display the image on the site.

**Comment by hay-kot** [comment]
This has been addressed in v0.1.0
