### ISSUE TITLE
hotmail.co.uk & custom domain email not allowed

### ISSUE THREAD

**Issue by Reddax** [hay-kot/mealie#435]
**Describe the bug**
Entering an email address that ends in hotmail.co.uk (which is valid) returns e-mail must be valid and won't let me save it.
I also cannot add my custom domain email - test@mydomain.co.uk. It needs to just check for the @ symbol and not force certail email domains.

**Steps To Reproduce**
Please be specific!
1. Create a new user
2. Enter test@hotmail.co.uk or test@mydomain.co.uk into email box
3. See that it cannot be saved

**Expected behavior**
An email address ending in @hotmail.co.uk, or anything else after @ to allow custom domains, is a valid address and should be accepted.

**Actual Behavior**
An email address ending in @hotmail.co.uk, or anything else after @ to allow custom domains,  is not allowed and won't let you save it.

**Screenshots**
![image](https://user-images.githubusercontent.com/1349626/119629162-a8bcee00-be05-11eb-9c0b-64c5c62c2cf6.png)

**Device Information (please complete the following information):**
 - OS: W10
 - Deployment: Docker version, Unraid community apps.
 - Browser: Chrome
 - Version: 0.4.3

**Comment by hay-kot** [comment]
This has come up before and I adjusted the validation. I think I need to just strip out the email validation all together. At the moment it doesn't really server any purpose anyways.

**Comment by KakersUK** [comment]
It looks like the only major problem with the current validation is it doesn't deal with 2 layer tlds. 
Just a recommendation before you strip it out completely, you could try this instead:

`/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/`

This was taken from here: https://emailregex.com/

I've tried a few different combinations in regex101 and seems like it might fit the bill. However, I've not been able to get a dev environment up to test it yet mind you.

**Comment by hay-kot** [comment]
> This was taken from here: https://emailregex.com/

and booked marked! Looks like that regex does the trick 👍

**Comment by AllySummers** [comment]
Just getting started with mealie and looks promising but would like to offer my 2 cents here:
Not sure there should be too strict validation on an email, because the regex for validating an email is incredibly complicated. As an example, even if you modify the regex to allow 2 level TLDs, what about people who use email on a subdomain? 
i.e. me@mycompany.billing.co.uk
