### ISSUE TITLE
Installation issues on OMV4 via Docker

### ISSUE THREAD

**Issue by slodown** [hay-kot/mealie#446]
How to fix OCI runtime create failed in Docker?

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; docker run -d --restart=always -v /etc/localtime:/etc/localtime:ro --net=bridge -p 0.0.0.0:9925:80/tcp -e PATH="/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" -e LANG="C.UTF-8" -e GPG_KEY="E3FF2839C048B25C084DEBE9B26995E310250568" -e PYTHON_VERSION="3.9.4" -e PYTHON_PIP_VERSION="21.0.1" -e PYTHON_GET_PIP_URL="https://github.com/pypa/get-pip/raw/29f37dbe6b3842ccd52d61816a3044173962ebeb/public/get-pip.py" -e PYTHON_GET_PIP_SHA256="e03eb8a33d3b441ff484c56a436ff10680479d4bd14e59268e67977ed40904de" -e PRODUCTION="true" -e DB_TYPE="sqlite" -e TZ="Europe/Berlin" -v "/sharedfolders/appdata/mealie":"/app/data/":rw --name="mealie" "hkotel/mealie:latest" 2>&1' with exit code '127': bb584b7d58cdd21454c2dd58583d6c7e669830adf6ae474e89abec6879ebfa2d docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown.

Thank you!

**Comment by hay-kot** [comment]
I'm not sure I can help much with this one as it seems to be docker related. What operating system are you trying to deploy on?

**Comment by slodown** [comment]
Hi,
the underlying system is:

Distributor ID: Debian                                                                                                                                                  
Description:    Debian GNU/Linux 9.13 (stretch)                                                                                                                         
Release:        9.13                                                                                                                                                    
Codename:       stretch                                                                                                                                                 

And here is the docker version:

Client: Docker Engine - Community                                                                                                                                       
 Version:           19.03.15                                                                                                                                            
 API version:       1.40                                                                                                                                                
 Go version:        go1.13.15                                                                                                                                           
 Git commit:        99e3ed8                                                                                                                                             
 Built:             Sat Jan 30 03:18:23 2021                                                                                                                            
 OS/Arch:           linux/arm64                                                                                                                                         
 Experimental:      false                                                                                                                                               
                                                                                                                                                                        
Server: Docker Engine - Community                                                                                                                                       
 Engine:                                                                                                                                                                
  Version:          19.03.15                                                                                                                                            
  API version:      1.40 (minimum version 1.12)                                                                                                                         
  Go version:       go1.13.15                                                                                                                                           
  Git commit:       99e3ed8                                                                                                                                             
  Built:            Sat Jan 30 03:16:53 2021                                                                                                                            
  OS/Arch:          linux/arm64                                                                                                                                         
  Experimental:     false                                                                                                                                               
 containerd:                                                                                                                                                            
  Version:          1.4.3                                                                                                                                               
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b                                                                                                            
 runc:                                                                                                                                                                  
  Version:          1.0.0-rc92                                                                                                                                          
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff                                                                                                            
 docker-init:                                                                                                                                                           
  Version:          0.18.0                                                                                                                                              
  GitCommit:        fec3683                                   

Thank you!

**Comment by slodown** [comment]
Ticket can be closed.

I pulled the dev tag and now it is running fine.

Nice manager.
