### ISSUE TITLE
API call results in 'Not authenticated'

### ISSUE THREAD

**Issue by hav0ck** [hay-kot/mealie#457]
**Describe the bug**
Trying out the Meal Plan API on a fresh install of Mealie.
On https://<Install.location.tld>/docs#/
Trying to use Get All Meals, Get This Week, and Get Today on the site results in the following:

Error:
Response body
{
   "detail": "Not authenticated"
 } 

Response headers 
alt-svc: h3-27=":443"; ma=86400,h3-28=":443"; ma=86400,h3-29=":443"; ma=86400,h3=":443"; ma=86400  
cf-cache-status: DYNAMIC  
cf-ray: 658ad0ffbe8decee-YUL  
cf-request-id: 0a6aa0f3d20000ecee229e9000000001  
content-length: 30  
content-type: application/json  
date: Tue,01 Jun 2021 19:23:26 GMT  
expect-ct: max-age=604800,report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"  
nel: {"report_to":"cf-nel","max_age":604800}  report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=IGIg4T1nOT2NepnQkWzrEFm%2BjzLbTWQQbTd94n6%2FJp8nbi6%2FcrJ8FK7%2BD1WLEdySHYVsaXjEUefILHj1ufrc26h1MuBPag1gK9oRutxDCz6HiFW%2BYqnssEBYmKhDkKgNKfdZ"}],"group":"cf-nel","max_age":604800}  
server: cloudflare  
strict-transport-security: max-age=31536000; preload  
www-authenticate: Bearer

**Steps To Reproduce**
Please be specific!
1. Go to 'https://<Install.location.tld>/docs#/'
2. Under Meal Plan click on Click on 'Get  /api/meal-plans/today'
3. Click on 'Try it out'
4. Click on 'Execute'

Get Todays Image works just fine.

**Device Information (please complete the following information):**
 - OS: Mealie Docker
 - Deployment: Docker
 - Browser: chrome
 - Version: 0.4.3

**Comment by hay-kot** [comment]
You have to authenticate you use the restricted routes. Restricted routes are noted with the lock icon. You can click the authorize button to be prompted to login.

![Capture](https://user-images.githubusercontent.com/64056131/120383543-7877c280-c2d1-11eb-9310-874797439aef.PNG)

**Comment by hav0ck** [comment]
> You have to authenticate you use the restricted routes. Restricted routes are noted with the lock icon. You can click the authorize button to be prompted to login.

Thank You!
