### ISSUE TITLE
[Beta] Stars from previous recipes will cosmetically carry over to a new recipe

### ISSUE THREAD

**Issue by BrandonG777** [hay-kot/mealie#463]
Whenever I have a recipe pulled up, fullscreen, that I rate, then I search for another recipe and open it fullscreen, the stars from the previous recipe will carry over, cosmetically. If I hit edit, it will display the correct number of stars. 

**Steps To Reproduce**
Please be specific!
1. Open a recipe, full browser window
2. Edit, give it a number of stars, save.
3. Search for another recipe, open it, the stars from the previous recipe will carry over.

 - OS: Win10
 - Deployment: unRAID Docker 20.10.5
 - Browser: Edge
 - Version: 0.5.0-dev

**Additional context**

**Comment by wengtad** [comment]
I just try it out, without fullscreen also have this issue.
Btw you may add a prefix [beta] on your title.

**Comment by BrandonG777** [comment]
fullscreen wasn't the right term. I just meant when you open a recipe up.
