### ISSUE TITLE
Can't import via URL from seriouseats.com

### ISSUE THREAD

**Issue by eric72777** [hay-kot/mealie#469]
**Describe the bug**
I tried to import this recipe:
https://www.seriouseats.com/taiwanese-three-cup-chicken-san-bei-gi-recipe
I get the error "Looks like there was an error parsing the URL. Check the log and debug/last_recipe.json to see what went wrong.”

I tested it in v0.50-BETA Online-Demo and mealie v0.4.3 deployed via docker-compose.

The last_recipe.json-file looks fine, but is not related to the failed recipe.

**Comment by wengtad** [comment]
You may try on latest v0.50-BETA, it can import now.
Tried import using demo site https://mealie-demo.hay-kot.dev/recipe/taiwanese-three-cup-chicken-san-bei-ji-recipe

**Comment by eric72777** [comment]
Yes, the updated parser on latest v0.50-beta worked. Thank you!
