### ISSUE TITLE
No confirmation on delete

### ISSUE THREAD

**Issue by kirkybaby** [hay-kot/mealie#47]
Just accidentally learned the hard way that there's no confirmation dialog that pops up when you click delete. Having delete immediately beside edit, it would be helpful for those of us with fat fingers to confirm before a recipe disappears lol

**Comment by hay-kot** [comment]
This has been added in the dev branch and will be pushed out later this week. 👍

**Comment by hay-kot** [comment]
New version is live [here](https://github.com/hay-kot/mealie/releases/tag/v0.0.2)
