### ISSUE TITLE
Image Uploader modal does not close after uploading image

### ISSUE THREAD

**Issue by abhchand** [hay-kot/mealie#477]
**Describe the bug**

The image uploader modal allows users to upload an image (or fetch an image from the web). After uploading, the modal remains open. There's no obvious way to close it, although clicking anywhere outside the modal does close it. 

Overall, this is more of a UX/usability minor issue. The behavior I see on most sites is that the upload action is "done" after uploading, so the modal feels like it should close.

**Steps To Reproduce**

1. Edit a recipe
2. Upload an image
3. After image is uploaded, note that the modal doesn't close.

**Sample Code**

Probably could be updated in [`ImageUploadBtn.vue`](https://github.com/hay-kot/mealie/blob/master/frontend/src/components/Recipe/RecipeEditor/ImageUploadBtn.vue)

**Expected behavior**

Modal should close.

**Screenshots**

<img width="806" alt="Screen Shot 2021-06-09 at 8 38 37 PM" src="https://user-images.githubusercontent.com/13787645/121446967-aeb4e200-c962-11eb-83ba-c7fb8ca0b884.png">

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Deployment: `docker run` with `hkotel/mealie:latest`
 - Browser: Firefox 89.0

**Comment by abhchand** [comment]
I wasn't 100% sure if this was really a "bug" or more of a (minor) feature request.

If this is something everyone agrees on adding, I'm happy to try my hand at it. I'm more of ReactJS developer, but I can probably figure out the VueJS setup.

**Comment by hay-kot** [comment]
@abhchand, hard to say where UX decisions fall into issues bugs or whatever but I'm still working through how to create an intuitive UX so issues like this are always welcome! 

I think it's a good idea, you're absolutely welcome to take a stab at it. The make file is pretty good so if you run `make help`  or take a look at the file you should be able to get everything spun up from there. If you need any help hop on the [Discord](https://discord.gg/dZCKHEMK) and we can help get you sorted.
