### ISSUE TITLE
[Beta] Private Recipe

### ISSUE THREAD

**Issue by wengtad** [hay-kot/mealie#478]
**Describe the bug**
Set one of the recipe on demo site to private under Recipe Settings, after logout the private recipe still there.

**Steps To Reproduce**
Please be specific!
1. Login Mealie
2. Edit a recipe
2. Click on 'Settings (which is Recipe Settings)'
3. Toggle 'Public Recipe' to off
4. Click on 'Save'
5. Back to 'Home page'
6. Logout Mealie
7. Refresh 'Home page'

**Expected behavior**
Private recipe should hide/not allow to view if not login.

**Actual Behavior**
Recipe mark as private still able to view and shown on the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/12437747/121449322-2834ea80-c9cc-11eb-8754-abcc14cf744a.png)
Recipe is mark as private for 'One Pot Shredded Chicken in Buffalo Sauce'.
![image](https://user-images.githubusercontent.com/12437747/121449274-0d627600-c9cc-11eb-9508-381eafe61027.png)
Private recipe (One Pot Shredded Chicken in Buffalo Sauce) still showing after logout.

**Device Information (please complete the following information):**
 - OS: Win10
 - Deployment: [demo site](https://mealie-demo.hay-kot.dev/)
 - Browser: Brave
 - Version: 0.5.0-beta (demo)

**Comment by hay-kot** [comment]
I haven't actually programmed that functionality yet. I'm was stuck last time I looked at it, I'm open to input/help on this as well.

in `mealie/routes/recipe/all_recipe_routes.py` the `get_recipe_summary` takes in the parameters to display the recipes. What I'd like to do is determine if the user is logged in using the dependency injection like the other routes, but if the user isn't logged in, return false and then only return the private recipes if the user is logged in.

**Comment by wengtad** [comment]
Ah I don't know it is not done yet. 

> Edit: Okay, so that was the easy part. I was able to get that working, now I just need to get the sql alchemy to filter recipes. Working over at #479.

Great, thanks!

**Comment by hay-kot** [comment]
From #479 

>  - [x] Create user check dependency
> - [x] Restrict Private Recipes on get_all
> - [x] Restrict private recipes on single recipe page
> - [x] Restrict private recipes on get by category
> - [x] Restrict private recipes on get by tag

This is what I've got restricted or will filter out recipes if not logged in. I think that covers everything? Anything jump out at you that I've missed?

**Comment by wengtad** [comment]
Thanks all your hard work! I think more or less is good to me.

Just got a question for you.
let's say if the user already logout/ non-user who use Mealie, he/she browse the url directly, for example https://mealie-demo.hay-kot.dev/recipe/slow-cooker-beef-brisket-with-bbq-sauce , then he/she able to view it also if that recipe is private?

**Comment by zierbeek** [comment]
I think the sharing needs to be considered to for this one. What if I want to share a private recipe?

**Comment by hay-kot** [comment]
> I think the sharing needs to be considered to for this one. What if I want to share a private recipe?

Y'all never want me to have free time 😂. In its current state you can't access any private recipes unless you are a user.

I think this would take a couple of things. A database to track recipe share tokens. A route/page on the frontend that is dedicated to shared recipes. Something like `recipe/shared/{token}`. And a background task to purge tokens on some interval.

I don't think I'll get at it in the current PR so if anyone wants to jump on it, feel free.

**Comment by zierbeek** [comment]
I think this is not in my knowledge set haha! But indeed, was thinking about something like that. Altought, I don't see why it would be a problem that a recipe get's shared. Unless it is that much of a family secret :p

**Comment by wengtad** [comment]
> A database to track recipe share tokens. A route/page on the frontend that is dedicated to shared recipes. Something like recipe/shared/{token}. And a background task to purge tokens on some interval.

I think this can be part of enhancement later in another release.

What I'm thinking is like the admin page, it will redirect to login like image below. Not sure how this work but that's is enough for me. Maybe this could be another release also?
![image](https://user-images.githubusercontent.com/12437747/121487299-88e01980-ca04-11eb-95fb-b36225063f23.png)

**Comment by hay-kot** [comment]
Private recipes are now live in the beta/demo-site 🚀. I've added the  "Share A Private Recipe Link" to the feature requests discussion as well

**Comment by wengtad** [comment]
Awesome!

**Comment by zierbeek** [comment]
I think this isn't working yet. Or is the 'Share a private recipe link' a thing that needs to come yet?

**Comment by hay-kot** [comment]
> I think this isn't working yet. Or is the 'Share a private recipe link' a thing that needs to come yet?

Share links are a future concern at this point, I've added it to the feature requests on the discussion page. Going to close this for now. Thanks all 👍
