### ISSUE TITLE
[Feature] Additional Database Support

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#48]
Additional support for SQLite and/or PostgreSQL

**Comment by anoma** [comment]
To add some weight to this. The current docker dependency of requiring mongo and optionally mongo-express stands in the way of uptake because only a small percentage of user will have this in place... putting mealie firmly into the `try it later when i have time` pile for most.

If an alternative is far off I would strongly suggest some sort of demo mode to get eyes on the project right now which is the critical moment.

However if you can get a self contained sqlite container up you would, in my humble opinion, be making a wise and timely resource allocation choice.

**Comment by hay-kot** [comment]
> To add some weight to this. The current docker dependency of requiring mongo and optionally mongo-express stands in the way of uptake because only a small percentage of user will have this in place... putting mealie firmly into the `try it later when i have time` pile for most.

I don't quite understand. What's the barrier in spinning up Mongo? I've experienced 0 issues in development or production with Mongo itself. It's one of the "it just work" container for me. You don't even have to create that database it's all done for you. What's the negative for you? 

There are significant drawbacks to using SQLite  in production. There's essentially no ability to implement robust search capabilities without extensive work on the backend. 

Im considering implement SQLite as a "demo" sort of feature, but having to maintain two database types hinders development and app improvements when it's just me in my free time.

**Comment by anoma** [comment]
Uptake of single container solutions is in my experience much higher than multiple container solutions.

Many projects end up coming back around eventually to the concept of a single container option for tiny installs but recommending, or even requiring for support, a full fat full scalable multi container version to get around the `land and leave` crowd who want something very simple to try in the first instance.

The choice is obviously yours I am just saying the vast majority of people falling on this project from google/reddit wont even know what mongo is.

**Comment by hay-kot** [comment]
A minor update on this. I'm working on a large migration to abstract the database calls to allow for a more extendable codebase. With that, I'm implementing the [TinyDB](https://github.com/msiemens/tinydb) package to handle a flat-file setup (no database). It's a rather long process so it may be a week or two before anything useable comes out of this.

**Comment by hay-kot** [comment]
> 
> 
> A minor update on this. I'm working on a large migration to abstract the database calls to allow for a more extendable codebase. With that, I'm implementing the [TinyDB](https://github.com/msiemens/tinydb) package to handle a flat-file setup (no database). It's a rather long process so it may be a week or two before anything useable comes out of this.

I was wrong this was a terrible approach and I wasted a ton of time trying to make it work. That said SQlite support is now live in the dev branch!
