### ISSUE TITLE
Custom sites mix up category items

### ISSUE THREAD

**Issue by simphide** [hay-kot/mealie#480]
**Describe the bug**

I have created custom sites in the settings for breakfast, lunch and dinner.

When you click on a tab of a custom site and then switch to another site and repeat these steps a couple of times, the categories mix up and the items don't fit the selected category anymore...
**Steps To Reproduce**
1. Open main page
2. select custom site
3. select category tab on custom site
4. switch to another custom site 
5. repeat step 3 and 4 a couple of times

**Sample Code**
-

**Expected behavior**
category displays correct items

**Actual Behavior**
it doesn't

**Screenshots**
normal view:
![image](https://user-images.githubusercontent.com/8183517/121521558-82e23c80-c9f4-11eb-835b-be86e3bebb25.png)

mixed up items:
![image](https://user-images.githubusercontent.com/8183517/121521462-6514d780-c9f4-11eb-88d8-3d2447092e36.png)
![image](https://user-images.githubusercontent.com/8183517/121521506-72ca5d00-c9f4-11eb-8d0e-d9b316ace6c1.png)

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04 (server) macos (client)
 - Deployment: docker-compose
 - Browser: chrome
 - Version: 0.4.3

**Comment by hay-kot** [comment]
I'm not able to replicate on the demo/beta site. I suspect this may already be resolved as I've changed the way that page data is populated in the next release. 

can you try to replicate this on the demo site and/or pull the `:dev` tag from dockerhub and give see if you can replicate it locally? It's still in beta so definitely keep your main instance

**Comment by simphide** [comment]
Sure, so the first problem I had with the beta was that when I used my backup to import recipes that the categorys were'nt loaded properly (don't know if this is already known)
![image](https://user-images.githubusercontent.com/8183517/121646491-ac9f7000-ca95-11eb-86b1-0a8ef7a52511.png)
![image](https://user-images.githubusercontent.com/8183517/121646512-b1642400-ca95-11eb-9300-e06aff1fb5fe.png)
after I created one random category, all the other categorys apperead and worked again...

But the bug with the mixed up categorys seems to be fixed - thank you!

**Comment by wengtad** [comment]
Hi @simphide , you may try refresh the page manually after import.
