### ISSUE TITLE
Missing apple-touch-icon

### ISSUE THREAD

**Issue by dcarls0n** [hay-kot/mealie#484]
**Bug Overview**
The mealie webpage does not have an apple-touch-icon so when you add a safari shortcut to Mealie to your iOS Home Screen, the icon is not the mealie icon, but instead a screenshot of the webpage.

This should be a trivial fix.

See: [Apple.com - Configuring Web Applications](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) 

**Steps To Reproduce**
1. Open the safari browser on iOS and direct it to your mealie install
2. Tap the share icon
3. Tap “Add to Home Screen”
4. Note the icon on the left is just a screenshot of the page rather than the mealie icon

**Expected behavior**
The icon generated by iOS should pull the mealie icon from apple-touch-icon.

**Actual Behavior**
The icon generated by iOS is just a screenshot of the mealie page.

**Device Information:**
 - OS: iOS 14.6
 - Deployment: docker-compose on RPi4
 - Browser: Safari
 - Version: v0.4.3

**Additional context**
[Apple.com - Configuring Web Applications](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html)

**Comment by dcarls0n** [comment]
Looks like this may be fixed in v0.5.0 with the PWA support.

**Comment by wengtad** [comment]
You may try out on the demo site [here](https://mealie-demo.hay-kot.dev/). :)
