### ISSUE TITLE
[Beta] Edit from recipes page doesn't have EBR

### ISSUE THREAD

**Issue by zierbeek** [hay-kot/mealie#485]
**Describe the bug**
Can not save recipe edits when clicking on the edit button on the recipes page

**Steps To Reproduce**
1. Log In
2. On recipes page, click on edit
3. Click on settings and change something
4.No save button to save

**Expected behaviour**
A save button or automatically saved when buttons are toggled

**Actual Behavior**
Nothing, no save button and settings are wiped upon refresh

**Comment by hay-kot** [comment]
Recipe settings are saved when you save the recipe itself, since they are recipe specific setting.

**Comment by zierbeek** [comment]
wait will show with screenshots

Upon login, click edit: 
<img width="363" alt="Schermafbeelding 2021-06-11 om 10 07 48" src="https://user-images.githubusercontent.com/58994651/121653462-ff305a80-ca9c-11eb-97ce-2f9eb35ed6a6.png">

Tick the toggle, but no option to save
<img width="1177" alt="Schermafbeelding 2021-06-11 om 10 08 03" src="https://user-images.githubusercontent.com/58994651/121653449-fdff2d80-ca9c-11eb-9d84-37fdd5f3a367.png">

Refresh page and click edit again, old settings are there. 
<img width="1176" alt="Schermafbeelding 2021-06-11 om 10 08 19" src="https://user-images.githubusercontent.com/58994651/121653433-fb043d00-ca9c-11eb-8c2b-d9c24dada575.png">

**Comment by hay-kot** [comment]
Ah, good catch! Looks like Im not picking up on the edit state change, I'll take a look.

**Comment by hay-kot** [comment]
Should be fixed in the latest build
