### ISSUE TITLE
[Beta] Tag and Category not create when import backup

### ISSUE THREAD

**Issue by wengtad** [hay-kot/mealie#486]
**Describe the bug**
Tag and Category are not create when using backup zip file from v0.4.3 during import process.

**Steps To Reproduce**
Please be specific!
1. Login Mealie
2. Go to 'Settings'
3. Go to 'Dashboard'
4. Click on 'Upload'
5. Upload v0.4.3 backup zip file
6. Click on the uploaded file
7. Check 'Recipes'
8. Click on 'Import'
9. Go to 'Toolbox'
10. View the 'Categories' or 'Tags'

**Sample Code**
You may use this file to test if you want. [Test-Tag-And-Cat.zip](https://github.com/hay-kot/mealie/files/6637732/Test-Tag-And-Cat.zip)

**Expected behavior**
Tag and Category is show on the recipe but actual is not create on Mealie

**Actual Behavior**
Tag and Category should auto create during import process

**Screenshots**
You may view it [here](https://mealie-demo.hay-kot.dev/recipe/test-tag-and-cat)

**Device Information (please complete the following information):**
 - OS: Win10
 - Deployment: demo
 - Browser: Brave
 - Version: 0.5.0-beta

**Comment by hay-kot** [comment]
#480 Also makes mention of this, did you just need to refresh the page?

**Comment by wengtad** [comment]
Yes refresh the page manually did the trick.
