### ISSUE TITLE
[Task] Migrate from Vue-CLI to Nuxt

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#489]
Description: ⬆️ See Title 

Checklist: 
- [ ] Migrate Packages
- [ ] Migrate Components
- [ ] Convert to Vite dev server
- [ ] Robust Build/User Manual Testing

**Comment by wengtad** [comment]
Are you planning to use SSR?

**Comment by hay-kot** [comment]
> Are you planning to use SSR?

I would like to, but I'm not sure how users would feel about 2 containers for a single app. The end user performance improvements would be pretty noticeable though.

**Comment by wengtad** [comment]
Hmm yeah, but if compare 2 containers and performance improvements I think they will choose latter ? Or will you open a poll to let user decide or just go with it?
1 last thing, really not possible to only 1 container for a single app if using nuxt ssr ? Not much experience on this field.

**Comment by hay-kot** [comment]
I don't suppose there's anything stopping you from running the Node server and the Python API server on the same docker container but I'd think that goes against the purpose of docker? In this case everything is such a small scale it probably doesn't actually matter though.

**Comment by hay-kot** [comment]
closing to consolidate tasks
