### ISSUE TITLE
Multilanguage support possible?

### ISSUE THREAD

**Issue by NimdaBE** [hay-kot/mealie#50]
Hello,

i would like to know if multiple languages are (or will be) supported? I would like to use this for our cooking-club with some friends, but i would like to know if this application can be set to another language (dutch for example) because some of them have limited knowlegde of english. I would gladly like to help with the translations...

keep up the great work!

**Comment by antoine2tt** [comment]
Totally agree, French translation could be good too. I can help with it, but i have no idea how to

**Comment by kentora** [comment]
Any preferences on which tools to use for this?
[Vie i18n](https://kazupon.github.io/vue-i18n/) seems to be quite reasonable for the purpose, and is built by the Vue core team. I think json files would be the most reasonable format to store the translations.

A tool should also be selected for editing the translations - the json files could just be edited by checking out the code and editing the json files, but a better option might be a web interface like [Weblate](https://weblate.org/) either the free version, or a hosted version.

This might be a good issue for someones first issue in a Vue project, as it would likely take you around the whole project and see the structure. I might look into this, once the tools have been decided

**Comment by hay-kot** [comment]
@kentora  @zackbcom  has brought up working on this as well. Join the discord and we can work out identifying the tool. I'm flexible on tooling.

**Comment by kentora** [comment]
Where do I join the discord? :)

**Comment by hay-kot** [comment]
> Where do I join the discord? :)

https://discord.com/invite/R6QDyJgbD2

**Comment by zackbcom** [comment]
@kentora , if you would like to start the work on this, please do. I've been sick recently and haven't started on the code.

**Comment by hay-kot** [comment]
Additional language support is now available. Please see the docs for information on how to contribute additional languages

https://hay-kot.github.io/mealie/contributors/translating/
