### ISSUE TITLE
[Task] Add Confirmation Dialogs

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#504]
Description: Add Confirmation dialogs to various new delete functions

Checklist:
- [x] Category Delete Section

**Comment by wengtad** [comment]
Add on:

- [ ] Tag Delete Section
- [ ] Events Delete Section (not sure this need confirmation or not, and there is a bug on delete, if will show red popup but when you refresh the page then the item is gone)
- [ ] Backups Delete Section (it will show unable to delete backup, but actual the item is deleted, wrong message?)
- [ ] Custom Page Delete Section (same with backup, wrong message after delete)

There are some bugs over there mainly wrong message with red color snackbar. This is my finding on missing confirmation dialogs.

**Comment by hay-kot** [comment]
> Add on:
> 
> - [ ] Tag Delete Section
> - [ ] Events Delete Section (not sure this need confirmation or not, and there is a bug on delete, if will show red popup but when you refresh the page then the item is gone)
> - [ ] Backups Delete Section (it will show unable to delete backup, but actual the item is deleted, wrong message?)
> - [ ] Custom Page Delete Section (same with backup, wrong message after delete)
> 
> There are some bugs over there mainly wrong message with red color snackbar. This is my finding on missing confirmation dialogs.

Whoo! That's a good bug report. Thanks for all the work lately. Having super specific feedback like this is priceless, turns a 2 hour task into a 15 minute one.

**Comment by wengtad** [comment]
I will try take a look on this.
