### ISSUE TITLE
[Task] ⚖️ Recipe Ingredient Scaling 

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#507]
## Checklist:
 - [ ] Backend: 
     - [x] Add Database Layer
     - [x] Add New Schema
     - [x] Auto Generate Basic Set of Units on database init
     - [x] Auto Scrape string to units/food
     - [x] CRUD routes for Foods and Units
     - [x] Add Merge Foods supports
     - [x] Add Merge Units support
     - [x] Update API Docs/Schema in Pydantic Model
- [ ] Frontend
     - [x] Set Frontend to Expect Objects
     - [x] Add Units/Food CRUD User Interface (Including Merge)
     - [x] Rewrite Ingredients Editor
     - [x] Add Support for Ingredient Sections w/ Title Attribute (See how Instruction sections works)

## Relevant PRs:
#506 - Add Database Layer to Support Scaling - @hay-kot

**Comment by hay-kot** [comment]
I've gone through and added the database layer for the required fields. There is both a Foods and Units field where the foods are things like Carrots or Onions and Units are like Cups or Oz. I've also added the following behavior

- When creating a Recipe Pydantic Model if it's a list of strings it will be converted to the new schema by passing the string as the notes field. This will allow backups/restores to happen seamlessly. 
- By default, all ingredients default to `amount_disabled=True` this behavior results in only the notes section being shown. This will retain the simplicity for users who don't care about recipe scaling. 
- Shopping lists now pull the notes field out of the ingredient. This will need to change in the future. Likely a whole rewrite of the shopping list is necessary to provide adequate merging of ingredients.
- I've also generated some skeleton routes that don't do anything yet for the Food/Units that will be required for the CRUD functionality through the API. 

I'm going to be leaving this for a while to work on tests but this should be a good starting point.

**Comment by zierbeek** [comment]
Is it considered that we would like halve the recipe. currently, if a cake is made for example, with 8 portions. There is no option to scale it down to let's say 6 servings. Although, this is only a rule of three.

**Comment by hay-kot** [comment]
@zierbeek that's not a use case I'm considering.

**Comment by Sennevds** [comment]
@hay-kot I have the same request. But it's already said in the discord. Several people use it for non baking and there it's logical that you can scale down or up with a increment of one. Maybe an option to add to a recipe that it can be scaled down or something?

**Comment by mjmccans** [comment]
For what it is worth, I too would really appreciate being able to scale below one or be able to scale up by a fraction (e.g., 1.5 the recipe). I am not a great cook so I may be missing reasons why this would not work, but I often scale my recipes by fractional amounts and allowing this feature would save me doing some math. Either way, I am really enjoying the program and thank you for all of the effort!

**Comment by hay-kot** [comment]
Hey folks, closing this issue since the initial support is now baked into Mealie v1. As far as the scaling down - it's not something I'm going to look at but happy to look at a feature request and/or a PR to add it.
