### ISSUE TITLE
[Beta] Descriptions without image

### ISSUE THREAD

**Issue by wengtad** [hay-kot/mealie#515]
**Describe the bug**
Descriptions not showing correctly on hover without image.

**Steps To Reproduce**
Please be specific!
1. Create new recipe with descriptions and without image.
2. Go to recipe list
3. Hover on the recipe

**Expected behavior**
Should show descriptions correctly.

**Actual Behavior**
Descriptions not showing correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/12437747/121872026-623d1e00-cd37-11eb-8fde-c347b4365989.png)

**Device Information (please complete the following information):**
 - OS: Win10
 - Deployment: `make docker-prod`
 - Browser: Brave, Firefox
 - Version: 0.5.0-beta

**Comment by hay-kot** [comment]
Closing since this has been fixed, but the `dev` branch is still broken for other reasons 😞
