### ISSUE TITLE
[Beta] Demo/Dev branch is broken - 308 Redirect Error Loop

### ISSUE THREAD

**Issue by anoma** [hay-kot/mealie#516]
**Describe the bug**

The demo is broken.

**Steps To Reproduce**

Go to https://mealie-demo.hay-kot.dev/

**Expected behavior**

A demo webpage

**Actual Behavior**

A 308 redirect error loop

**Additional context**

Link presented on https://github.com/hay-kot/mealie as "view demo"

**Comment by zierbeek** [comment]
Haha! this is known, dev is working on it :) check the discord!

**Comment by hay-kot** [comment]
Thanks! We are taking on this, something went wrong with a PR to the `dev` branch and is giving me all kinds of headaches! In the meantime you can access the demo site by going to a subpath like https://mealie-demo.hay-kot.dev/recipes/all

For some reason that still works. I'll keep this updated when we've got a fix

**Comment by hay-kot** [comment]
Dev branch is back to working. The site overall has slowed down the initial load for some reason...still looking into this but the initial issue is resolved.

**Comment by adrianbrink** [comment]
@anoma I'm trying to reach you via email from adrian@officium.dev . It'd be fantastic if you could quickly answer me or write me a fresh email :-)
