### ISSUE TITLE
[Task] - Add Reset Password Support

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#517]
Description: Add reset via email with tokens generated from the backend server

Checklist
- [x] Python Email Send Code
- [x] Email Template(s)
- [x] Reset Password Tests
- [x] Password Reset UI

**Comment by zierbeek** [comment]
maybe upgrade this issue to mails in general. I would like that my users gets a confirmation mail that he/she is subscribed to mealie.
