### ISSUE TITLE
[Task] Optimize Web Icons

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#522]
Description: Replace current schema for icons with mdi/js [See Here](https://vuetifyjs.com/en/features/icon-fonts/#material-design-icons-js-svg)

**Comment by zierbeek** [comment]
isn't most of it already replaced with mdi?

**Comment by hay-kot** [comment]
> isn't most of it already replaced with mdi? 

I believe switching to these offers tree shaking support, but reading it again I'm not sure. Part of the large bundle problems is that it's shipping a ton of material design icon css, so I thought this might help.

I could be wrong though.

**Comment by zierbeek** [comment]
I know there are some things which are mdi already like mdi-share or mdi-cog,...
Or is this something different?

**Comment by hay-kot** [comment]
> I know there are some things which are mdi already like mdi-share or mdi-cog,...
> Or is this something different? 

This is something different I believe. If you look at the example in the link there's a reference where you import the icon directly from the package, that way when the site is built, it will remove the unused icons from the bundle. I don't believe this is the current behavior.

**Comment by zierbeek** [comment]
I see!
Willing to give this a crack, should in each file where the icons are used, the import script added and the icons replaced with the right mdi variant?

**Comment by zierbeek** [comment]
I see, will do this!
