### ISSUE TITLE
[Task] Lazy Load Localization

### ISSUE THREAD

**Issue by hay-kot** [hay-kot/mealie#527]
Description: Lazy load localizations to reduce initial bundle size -> [See here for details on how](https://kazupon.github.io/vue-i18n/guide/lazy-loading.html)

**Comment by sephrat** [comment]
I was also curious to get this to work. I'll take a look.

**Comment by hay-kot** [comment]
FYI, I added a dependency for analyzing the bundle. If you run `make frontend-build` it will open up an html report to show you the impact of different packages. Looks like trimming out the localization will make a big difference on initial load.
