### ISSUE TITLE
The ingredients section is missing for new recipes

### ISSUE THREAD

**Issue by ltctceplrm** [hay-kot/mealie#538]
**Describe the bug**
Since the v0.50 update if I create a new recipe the ingredients section is missing

**Steps To Reproduce**
Please be specific!
1. Click on new recipe from any page
2. No ingredients section

**Expected behavior**
The ingredients section is missing

**Actual Behavior**
Unless the ingredients section has moved place I don't see it anymore, I can still add ingredients if I edit through json and then the section shows up again.

**Screenshots**
https://i.imgur.com/ci18dYZ.png

**Device Information (please complete the following information):**
 - OS: [Debian]
 - Deployment: [docker-compose]
 - Browser: [Firefox or chrome]
 - Version: [v0.50]

**Comment by sephrat** [comment]
Yep, doesn't show either in edit mode if the recipe doesn't have ingredients.
I'll see what I can do.

**Comment by wengtad** [comment]
Temporary solution is to use the JSON editor, try add at least 1 object in `recipeIngredient`

```json
"recipeIngredient": [
    {
      "title": null,
      "note": "your ingredient here",
      "unit": null,
      "food": null,
      "disableAmount": true,
      "quantity": 1
    }
  ],
```

**Comment by hay-kot** [comment]
This is now fixed in v0.5.1 thanks to @sephrat 🎉

**Comment by Rickman** [comment]
I'm not sure if it is, I still can't see any option for adding ingredients?

**Comment by Rickman** [comment]
I'm not sure if it is, I still can't see any option to input ingredients on 0.5.1?

**Comment by hay-kot** [comment]
> I'm not sure if it is, I still can't see any option to input ingredients on 0.5.1?

I have it on mine, there's a plus button in edit mode next to the bulk add. 

<img width="387" alt="Screen Shot 2021-06-17 at 10 56 19 AM" src="https://user-images.githubusercontent.com/64056131/122458665-89c10000-cf5c-11eb-82af-ae731d479507.png">

**Comment by Rickman** [comment]
I've got it now, thanks for the fix!
