### ISSUE TITLE
When manually adding recipe without image, no error is thrown, and loading bar shown forever

### ISSUE THREAD

**Issue by kentora** [hay-kot/mealie#54]
Apparently a recipe cannot be saved without selecting an image. (This might be the actual bug, or desired functionality, I'm not a 100% certain).

However, when trying to manually add a recipe with no selected image, a progress bar appears, but nothing further happens. Upon inspecting the console, I saw that an error being thrown: `TypeError: null is not an object (evaluating 'e.fileObject.name')`.

To fix this bug: either allow creation without image, or show an error dialog when saving fails. I think that in general, error handling might be missing from the dialog, but it behaves in a different manner when other data is missing.

**Comment by hay-kot** [comment]
This has been addressed in the [new release](https://github.com/hay-kot/mealie/releases/tag/v0.0.2)
