### ISSUE TITLE
Tags and Categories gone after 0.4.3 -> 0.5.1 Upgrade and Import

### ISSUE THREAD

**Issue by rich1110** [hay-kot/mealie#554]
**Describe the bug**
Upgraded Mealie from 0.4.3 to 0.5.1 on UnRAID docker setup. As predicted(?) all my existing database and information (recipes/tags/categories/users etc) was gone after the upgrade so I imported the automatic backup that was created prior to upgrade. All my recipes and information were imported without any fails recorded. However, all my Tags and Categories are now missing. 

Any Tags or Categories that were assigned to a specific recipe still appear there, however the 'list' of Tags/Categories in the dropdown boxes (in the recipe cards) and in the 'Settings->Toolbox' section are gone.

Furthermore, If I try to re-add a missing Tag/Category that was there prior to the upgrade, I receive an error ("Category Creation Failed").

**Steps To Reproduce**
Please be specific!
1. Upgrade Mealie from 0.4.3 to 0.5.1
2. All my existing database/recipes/tags/categories/users etc were gone.
2. Go to 'Settings > Dashboard > Backups' and upload/import previous backup
3. All recipes and embedded tags/categories are imported without fails.
4. All my listed categories/tags in recipe card dropdown boxes and  'Settings->Toolbox' section are gone.
5. Cannot re-create previous Tag/Category that was there prior to the upgrade, I receive an error ("Category Creation Failed").

**Device Information (please complete the following information):**
 - OS: UnRAID
 - Deployment: Docjker container (Docker-version 20.10.5)
 - Browser:Firefox 89.0
 - Version: 0.5.1

**Comment by zierbeek** [comment]
please make sure to logout, login and refresh the page after the imported backup

**Comment by hay-kot** [comment]
@zierbeek is correct, that you likely just need to refresh your page (Maybe a hard refresh?). This is not an ideal experience though. I'll add this to the project tracker to find a better way to "reload" the page on a backup import.

**Comment by rich1110** [comment]
You are correct! I Logged out and in and did a hard refresh of the site and all appears normal now. Sorry for the confusion ;)

**Comment by zierbeek** [comment]
no worries ;)
