### ISSUE TITLE
Nginx Proxy Manager not working, any help with config?

### ISSUE THREAD

**Issue by yieldhog** [hay-kot/mealie#556]
**Describe the bug**
Using Nginx Proxy Manager [https://github.com/jc21/nginx-proxy-manager](url) I am unable to forward to Mealie. I feel like it worked a few versions ago. I have (many) docker images successfully forwarded on my various domains.

Receive a time-out error. I did look at the sample proxy configuration here [https://hay-kot.github.io/mealie/documentation/community-guide/swag/](url) -- doesn't seem applicable to Nginx Proxy Manager.

**Actual Behavior**
Timeout

**Device Information (please complete the following information):**
 - Version: 0.5.1

**Additional context**
Thank you

**Comment by zierbeek** [comment]
hi! There are maybe more to help on the discord channel. Please come over there! ;)

**Comment by yieldhog** [comment]
@zierbeek -- I realized my DDNS had not been updated, if anyone happens to see this, default settings for Nginx Proxy Manager work great for Mealie
