### ISSUE TITLE
Inconsistent Message Style

### ISSUE THREAD

**Issue by wengtad** [hay-kot/mealie#560]
**Describe the bug**
I think this is not a bug, just want to know when will use warning or error snackbar ?

**Steps To Reproduce**
Please be specific!
1. Go to 'Dinner This Week'
2. Go to 'Dinner Today'

**Screenshots**
Dinner This Week:
![image](https://user-images.githubusercontent.com/12437747/122504934-e3ddc600-d02d-11eb-854d-f1ccff9d9b15.png)
Dinner Today:
![image](https://user-images.githubusercontent.com/12437747/122504971-f6f09600-d02d-11eb-8fd0-ababb9ef3742.png)

**Device Information (please complete the following information):**
 - OS: Win10
 - Deployment: `make docker-prod`
 - Browser: Firefox, Brave
 - Version: 0.5.1

**Comment by hay-kot** [comment]
I've been thinking about this for that past few days and don't have a good answer. Since both of these are not indicating an actual error, they should be warnings? I don't have a good way to define the behavior though. I'm open to some guidelines we can include in the developer guide though.
