### ISSUE TITLE
Error 422/404 when saving a recipe note without a title

### ISSUE THREAD

**Issue by asecor** [hay-kot/mealie#586]
**Describe the bug**
When attempting to save a note without a title a " Recipe update failed" and 404 message is displayed and the note contents along with any other recipe modifications do not get saved.

**Steps To Reproduce**
Please be specific!
1. Go to any recipe and edit it
2. Click on the + under Note
3. Leave the title empty
4. Add text to the note part
5. Click Save

**Sample Code**
N/A

**Expected behavior**
Note contents should be saved even without a title.

**Actual Behavior**
Recipe closes and a "Recipe update failed" is displayed along with a 404.

**Screenshots**
![image](https://user-images.githubusercontent.com/13489208/122954686-f2a2e080-d37f-11eb-9264-9d756c6ac1d1.png)

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.1
 - Deployment: Docker Version 20.10.2, 
 - Browser: IE Edge
 - Version: Version 91.0.864.41 (Official build) (64-bit)

**Additional context**
N/A

**Comment by sephrat** [comment]
PUT request returns a 422:
{"detail":[{"loc":["body","notes",0,"title"],"msg":"field required","type":"value_error.missing"}]}

Then the frontend tries to get "undefined" recipe which in turn results in a 404.

- [ ] Fix the actual 422 issue
- [ ] Better error catching to prevent the subsequent 404 and losing user input
