### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by calum523** [hay-kot/mealie#595]
Having the ability to add URL's from the GOUSTO and Hello fresh cookbooks?

https://www.gousto.co.uk/cookbook
and
https://www.hellofresh.co.uk/recipes/

If this could be added it would be much appreciated, thanks.

**Comment by zierbeek** [comment]
Hi, if i'm nog mistaken, hello fresh recipes could be added. I have no troubles with this

**Comment by hay-kot** [comment]
> https://www.gousto.co.uk/cookbook

Does not return valid schema. Requests/Contributions for individual sites should be directed to https://github.com/hhursev/recipe-scrapers and once added those changes can be down-streamed into Mealie.

> https://www.hellofresh.co.uk/recipes/

Working fine in v0.5.0+
