### ISSUE TITLE
Hide home page

### ISSUE THREAD

**Issue by DOFfactory** [hay-kot/mealie#597]
Currently whoever knows the address of my site, can access the home page, i.e. the list of recipes. I could not figure out how to disable the Home page, or change it for e.g. the Login page. I would prefer not to have a publicly facing recipe page, if possible. 

Can you implement this, or if it is already implemented, share with me? I was not able to find the answer to this in the documentation.

**Comment by hay-kot** [comment]
This has been discussed in the [Feature Request Megathread](https://github.com/hay-kot/mealie/discussions/318).

> Private site with Login Portal ❌ - IMO This is outside of the scope of Mealie and is better implemented with a security provider like Authelia, Keycloak, or HTTP Auth

I won't be implementing this feature.
