### ISSUE TITLE
Bug while creating a recipe with a note

### ISSUE THREAD

**Issue by ar0707** [hay-kot/mealie#601]
Describe the bug
it is not possible to save without a note title. See image. After adding the note title, the save function works. 
running with Docker v0.5.1 on my synology nas using Chrome 

Steps To Reproduce
1. New recipe
2. add recipe Name
3. add Note without title 
4. try to safe

Screenshots
<img width="1656" alt="2021-06-28 23_03_11-" src="https://user-images.githubusercontent.com/44272599/123704053-87687b00-d865-11eb-8855-85f9cdc92bd7.png">

**Comment by wengtad** [comment]
Duplicate #586 and fixed on #592, pending release.
