### ISSUE TITLE
Iframe Scrolling On IPad

### ISSUE THREAD

**Issue by grownthc** [hay-kot/mealie#604]
**Describe the bug**
When displaying mealie inside of an iframe in home assistant on an ipad, i am unable to scroll due to safari iframe issue.

**Steps To Reproduce**
Please be specific!
1. link to mealie inside of iframe on ipad
2. scroll any page
3. page just bounces

**Expected behavior**
Scroll normally like on my Samsung wall mount tablet while inside of iframe inside of home assistant

**Actual Behavior**
bouncing screen and unusable recipe manager while inside of iframe inside of home assistant

**Video Example**
https://youtu.be/T7oWoc5jE5Q

**Device Information (please complete the following information):**
 - OS: iOS 12.4.8
 - Deployment: docker-compose
 - Browser: safari
 - Version: 0.5.1

**Comment by hay-kot** [comment]
Is this isolated to Mealie? Do other web apps operate the same in Iframe? This is a weird one. Likely something to do with the Apple Javascript engine, but no idea what would cause it.

**Comment by grownthc** [comment]
> Is this isolated to Mealie? Do other web apps operate the same in Iframe? This is a weird one. Likely something to do with the Apple Javascript engine, but no idea what would cause it.

To my knowledge this happens whenever embedding a scroll-able webpage into an iframe and display it on an ipad/ios device. From my limited research about it when trying to fix it, i found some posts of people showing a simple css class and a main div would be a workaround, but other then that, I am not to sure how to go about fixing it, other then a dirty work around like i found online.

I tried using hass webserver to contain the iframe itself in a div with the css i found to see if i could get it to scroll but there was no change, sadly.

**Comment by hay-kot** [comment]
Scrolling in an IFrame works fine for me in Home Assistant on my new Ipad. I'm guessing it has something to do with the version of Safari you're running.
