### ISSUE TITLE
Traegar recipes

### ISSUE THREAD

**Issue by Code-Slave** [hay-kot/mealie#613]
Cant import recipies from traegar grill site. Looks like it has whats needed

https://www.traegergrills.com/recipes/rosemary-orange-chicken

Data

[
  {
    "keywords": "",
    "recipeCategory": "Poultry",
    "prepTime": "PT0H15M00S",
    "cookTime": "PT0H45M00S",
    "image": "https://i8.amplience.net/i/traeger/20181214_Roasted-Rosemary-Orange-Chicken_RE_HE_M?w=500&sm=aspect&aspect=1:1&scaleFit=poi&$poi2$",
    "author": "Amanda Haas",
    "recipeIngredient": [
      "(3-4 lb) chicken, backbone removed",
      "olive oil",
      "oranges, juiced",
      "orange, zested",
      "Dijon mustard",
      "chopped rosemary leaves",
      "kosher salt"
    ],
    "recipeInstructions": [
      "Rinse the chicken and pat dry with paper towels.\nAdd A Note\n\nIngredients\n\n1 (3-4 lb) chicken, backbone removed",
      "For the Marinade: In a medium bowl, combine olive oil, juice from the oranges (about 1/4 cup of freshly squeezed juice), orange zest, Dijon mustard, rosemary and salt. Whisk to combine.\nAdd A Note\n\nIngredients\n\n1/4 Cup olive oil\n\n2 oranges, juiced\n\n1 orange, zested\n\n2 Teaspoon Dijon mustard\n\n3 Tablespoon chopped rosemary leaves\n\n2 Teaspoon kosher salt",
      "Place the chicken in a shallow baking dish large enough for chicken to be fully opened in one piece. Pour marinade over the chicken ensuring it is covered with the marinade.\nAdd A Note",
      "Cover with plastic wrap and refrigerate for a minimum of 2 hours or up to overnight, turning once during the process.\nAdd A Note",
      "When ready to cook, set Traeger temperature to 350℉ and preheat, lid closed for 15 minutes.\n\nGrill: 350 ˚F\n\nAdd A Note",
      "Remove the chicken from the marinade and place on the Traeger, skin-side down.\nAdd A Note",
      "Cook for 25 to 30 minutes until the skin is well-browned, then flip. Continue to grill chicken until the internal temperature of the breast reaches 165℉ and the thigh reaches 175℉, about 5 to 15 minutes longer.\n\nGrill: 350 ˚F\n\nProbe: 165 ˚F\n\nAdd A Note",
      "Let rest 10 minutes before carving. Enjoy!\nAdd A Note"
    ],
    "@context": "https://schema.org",
    "@type": "Recipe",
    "url": "https://www.traegergrills.com/recipes/rosemary-orange-chicken"
  }
]

**Comment by hay-kot** [comment]
There's no name/title in the schema, so it gets caught up when saving to the database. I can look at adding some validation and than generate a generic place-holder name

**Comment by Code-Slave** [comment]
That would be perfect. Lots of good smoker recipies on there
