### ISSUE TITLE
recipes not loading after upgrade to 0.5.1 (beta)

### ISSUE THREAD

**Issue by slodown** [hay-kot/mealie#614]
Hello,

my recipes are not loading. The recieps are still in the sqlite DB, but when loading the page i got an 'internal server error'.

If I try to create a backup I got an error, see logs.

ERROR: 04-Jul-21 19:18:31 	(sqlite3.OperationalError) no such column: recipes_ingredients.title
[SQL: SELECT recipes_ingredients.id AS recipes_ingredients_id, recipes_ingredients.position AS recipes_ingredients_position, recipes_ingredients.parent_id AS recipes_ingredients_parent_id, recipes_ingredients.title AS recipes_ingredients_title, recipes_ingredients.note AS recipes_ingredients_note, recipes_ingredients.quantity AS recipes_ingredients_quantity 
FROM recipes_ingredients 
WHERE ? = recipes_ingredients.parent_id ORDER BY recipes_ingredients.position]
[parameters: (1,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

Thank you!

**Comment by slodown** [comment]
That's my problem. I do not have a backup :/

The updated the latest beta versions.

I will change to stable. Any chance without backup?

**Comment by hay-kot** [comment]
The Beta and Stable both share the same database schema at the moment. If you don't have a backup I'm not sure how to help. You could try to find `dev` branch before the database changes were made and build it from source to get your data. 

Are you sure you don't have a backup? They should be done automatically, so you should have at least one.
