### ISSUE TITLE
Some settings not available when creating a new recipe

### ISSUE THREAD

**Issue by FrouxBY** [hay-kot/mealie#615]
**Describe the bug**
When I start a new recipe (without importing from zip or url), the Recipe setting are not available, which means that I cannot configure for example if a recipe is private before publishing it (it requires saving, then editing to modify this setting)

**Steps To Reproduce**
Please be specific!
1. Go to your mealie Instance (0.5.1 dev 74b1e62)
2. Click on + -> "New"
3. Click on "Settings"
4. See that settings are not displayed as they should be

**Expected behavior**
Displaying recipe settings

**Actual Behavior**
Only title of this menu is displayed, without toogle options

**Device Information (please complete the following information):**
 - Deployment docker-compose, on dev tag

Thanks for your help

**Comment by hay-kot** [comment]
Thanks for the report! This was obviously not ideal. In the next release you'll be able to set these accordingly. Additionally, you'll be able to set the defaults through ENV variables so you can keep you settings consistent across the board.
