### ISSUE TITLE
[Browser Compatibility] WebP Images not supported in Safari below 14.4 

### ISSUE THREAD

**Issue by FrouxBY** [hay-kot/mealie#616]
**Describe the bug**
I have a (quite old) ipad, very useful in the kitchen, but image are not displayed either on safari, or as a installed WPA, 
Everything else work so far

**Steps To Reproduce**
I don't have other iOS device to test on, so it might be specific of this old iOs version, 
On laptop and android smartphone, I don't have this issue, image are displayed correctly

** Mealie version
Docker-compose on dev tag, mealie 0.5.1 dev (74b1e62)

Thanks for your help !

**Comment by hay-kot** [comment]
I don't have this issue on my iPad so I suspect it has to do with the older version of. Is is possible to update to a newer version of Safari or something? Not sure there's much I can do on this end.

**Comment by FrouxBY** [comment]
No, I cannot update, the hardware is too old,

If this is not an issue on newer devices, don't worry with it,
Maybe one day I will have time to investigate logs from my iPad, but meanwhile this is not a big issue

**Comment by tlskinneriv** [comment]
I am also running iOS 12.5.4 on an older iPad (iPad Air, ME997LL/A to be exact) and running into the same issue. Looks like this is from Safari <14 not supporting WebP images. Adding an option for the browser to load a JPEG or PNG when WebP is not supported would allow browsers that don't support WebP to load the images. Looks like there are options out there to detect WebP support/give other image source options in Vue (https://codepen.io/gksander/pen/QPEMeZ; https://dev.to/ignore_you/minify-generate-webp-and-lazyload-images-in-your-vue-nuxt-application-1ilm). Wish I could be of more help, but I've not used Vue before.
