### ISSUE TITLE
Section behaviour when adding a step

### ISSUE THREAD

**Issue by FrouxBY** [hay-kot/mealie#617]
**Describe the bug**
When I add a step (bulk or single one), the editor automatically add an empty section header to the step (or to all step if bulk added), which seems kind of disturbing,

Moreover, when I save the recipe, the immediate view is the edited recipe, with the empty section displayed. I need to refresh the page so that they disappear

**Steps To Reproduce**

1. Go to a recipe
2. Add a new step
3. See that a section is automatically added
4. write some text in the step, but not on the new section header
5. save the recipe
6. See that the empty header is displayed

Thanks for your help

**Comment by zierbeek** [comment]
Can confirm i and this top earlier
