### ISSUE TITLE
No users/recipes after 0.4 to 0.5 upgrade

### ISSUE THREAD

**Issue by CorneliousJD** [hay-kot/mealie#619]
Using 0.4 docker image with only DB_TYPE set to "sqlite" and /app/data/ mapped as a persistent storage volume.

After it upgraded to 0.5 it doesn't seem like it realized 0.4 db was present as perhaps file structure, etc all changed?

I still have a /app/data/db/mealie_v0.4.0.sqlite file 

2 Questions,
1. how do I get everything back properly? (The only auto-backup listed is from today, which has the null/blank data)
2. How do I prevent future updates from breaking everything? 
I would like to be able to rely on remote access to Mealie to house all my recipes. 

I spent about 12 hours or so importing all my recipes only to find them all gone by the next time I accessed it.

**Comment by hay-kot** [comment]
1. If you still have your original database for v0.4.0, roll back to v0.4.0 and create a backup with your data. Then upgrade and import the backup. I'd advise to make a copy of your entire /app/data/ folder as well.
2. [Review the change log before you update](https://hay-kot.github.io/mealie/changelog/v0.5.0/) as well as [the updating section in the documentation](https://hay-kot.github.io/mealie/documentation/getting-started/updating/)


> I spent about 12 hours or so importing all my recipes only to find them all gone by the next time I accessed it.

Mealie doesn't delete data under pretty much any circumstance. My only guess is that you either have your docker volumes configured incorrectly, or you are auto updating the container via watchtower or similar. Auto updating is specifically discouraged in the [documentations first page](https://hay-kot.github.io/mealie/documentation/getting-started/introduction/). Data loss is always a possibility with any application, I'd suggest you use the integrated backup solution and store a copy of your data off-site to avoid all of these issues in the future.

**Comment by CorneliousJD** [comment]
Thank you - I do have backups and I was able to roll back and export from 0.4.0 

I am running the container on unraid which updates containers by default to the :latest tag, will adjust moving forward.
