### ISSUE TITLE
[Feature] Auto-generated shopping list based on Meal Plan

### ISSUE THREAD

**Issue by tylerlucas** [hay-kot/mealie#62]
After creating a meal plan, it would be great to have a shopping list generated which aggregates ingredients from all recipes within the plan. This way you don't need to dig through each recipe to figure out what to buy for the week.

**Comment by adrkable** [comment]
I was literally about to file the same feature request. +1

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
