### ISSUE TITLE
"Favorite" button in incorrect place

### ISSUE THREAD

**Issue by paulfantom** [hay-kot/mealie#627]
**Describe the bug**

**Steps To Reproduce**
Please be specific!
1. Start mealie v0.5.1 using container: `docker run -p 9925:80 hkotel/mealie:v0.5.1`
2. Go to website `localhost:9925/` and login with default user/pass
3. Click on "+" in the bottom right corner
4. Add empty recipe (only with name "Test")
5. View recipe ( `http://localhost:9925/recipe/test` )
6. The "Favorite" button is in the top left corner and not with other buttons (demo site has the button placed correctly)

**Sample Code**

**Expected behavior**

The "Favorite" button is aligned with the rest of round buttons and it is blue.

**Actual Behavior**

**Screenshots**

![Screenshot_20210715_153125](https://user-images.githubusercontent.com/3531758/125796947-07f2443f-73d4-4c50-b382-a60cd7a7a1f3.png)

**Device Information (please complete the following information):**
 - OS: [e.g., WSL2 on Win10, Mac]
 - Deployment: [e.g., Docker-version, docker-compose, Python application]
 - Browser: [e.g., chrome, safari]
 - Version: [e.g., 0.2.0-dev]

**Additional context**

I am no frontend developer, but it seems that `<div>` with a button is not in the same button group as others (`custom-btn-group` class).

**Comment by hay-kot** [comment]
The demo site is always the beta version of the next release. Shows off some of the new features coming. You'll see the button move to the row with the rest in the next release.
