### ISSUE TITLE
Removing stars

### ISSUE THREAD

**Issue by nicolasshu** [hay-kot/mealie#628]
In the UI, there doesn't seem to be a way to remove the stars. For example, if I set the stars to 5 and then wanted to unstar a recipe, I am not sure if you've implemented a way to "unstar" a recipe. Or am I wrong? Thanks!

**Comment by hay-kot** [comment]
You cannot do this through a UI editor. You can if you use the JSON editor and change the rating to 0. I think that is a good enough work around for this as it's probably not a common use-case.
