### ISSUE TITLE
[Feature] Add Cook Time / Prep Time data fields to recipes + filtering

### ISSUE THREAD

**Issue by tylerlucas** [hay-kot/mealie#63]
It would be helpful if we had data fields for cook time and prep time so that we could filter recipes by cook time. 

This will let users quickly sort by quick meals under 30m, for example.

**Comment by hay-kot** [comment]
Working on cook/prep times now. I'm struggling with placement in the UI. Any suggestions on where it should go on the recipe page?

**Comment by tylerlucas** [comment]
Nice!

I think that there are a couple spots it could go:

1. Expand the ‘servings’ field into a multi-field table, and include prep-time/cook-time/total-time/servings all together. Similar to allrecipes. The downside of this is that it bumps down the ingredients.
2. Add a cook-time table directly above the star-rating or below it. This might work well because cook times are a summary of the overall cooking experience, and they are also near the instructions (relevant since cook time is an aggregation of all instructions combined).

Haven’t thought about mobile, though. Hope that helps!

**Comment by kentora** [comment]
Would be real cool to have this as a filter in the "random" mealplan - so that weekdays could be set with a max prep / cook time!

**Comment by mrherman** [comment]
It would be nice if we could have our own "fields" (fields could just be tags/labels with values).  Cook time and prep time are common in cooking (obviously) but some of us might have needs to track other items and search on it.  A few examples could be sodium, or level of spicy/heat.

**Comment by nickcj931** [comment]
> Working on cook/prep times now. I'm struggling with placement in the UI. Any suggestions on where it should go on the recipe page?

Can this not be added on the image of the meal, like a shadow rectangle at the bottom of the image which could pull some tags in.?

Alternatively the way the https://groceri.es card layout is done works very well from a UI perspective

**Comment by hay-kot** [comment]
> Can this not be added on the image of the meal, like a shadow rectangle at the bottom of the image which could pull some tags in.?

This is probably the route I'll go. Never thought of that. Thank you! I'm working on updating the database models to include some more of the basic information that is used in the standard schema that includes cook time and such. Thanks for your insight!

**Comment by nickcj931** [comment]
Glad I was of help. Keep up the good work, love this project and I'll contribute where I can with my limited skills haha

**Comment by jaker-dotcom** [comment]
Hey don't want to open a new issue for this but I don't see no option for filtering prep time.
Neither in recipies page nor meal planner. 
I found no mention of this filter in the docs.

My Version (v3.6.0) deployed via truenas apps i.e. docker image v1.5.33.

I'd be happy to update the docs if someone points me to the solution.

**Comment by michael-genson** [comment]
Our time fields (e.g. prep time) aren't structured, so there's no way to filter on them. It's something I want to implement at some point if someone doesn't beat me to it.
