### ISSUE TITLE
Locales seemingly not working after upgrading to 0.5.2

### ISSUE THREAD

**Issue by kneejah** [hay-kot/mealie#638]
After updating my docker image from 0.5.1 to 0.5.2, nothing seems to load, and none of the strings seem localized in the UI:

In the js console I see
<img width="717" alt="TzV3XBF0rV" src="https://user-images.githubusercontent.com/609994/127204745-1d0ee966-4b72-433c-b4c7-3b12d2a0f7a7.png">
and the UI looks like
<img width="227" alt="swHXamiFCg" src="https://user-images.githubusercontent.com/609994/127204764-ca9b59c1-2a7f-4a1c-8f3d-2670d8349b57.png">

I can provide logs if that would help...

**Comment by ESOB86** [comment]
This is what happened to mine, reinstall from fresh and load your latest back-up to recover.

**Comment by ltctceplrm** [comment]
I had the same problem and @sephrat on discord found how to fix it: Start with a fresh container (I renamed my old persistant data folder) and after loading your backup you immediately change the language in locale settings and save it. Just starting with a fresh container wasn't enough for me

**Comment by kneejah** [comment]
nice, yeah, was a little bit of a pain to unzip, edit locale file, and rezip but i got it working, thanks all!
