### ISSUE TITLE
Latest update (0.5.2) everything is gone

### ISSUE THREAD

**Issue by rich1110** [hay-kot/mealie#640]
**Describe the bug**
After upgrading my UNRAID docker to 0.5.2, all my recipes and are gone. I call login using my previous credentials, but none of the menu items take me anywhere and the main page remains blank. I tried deleting the docker, installing fresh and restoring from a backup (taken just prior to updating), and again I can login with my previous creds but nothing is there. The menu items also look incorrect (as per screen shot).

Logs attached ('mealie.log' was inside docker directory, 'Log for Mealie.txt' was from unraid docker tab)

Really hope I don't have to start again as I don't think I could be bothered and will just move on...

 - OS: Unraid docker
 - Deployment: [e.g., Docker-version, docker-compose, Python application]
 - Browser: Firefox, Edge
 - Version: 0.5.2

![Capture](https://user-images.githubusercontent.com/75110979/127243890-42996c48-e5c1-40c0-b044-ad778d542fbc.JPG)
[mealie.log](https://github.com/hay-kot/mealie/files/6889418/mealie.log)
[Log for Mealie.txt](https://github.com/hay-kot/mealie/files/6889427/Log.for.Mealie.txt)

**Comment by hay-kot** [comment]
There is already an issue open on this.

https://github.com/hay-kot/mealie/issues/637

You likely need to remove the image and cached layers and repull the container and all of its layers.

**Comment by rich1110** [comment]
thanks for the quick reply...

Just to confirm, I have already tried uninstalling docker, removing template and also deleting the remaining Mealie docker directory from my appdata directory in unraid. Then I did a fresh reinstall of the docker.

is this what you meant?

**Comment by hay-kot** [comment]
I don't use Unraid so I don't know how the process goes. The traditional docker command would be to remove the Mealie container and run [docker image prune](https://docs.docker.com/config/pruning/) to remove the images/layers associated with Mealie from docker.

**Comment by ltctceplrm** [comment]
For me just starting with a fresh container wasn't enough, I also had to change my language locale in mealie's settings immediately after loading the backup, if you move away from the dashboard to check out the recipes before changing and saving the language then the recipes seem to disappear and the buttons become like in your screenshot.

Looking at the difference in the backups between 0.5.1 and after successfully importing and changing locale in 0.5.2 it seems like this entry in the settings file:
`        "language": "en",`
changed to
`        "language": "en-GB",`
so I suspect that you can just edit the settings file in your backup to en-GB or en-US and then load that into a fresh container and then it'd work right away

**Comment by rich1110** [comment]
Yeah... I completely removed all the docker settings, templates and residual container items and repull the container. New container works ok until I restore my backup - then it just borks. I suspect it may be related to [#638](https://github.com/hay-kot/mealie/issues/638)

**Comment by ltctceplrm** [comment]
@rich1110 try editing your backup file first like what's in my post above yours, then load that into a fresh container

**Comment by hay-kot** [comment]
Resetting you language in the UI would also change that if you're able to navigate to the UI

**Comment by rich1110** [comment]
> 
> 
> @rich1110 try editing your backup file first like what's in my post above yours, then load that into a fresh container

^ This!!

Thanks very much @ltctceplrm. I tried your original suggestion (changing the locale language settings using the GUI immediately after a backup restore, but I wasn't allowed to save the changes). Instead, I edit the _settings.json_ file directly inside my backup archive, changing the language from "en" to "en-GB" and then restored the backup into a fresh install. Everything now works.

Thanks very much.

**Comment by rich1110** [comment]
> Resetting you language in the UI would also change that if you're able to navigate to the UI

Yes, but I was not able to save any changes inside the GUI.

**Comment by nathcoad** [comment]
I tried doing this but I can’t seem to unzip the backups file. Is it a regular zip file? Perhaps it is corrupted somehow?

**Comment by rich1110** [comment]
@nathcoad 
I just use 7-zip to open the archive. It didn't appear any different to a normal archive file.

**Comment by nathcoad** [comment]
Ok cool.
Turns out I had a backup of the VM that runs the mealie container, so I was able to access an older backup file and modify settings.json. Importing that into a new 0.52 container did the trick.
Thanks for your help!

**Comment by ltctceplrm** [comment]
Did you start with a fresh/new container before uploading the zip?

**Comment by rucknapucknavitz** [comment]
> Did you start with a fresh/new container before uploading the zip?

I did. New persistent storage, new images, and new containers. The unedited backup will upload - it just doesn't like when I edit to en-US.

**Comment by ltctceplrm** [comment]
Then I'd try uploading the unedited backup and unselecting "settings" in the import screen and just manually restoring those settings later.

**Comment by rucknapucknavitz** [comment]
> unselecting "settings" in the import screen

That worked - thank you!

**Comment by KakersUK** [comment]
unRAID simply employs a templating system (XML) of default options for the docker image. So there isn't anything different going on with unRAID here specifically, typically it'll just go with whatever is in the docker image. I suspect this is more of a code issue.

From what I can tell by looking at my filesystem, it seems the database name and path was changed. It used to be db/mealie_v0.4.0.sqlite and now it's mealie_v0.5.0.db in the root filesystem. So this will also probably pertain to #637 if people are using the docker image in production on their Synology or unRAID NAS then the version based naming for databases will most likely cause an issues again in the future.

It seems the docker container by default is using a Production "true" environment variable. It might be best to use a standardized name like mealie.db for Production = true but a version based database name for Production = false.

If the data hasn't been completely blown away people should be able to recover their recipes. I managed to do this myself by temporarily downgrading the version used by my docker container:

![mealie_repository](https://user-images.githubusercontent.com/2082913/128344567-85fbdf99-b5fd-4a26-8c82-bae634017258.png)

1. Change the repository from "hkotel/mealie" to "hkotel/mealie:v0.4.3" and apply.
2. Log in and create a backup (download to your machine to be safe).
3. Change the repository back to "hkotel/mealie".
4. Log in with the default credentials.
5. Import your backup.

There may already be a backup file but with docker containers automatically upgrading then this may get overwritten especially if people only log onto their instance once a week or less. I'd recommend people do manual backups from time to time.

**Comment by hay-kot** [comment]
> It used to be db/mealie_v0.4.0.sqlite and now it's mealie_v0.5.0.db 

These changes are listed as breaking changes on the [changelog](https://hay-kot.github.io/mealie/changelog/v0.5.0/). This is due to the massive changes that take place on the database during each upgrade. I haven't setup migrations yet because of this. Once the database schema is some-what stable, I'll be looking at setting up migrations and resolving these breaking changes. Also, this only applies if you're upgrading from 0.4.x -> 0.5.x. 

That work is already being done with the v1.0 rewrite.

**Comment by hay-kot** [comment]
Should be fixed in the new release (v0.5.3), please open a new issue if you're still experiencing it after upgrading.
