### ISSUE TITLE
Could Not Validate Credentials

### ISSUE THREAD

**Issue by greerchristo** [hay-kot/mealie#647]
When trying to troubleshoot #644 I rebooted my server and now I cannot login as I get the error "could not validate credentials"

**Steps To Reproduce**
Please be specific!
1. Go to 'Login'
2. Click on 'Sign In

**Expected behavior**
Should be able to log in

**Actual Behavior**
get error "Could Not Validate Credentials "

**Comment by greerchristo** [comment]
this can be closed, I'm just going to blow the install up and not use postgres

**Comment by hay-kot** [comment]
Sometimes PostgreSQL won't initialize before Mealie starts up all the way and then there's some weirdness with initializing default values. SQLite is probably the best bet at this point. PG will get more stable in future releases.

**Comment by greerchristo** [comment]
thanks bud.  i reinstalled and she's purrin like a kitten
