### ISSUE TITLE
Import from Nextcloud 48% not working

### ISSUE THREAD

**Issue by funky123** [hay-kot/mealie#653]
**Describe the bug**
Importing a ZIP File from Nextcloud resulting with 58 failed imports and only 62 working ones.

**Steps To Reproduce**
Please be specific!
1. download nextcloud recepies as .zip file
2. upload them to migration at Nextcloud Cookbook
3. wait for prozess to finish
4. check the results

**Sample Code**

**Expected behavior**
Success

**Actual Behavior**
"failed"
`(sqlite3.IntegrityError) UNIQUE constraint failed: recipes.slug [SQL: INSERT INTO recipes (name, description, image, total_time, prep_time, perform_time, cook_time, recipe_yield, "recipeCuisine", slug, rating, org_url, date_added, date_updated, favorited_by_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)] [parameters: ('Laugenbrezeln', '', 'https://img.chefkoch-cdn.de/rezepte/225891092993593/bilder/1201543/crop-960x540/laugenbrezeln.jpg', '45 Minutes', '45 Minutes', None, None, '10', None, 'laugenbrezeln', None, '', '2021-08-20', '2021-08-20 21:54:58.553758', None)] (Background on this error at: https://sqlalche.me/e/14/gkpj)`

**Screenshots**
![Screenshot-20 08 2021-0003](https://user-images.githubusercontent.com/12056510/130287899-8fa7fec5-1dbe-4bef-95fb-a868a5d8e877.jpg)

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04 Docker
 - Deployment: Docker 20.10.8
 - Browser: Chrome 92
 - Version: Mealie 0.5.2

**Additional context**
to test it, use this one
[Laugenbrezeln.zip](https://github.com/hay-kot/mealie/files/7023900/Laugenbrezeln.zip)

**Comment by hay-kot** [comment]
> Additional context
> to test it, use this one
> Laugenbrezeln.zip

This worked fine on the [demo-site](https://mealie-demo.hay-kot.dev/recipe/laugenbrezeln). If you have all your recipes, I can try those as well. 

The error you're getting should only happen when you have a duplicate entry in the database. You could try deleting your database and re-import the recipes. But I'm not sure why you would get this if they didn't exists?

**Comment by funky123** [comment]
Okay it seems import was working but there are some errors at the log only.
