### ISSUE TITLE
Ram Usage

### ISSUE THREAD

**Issue by sandstormkeshav** [hay-kot/mealie#654]
**Describe the bug**

I am currently running mealie inside the docker image, I am wondering if it is normal for the container to be using 400MB of RAM?
**Steps To Reproduce**
Please be specific!
1. Setup Mealie using Quickstart docker container listed on website
2. Check RAM Usage

**Expected behavior**

Less RAM Usage?

**Device Information (please complete the following information):**
 - OS: Unraid
 - Deployment: Docker Version
 - Browser: Chrome
 - Version: 0.5.2

**Additional context**
I am wondering if its related to the addition of gunicorn, or if this is just expected RAM usage.

**Comment by hay-kot** [comment]
Potentially related to an [issue posted in the FastAPI repo](https://github.com/tiangolo/fastapi/issues/1624). 

I did notice the same thing on the demo site. Reducing the workers did bring it down to 300m, but I still think that a lot for idling, although I don't have a good baseline for another similar python application. I haven't done any memory management, so it may be time to look into that.

**Comment by sandstormkeshav** [comment]
It is now at almost 600 MB, there does seem to be some kind of leak, I never saw this kind of usage before. I just limited the docker containers memory to 1GB to prevent an OOM of the node. Memory management would be great, thank you!

**Comment by hay-kot** [comment]
> It is now at almost 600 MB, there does seem to be some kind of leak, I never saw this kind of usage before. 

That's not something I've seen. If you don't mind, can you set the variables below and see if the memory issue still occurs? 

```
      # Gunicorn
      WEB_CONCURRENCY: 2
      WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 1
```

**Comment by sandstormkeshav** [comment]
> > It is now at almost 600 MB, there does seem to be some kind of leak, I never saw this kind of usage before.
> 
> That's not something I've seen. If you don't mind, can you set the variables below and see if the memory issue still occurs?
> 
> ```
>       # Gunicorn
>       WEB_CONCURRENCY: 2
>       WORKERS_PER_CORE: 0.5
>       MAX_WORKERS: 1
> ```

That looks to be using 345MB of RAM when running with the above settings

**Comment by hay-kot** [comment]
I've set the web concurrency to default to a single worker. This should resolve the issue by default. Thanks!
