### ISSUE TITLE
Clicking on "tags" on a mobile phone doesn't work (Wrong link, "Internal server error")

### ISSUE THREAD

**Issue by cyberius0** [hay-kot/mealie#655]
**Describe the bug**
Clicking on a "tag" within a recipe on my mobile phone (Android + Firefox browser) shows the error message "Internal server error". When examining the link of the tag it leads to "[url]/recipes/category/undefined" (see screenshots). Clicking on the same "tag" on my PC with Firefox works without problems.

**Steps To Reproduce**
Please be specific!
1. Go to any recipe on a mobile phone with Firefox browser.
2. Click on any tag that was saved with that recipe.
3. Link is wrong, message "internal server error"

**Screenshots**
**Screenshot on PC**: Link is correct

![ff_pc](https://user-images.githubusercontent.com/3000648/130757027-62fefe19-1004-4472-ac15-b185448a38df.png)

**Screenshot mobile phone (Android with Firefox)**: Link is not correct:

![ff_android](https://user-images.githubusercontent.com/3000648/130757080-1e152a13-7156-45a1-803c-c81ff154d626.png)

**Additional context**
Mealie version 0.5.2 (running with Docker on Debian Linux)

**Comment by hay-kot** [comment]
Should be fixed in the new release (v0.5.3), please open a new issue if you're still experiencing it after upgrading.
