### ISSUE TITLE
Container running as root user

### ISSUE THREAD

**Issue by usma0118** [hay-kot/mealie#657]
I have tried to deploy with:
securityContext:
  runAsNonRoot: true

this has resulted into groupmode error

**Expected behavior**
Container and application should run fine.

**Actual Behavior**
container fails with following error:
Production
groupmod: Permission denied.
groupmod: cannot lock /etc/group; try again later.

**Device Information (please complete the following information):**
 - OS: Ubuntu 20.04
 - Deployment: Microk8s

**Comment by hay-kot** [comment]
Caveats 
1. I'm don't know anything about Microk8s
2. I'm not a container expert, so I'm not sure how much help I can be here. 

---
Currently, the user is created at runtime with the set PUID/GUID variables so without running as an admin I'm not sure this will work. Obviously running as root is not ideal, but I'm unsure how to allow both PUID/GUID settings and running as non-root. 

I will gladly accept any PRs or support on making this work as it's not my primary area of expertise.

**Comment by usma0118** [comment]
in cady file you have, can't it run on any other port instead of 80?
`:80 {
	@proxied path /api/* /docs /openapi.json

	@static {
		file
		path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.svg *.woff *.woff2 *.webp
	}

	encode gzip zstd

	# Handles Recipe Images / Assets
	handle_path /api/media/recipes/* {
		header @static Cache-Control max-age=31536000
		root * /app/data/recipes/
		file_server
	}`

**Comment by hay-kot** [comment]
Is that related to this issue?

You should be able to set port 80 to anything you want.

**Comment by usma0118** [comment]
I had been working on fixing this. but right now blocked due to scheduler.db error.
is it intentional to have scheduler.db as 644 permissions while mealie.db as 755?

644 mealie.log
755 mealie_v0.5.0.db
644 scheduler.db
644 scheduler.db-journal

I have non-root PR ready but this issuer is a blocker for testing.

**Comment by hay-kot** [comment]
> is it intentional to have scheduler.db as 644 permissions while mealie.db as 755?

No, it isn't. scheduler.db is deleted and recreated at runtime. This could potentially be moved to a non-exposed volume. I'm not sure why the logger wouldn't have the correct permissions.

It may be necessary to call 

```python
os.chmod({dir}, 0775)
```

on whatever files have improper permissions.

**Comment by usma0118** [comment]
I think moving it to a non-exposed volume is good idea as it holds no critical data.

**Comment by usma0118** [comment]
@hay-kot let me know when i should try this.

**Comment by hay-kot** [comment]
> @hay-kot let me know when i should try this.

I'm not sure what you mean

**Comment by agneevX** [comment]
Why not use the default PUID/PGID of `1000`? 

https://github.com/hay-kot/mealie/blob/b46ea7c81ffd6c7a02dd02932671460aef71af9c/Dockerfile#L32-L35

Makes no sense for it to run as `root`.

Also, I agree, it should not listen on priveleged ports (<1024).

**Comment by usma0118** [comment]
> > @hay-kot let me know when i should try this.
> 
> I'm not sure what you mean

was referring to log and schedher.db permission fix.

**Comment by hay-kot** [comment]
> was referring to log and scheduler.db permission fix.

This isn't something I'm actively looking at, nor do I see having time to look at it in the near future.

**Comment by articuno1au** [comment]
I spun up the container with PUID/GUID 1000, got it up and running checked everything out. Went to set up backups and realised everything was owned by root. Definitely sub-optimal.

It would be worth calling out in the current documentation as that's a rude surprise for someone who isn't paying attention.

@usma0118 - Looks like the scheduler DB is configured at: https://github.com/hay-kot/mealie/blob/b565cf24dfa145d1b36b7df1049da47b6fb5d6c4/mealie/core/config.py#L154 and gets ingested from there in the only other place it's used.

Seems an easy enough change to move it out of the data directory into the container. Would that allow us to work around the error you're seeing?

I can try testing in a couple of days based on the PR you have in your fork.

**Comment by articuno1au** [comment]
@usma0118 - Ok, so I have it running now with a temp directory in the container and no root owned files on the file system. Unfortunately I couldn't get your fork to run due to a `groupmod: group 'abc' does not exist`. I tried propagating the changes further into the script, but no joy. I ended up using hay-kot's mealie:master.

The change is very simple. Create `/app/temp` in the dockerfile (I just whacked it in), add a Path variable to config.py and then feed it to SCHEDULER_DATABASE. I'm sure I'm sharing this entirely the wrong way, but first time working on a public project..
```diff --git a/Dockerfile b/Dockerfile
index 9e9088a..8e02b0b 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -128,6 +128,7 @@ WORKDIR /
 COPY --from=frontend-build /app/dist $MEALIE_HOME/dist
 COPY ./dev/data/templates $MEALIE_HOME/data/templates
 COPY ./Caddyfile $MEALIE_HOME
+RUN mkdir /app/temp

 VOLUME [ "$MEALIE_HOME/data/" ]
 ENV APP_PORT=80
diff --git a/mealie/core/config.py b/mealie/core/config.py
index 45a23fe..a477224 100644
--- a/mealie/core/config.py
+++ b/mealie/core/config.py
@@ -43,7 +43,7 @@ def determine_secrets(data_dir: Path, production: bool) -> str:

 # General
 DATA_DIR = determine_data_dir(PRODUCTION)
-
+CONTAINER_TEMP_DIR = Path("/app/temp")

 class AppDirectories:
     def __init__(self, cwd, data_dir) -> None:
@@ -151,7 +151,7 @@ class AppSettings(BaseSettings):
     DEFAULT_EMAIL: str = "changeme@email.com"
     DEFAULT_PASSWORD: str = "MyPassword"

-    SCHEDULER_DATABASE = f"sqlite:///{app_dirs.DATA_DIR.joinpath('scheduler.db')}"
+    SCHEDULER_DATABASE = f"sqlite:///{CONTAINER_TEMP_DIR.joinpath('scheduler.db')}"

     TOKEN_TIME: int = 2  # Time in Hours```

**Comment by usma0118** [comment]
haven't tested after adding your changes. will do them later.
but feel free to use this branch https://github.com/usma0118/mealie/tree/docker/runasnonroot

we can collaborate on this.

missing: build image and test.

**Comment by articuno1au** [comment]
Hey @usma0118, yeah definitely happy to work with you on this one (when I'm able), but that branch is what I was blocked on by the error.

The dockerfile in the branch also has a trailing ` which breaks the build. I just didn't want to roll back your commit to make it work (seemed a bit rude :P). I'll try and etch out some time over the weekend. Thanks for the invite to collaborate :)

**Comment by usma0118** [comment]
image is building fine now. i plan to test it during weekend.

**Comment by usma0118** [comment]
PR part of dev branch now.
