### ISSUE TITLE
No image when added by URL, and can;t add an image

### ISSUE THREAD

**Issue by kirkybaby** [hay-kot/mealie#66]
Not sure why the image failed to save with the URL, the rest of the recipe was fine. But now it will not allow me to save a different image instead either. At first in the code, it said: image: "no image", then after trying to swap the image, it says: image: "null"

Any ideas? I'm on version 0.0.2 and here is the URL I was adding:
https://sallysbakingaddiction.com/easy-coconut-shrimp/

**Comment by hay-kot** [comment]
Looks like 2 things were going on. No image data was provided as part of the recipe schema, nothing I can really do about that at the moment. The second thing is that the image looks like it gets uploaded but the name never gets changed in the database. I'll roll out a small patch when I can to address the issue. For the time being, you can change the image text yourself to the recipe slug + the image extension. So easy-coconut-shrimp.jpg should get you there.

**Comment by kirkybaby** [comment]
Awesome, thanks once again for the quick replies!!

**Comment by hay-kot** [comment]
This has been addressed in v0.1.0
