### ISSUE TITLE
Image rotation an croping 

### ISSUE THREAD

**Issue by funky123** [hay-kot/mealie#661]
**Describe the bug**
Images are rotating at the recipe view.
At the explorer preview they are correct, but in mealie they are 180° rotated or the displayed part of the image is not good.

**Steps To Reproduce**
Upload a picture (attached), an view after save them.

**Sample Code**

**Expected behavior**
No rotation or/and the part of the picture displayed centered but not zoomed in.

**Actual Behavior**
Rotation or/an zoomed in

**Screenshots**
Attached
![20210815_184322](https://user-images.githubusercontent.com/12056510/131254142-fd59c007-93d7-4c4d-affb-d4ad5d69a24e.jpg)

![20210818_120012](https://user-images.githubusercontent.com/12056510/131254174-14cbbe01-74fd-40b6-aa79-7d1433f88f6e.jpg)
<img width="956" alt="Screenshot 2021-08-29 163708" src="https://user-images.githubusercontent.com/12056510/131254245-8f9db697-88f3-4b85-b616-a25b25f03d2f.png">

<img width="959" alt="Screenshot 2021-08-29 163809" src="https://user-images.githubusercontent.com/12056510/131254280-650bd967-5d8f-4b38-95c2-2baf4691c5f4.png">

**Device Information (please complete the following information):**
 - Deployment:  Docker-version latest, docker-compose latest
 - Browser: all/latest
 - Version: mealie latest 0.52

**Additional context**

**Comment by hay-kot** [comment]
I'm not sure what would cause this, there's nothing that explicitly does anything with rotation, the image that displays on the recipe page should be unchanged. 

What happens if you rotate the image and re-upload it?

**Comment by funky123** [comment]
i added some filters reuploaded it, now it works.

![03](https://user-images.githubusercontent.com/12056510/131723888-bea6e8bd-a5fb-47d5-badf-98bf6bba4f08.jpg)
