### ISSUE TITLE
Image Preview not displayed at search

### ISSUE THREAD

**Issue by funky123** [hay-kot/mealie#662]
**Describe the bug**
Image preview of recipe not shown at search

**Steps To Reproduce**
Search fresh added recipe with picture.

**Expected behavior**
Display of image

**Actual Behavior**
Placeholder image shown

**Screenshots**

<img width="953" alt="Screenshot 2021-08-29 164113" src="https://user-images.githubusercontent.com/12056510/131254430-b5b1494e-fc7f-4fa3-9e8c-638e78fea154.png">
<img width="946" alt="Screenshot 2021-08-29 164140" src="https://user-images.githubusercontent.com/12056510/131254431-39702b06-c51a-4a85-8941-9b40abde695e.png">

**Device Information (please complete the following information):**

 - Deployment: Docker latest, docker-compose latest
 - Browser: all
 - Version: 0.52

**Additional context**

**Comment by hay-kot** [comment]
From your previous issue, it looks like the migration may have partially crashed? If it did get interrupted it may not have created all the required images. I believe the system checks on reboot, so if you reboot the container it way re-run all those actions. 

There should be 3 image files in the recipe directory. You can check the image folder for the recipes to see if all the required images are there.
