### ISSUE TITLE
Localization not loading on upgrade to v0.5.2

### ISSUE THREAD

**Issue by IronicBadger** [hay-kot/mealie#671]
![image](https://user-images.githubusercontent.com/2773080/132114993-c49aab0a-2723-40ec-ab3d-11d9afef70f9.png)

Unable to load any recipes (they are visible in the DB) after first page load. Hard to explain but first page load works as expected but clicking on any recipe or link (logging in or not) the app seems to break and loads this `some.thing` type links.

Running 0.5.0 in docker. Tried both with and without a reverse proxy just incase the URLs were hardcoded somewhere and got the same result.

**Comment by hay-kot** [comment]
Couple of things I can think of to try.

1. Hard refresh browser, clear cache and/or data
2. If you can, navigate to your settings and reset your language to something different, and then back to English. 

If you happen to be running 0.5.2. There is issue #640 related to the language file not loading. looks like during a PR some of the language files changed names but there wasn't a catch in place to replace the old references.

**Comment by IronicBadger** [comment]
My bad - I was running `0.5.2`, downgraded to `0.5.1` and access was restored.

`0.5.2` confirmed buggy :)

**Comment by nnarain** [comment]
Same issue for me. Also downgraded to 0.5.1 and appears to be ok now.

**Comment by hay-kot** [comment]
If either of you are feeling brave and want to confirm that bug is fixed, you can pull the :dev tag from docker and do a browser refresh `CMD` + `SHIFT` + `R`

**Comment by hay-kot** [comment]
Should be fixed in the new release (v0.5.3), please open a new issue if you're still experiencing it after upgrading.
