### ISSUE TITLE
database was reset and all recipes lost. 

### ISSUE THREAD

**Issue by davbren** [hay-kot/mealie#672]
**Describe the bug**
create database using installation instructions. All worked well. The "service" stopped so I restarted it using the docker run command and it rebuilt the installation.

**Steps To Reproduce**
Please be specific!
1. Install as normal
2. Run "docker run \
    -p 9925:80 \
    -v `pwd`:'/app/data/' \
    hkotel/mealie:latest"

**Expected behavior**
Service would restart allowing me to access the site on domainname:9925

**Actual Behavior**
Connection refused message on browser until _docker run_ command is given, then database is overwritten and rebuilt.

**Device Information (please complete the following information):**
 - OS: Ubuntu 21.04
 - Deployment: Docker version
 - Browser: chrome
 - Version: latest on 5 Sept 2021

**Comment by hay-kot** [comment]
The `-v pwd:'app/data' mounts the current directory to the image. If you didn't run the command from the same directory each time, you will experience what you described.

Are you sure that the files don't reside somewhere else on your machine?

**Comment by davbren** [comment]
ah right, that's interesting. The server is rebooted every night. So
presumably after this first reboot the conditions would be the same so
should persist?
