### ISSUE TITLE
Continer Fails to initialize due to python package error on ubuntu arm64 raspberry pi 3

### ISSUE THREAD

**Issue by ender89** [hay-kot/mealie#674]
Mealie fails to initialize on a raspberry pi 3 running ubuntu server 20.04 arm64

Error is given as a python package error "Failed to import the site module"

docker-compose up
mealie is up-to-date
Attaching to mealie
mealie    | Production
mealie    |
mealie    |     User uid:    1000
mealie    |     User gid:    1000
mealie    |
mealie    | Error processing line 1 of /opt/poetry/venv/lib/python3.9/site-packages/_virtualenv.pth:
mealie    |
mealie    | Fatal Python error: init_import_site: Failed to import the site module
mealie    | Python runtime state: initialized
mealie    | Traceback (most recent call last):
mealie    |   File "/usr/local/lib/python3.9/site.py", line 169, in addpackage
mealie    |     exec(line)
mealie    |   File "<string>", line 1, in <module>
mealie    |   File "/opt/poetry/venv/lib/python3.9/site-packages/_virtualenv.py", line 40, in <module>
mealie    |     from functools import partial
mealie    |   File "/usr/local/lib/python3.9/functools.py", line 18, in <module>
mealie    |     from collections import namedtuple
mealie    |   File "/usr/local/lib/python3.9/collections/__init__.py", line 39, in <module>
mealie    |     from reprlib import recursive_repr as _recursive_repr
mealie    | ValueError: source code string cannot contain null bytes
mealie    |
mealie    | During handling of the above exception, another exception occurred:
mealie    |
mealie    | Traceback (most recent call last):
mealie    |   File "/usr/local/lib/python3.9/site.py", line 589, in <module>
mealie    |     main()
mealie    |   File "/usr/local/lib/python3.9/site.py", line 572, in main
mealie    |     known_paths = venv(known_paths)
mealie    |   File "/usr/local/lib/python3.9/site.py", line 504, in venv
mealie    |     addsitepackages(known_paths, [sys.prefix])
mealie    |   File "/usr/local/lib/python3.9/site.py", line 359, in addsitepackages
mealie    |     addsitedir(sitedir, known_paths)
mealie    |   File "/usr/local/lib/python3.9/site.py", line 208, in addsitedir
mealie    |     addpackage(sitedir, name, known_paths)
mealie    |   File "/usr/local/lib/python3.9/site.py", line 179, in addpackage
mealie    |     import traceback
mealie    |   File "/usr/local/lib/python3.9/traceback.py", line 3, in <module>
mealie    |     import collections
mealie    |   File "/usr/local/lib/python3.9/collections/__init__.py", line 39, in <module>
mealie    |     from reprlib import recursive_repr as _recursive_repr
mealie    | ValueError: source code string cannot contain null bytes

**Comment by hay-kot** [comment]
Please provide your docker compose and follow the issue template.
