### ISSUE TITLE
Signup links don't seem to be working.

### ISSUE THREAD

**Issue by crunchingcode** [hay-kot/mealie#677]
**Describe the bug**
So I created a signup link and replaced my internal ip with my fqdn that I use.  Everything works and the user starts to create the account but when they click signup it says You are not allowed to create a user.

**Steps To Reproduce**
Please be specific!
1. Go to signup links under managed users.
2. create link
3. send link to user (change internal ip to whatever you need to change it to)

**Expected behavior**
Link is used to create a user

**Actual Behavior**
Link is used but errors out saying they is not allowed to create a user

**Screenshots**
Unable to at this time.

**Device Information (please complete the following information):**
 - OS: Unraid
 - Deployment: Docker
 - Browser: Safari
 - Version: Latest on Iphone

**Comment by crunchingcode** [comment]
well unraid is setup to click on the docker and go to webui which uses the ip. I can setup a static dns entry on my local resolvers that I can use internally so I can reach it.  I'll test that out tomorrow and see if the signup works. and I'll try a different browser as well.

**Comment by KuroSetsuna29** [comment]
@crunchingcode 
This worked for me (I am also using on Unraid), if you are trying to invite someone external from your network, you will either need to:
1. Setup port forwarding on your router to your unraid machine, and then use your public IP or DDNS as domain with the port (eg. http://your.ddns.com:9925/)
2. Or more preferably and secure, use a reverse proxy so you port forward 80 and 443 from router to your reverse proxy ports on Unraid. Then they would just go to for example: https://mealie.your.ddns.com/.

There are couple of different ways to setup reverse proxy on Unraid, two most popular is NginxProxyManager and linuxserver/swag. There are a bunch of video tutorials on YouTube how to setup either. I am using swag which conveniently has a template for mealie already.

Tip, if you use the DDNS url to get the invite link, it is formatted with the DDNS domain already.

-----

If you are inviting someone on your local network to use it, well then it should just work as long as they have the same static dns entry you are using, or just use the IP address of your unraid server.

**Comment by hay-kot** [comment]
Since signup links do work, I'm going to go ahead and close this. If you need some additional support in getting this working, you can open a discussion or reach out on discord.
