### ISSUE TITLE
cannot add linefeed \n in recipe editor

### ISSUE THREAD

**Issue by fundef1** [hay-kot/mealie#68]
When manually adding a recipe (edit) linefeeds are shown in the input boxes.
when rendering the recipe (view) these are removed.

is there a way to force a linefeed ?

**Comment by hay-kot** [comment]
I'm unsure what you're looking for can you provide a little more detail? perhaps with an example.

**Comment by fundef1** [comment]
A picture is worth a thousand words...

the "edit" mode - note the the instructions on seperate lines:
![image](https://user-images.githubusercontent.com/12233640/104303661-a7300080-54ca-11eb-974d-d065444b0a76.png)

in "view" mode - note the instructions on a single line:
![image](https://user-images.githubusercontent.com/12233640/104303772-cb8bdd00-54ca-11eb-87c5-3a3045d51c1b.png)

**Comment by FoxxMD** [comment]
Just adding +1 to this. Newlines are stored in the json but not respected when rendering the content.

![image](https://user-images.githubusercontent.com/4663766/107284458-dedb8b00-6a2b-11eb-885c-2650d26e0992.png)

**Comment by hay-kot** [comment]
To follow up on this, I'm looking at implementing markdown for the description and steps content that will respect line breaks. Hoping to have it working soon!

**Comment by FoxxMD** [comment]
Thanks for the quick work! However #148 fixed this for instructions but not for notes.
