### ISSUE TITLE
Mealie changes file ownership in my home dir.

### ISSUE THREAD

**Issue by bmn001** [hay-kot/mealie#682]
**Describe the bug**

When I run
```
sudo docker run \
    -p 9925:80 \
    -v `pwd`:'/app/data/' \
    hkotel/mealie:latest
```

This is the output:

```Production
usermod: no changes

    User uid:    911
    User gid:    911
```
    
...along with a bunch of other success messages.  And indeed, Mealie runs just fine.

However, it _also_ **changes** the file/group ownership of just about everything in my home directory from plex:plex (this machine is mainly a Plex server, not running on docker) to "911:911".

This ended up breaking a lot of things for me, so I killed the container and went back and changed all of those permissions manually.

I then deleted the container, then tried the docker command above again.  Same thing.  Everything is owned by 911 again.

**Steps To Reproduce**
Please be specific!
1. Fresh install of Docker on Ubuntu 21.04 
2. Run the docker command above from the install instructions
3. Whoop - file ownership is hosed.

**Sample Code**

**Expected behavior**

I'd expect Mealie to run without needing to change file ownership.

**Actual Behavior**

Mealie runs, but my files change ownership.

**Screenshots**

**Device Information (please complete the following information):**
 - OS: Ubuntu 21.04
 - Deployment: Docker
 - Browser: n/a
 - Version: 0.5.2

**Additional context**

I'm honestly not sure if this is a Docker issue or a Mealie issue.  This is the first time I've used Docker.

**Comment by hay-kot** [comment]
This is expected behavior if you're running this in your home directory. `pwd` is just mounting whatever the current directory is to mealie. By default, mealie assigns the owner on startup in order to conform to the ENV settings. 

Making a `~/mealie` directory and running the container in there will likely solve your problem. Although if you're going to use the app more than just testing it out, I suggest you deploy with docker compose.

**Comment by bmn001** [comment]
Thanks for the clarification.  Maybe throw a warning on that part of the install guide :)  Took me a few hours of panicked googling to figure out how to revert those changes safely.

I'm all set now with docker compose!

**Comment by ghost** [comment]
There really should be warning about this, it's pain in the ass to revert all the changes this does if you just happen to be in wrong folder. And I've never seen any other project do this either

**Comment by hay-kot** [comment]
> There really should be warning about this, it's pain in the ass to revert all the changes this does if you just happen to be in wrong folder. And I've never seen any other project do this either

This behavior is inline with what a lot of other container providers do to manage host / container permission conflicts when using volume mounts. You're welcome to submit a PR to provide a warning to other users if you'd like. Another alternative is to use docker-volumes.
