### ISSUE TITLE
ARM image for Docker

### ISSUE THREAD

**Issue by antoine2tt** [hay-kot/mealie#69]
Hello,

I went here : https://hub.docker.com/r/hkotel/mealie/tags?page=1&ordering=last_updated

And i haven't see any ARM images...

Is that possible to have an ARM images in Docker Hub for Mealie ? 

I don't know how to build it myself...

It could be good for thoses who use Raspberry, last Apple products.... 

Thanks !

**Comment by zackbcom** [comment]
I'll look into making this muti arch docker image.

**Comment by antoine2tt** [comment]
Thanks ! You rock

**Comment by robertmain** [comment]
Any update on this?

**Comment by hay-kot** [comment]
> Any update on this?

There is an arm image on docker hub.

**Comment by robertmain** [comment]
Looks like only for older versions up to 0.4.x.

**Comment by hay-kot** [comment]
> Looks like only for older versions up to 0.4.x.

There is an arm64 bit version available. 

<img width="1328" alt="Screen Shot 2021-11-02 at 8 10 03 AM" src="https://user-images.githubusercontent.com/64056131/139898915-221345c0-c57d-4f67-af28-471259bdcb0b.png">

If you are looking for a 32bit image have a look at this issue.

- #706 

If you still need help after that, please open a new issue.

**Comment by robertmain** [comment]
Ohhhhh, thanks! Yeah, that'll do it. I've been meaning to upgrade to 64 bit
anyway. I'll try that. Thank you.
