### ISSUE TITLE
[Feature] Flavor Profile

### ISSUE THREAD

**Issue by dpieski** [hay-kot/mealie#71]
I realize this would probably be a bit down the line from where the project is right now, but the below comment made me think of the ability to create a flavor profile for a particular recipe as part of a rating system. So the ability to rate it on Umami / Temperature / Sweet / Bitter / Salty / Sour / Texture / Spicy. 

Maybe the ratings show up in a [Radar Chart](http://bl.ocks.org/tpreusse/2bc99d74a461b8c0acb1). This is probably not something that would be printed normally. Maybe have an option on the print screen whether to include or not.

> It would be nice if we could have our own "fields" (fields could just be tags/labels with values).  Cook time and prep time are common in cooking (obviously) but some of us might have needs to track other items and search on it.  A few examples could be sodium, or level of spicy/heat.
_Originally posted by @mrherman in https://github.com/hay-kot/mealie/issues/63#issuecomment-758217194_

**Comment by hay-kot** [comment]
This is cool. I particularly like the idea of the Radar Chart. I don't think this feature would be well adopted, but I'm interested in the "cool" factor for sure. I wouldn't expect any progress soon, but I think It's on my radar. Thanks!

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
