### ISSUE TITLE
Possibilities to create meal plan based on rules

### ISSUE THREAD

**Issue by Crupuk** [hay-kot/mealie#77]
Hello, 

First of all, I would like to say thank you for this project .
I just discovered this project on Reddit, installed on podman in 5m and I already have 10 recipes imported.

I would like to know ( already search though all open issue and didn't find one related to this demand ) if you plan to improve the meal plan generator ?

What do you think about the abilities to add some basic rules based on tags like :  

- Min/Max Tags / week or month ( For example, min 1 * fish, max 2 * meat, at least 1 soup  , max 2 * pizza / month etc .. ) 
- Season recipe ( based on ingredient ? or tag ? ), Maybe with a "Season score" based on all parsed ingredient or at least, be able to only select some tags for the meal plan ( "January" tags for example ) 
- Always take the oldest recipe done to avoid same plan two week consecutive

Thx a lot for all your work

**Comment by kentora** [comment]
I definitely think there are plans of improving the meal generator, and I have had the same idea about users being able to set up rules, based on tags and/or categories.
I also mentioned something related in #63 where it would be nice to be able to set up rules about max cook/prep time, useful for weekday meals.

**Comment by hay-kot** [comment]
The meal planner is very much thrown together at the moment. IMO it needs a UI redesign and a lot more features to be useful. These are all really good ideas. Filtering primarily on tags and categories is my idea. You've brought up some good points, but I'm scratching my brain on how to get it working client-side in javascript with the random generator. I'm open to suggestions. Thanks!

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
