### ISSUE TITLE
Allow adding / editing notes without editing the recipe

### ISSUE THREAD

**Issue by kentora** [hay-kot/mealie#79]
Like Rating (as mentioned in #25), one might not expect to "edit recipe" to add or edit notes.
This change could also come in handy with users (and possibly groups) along with read/write permissions, causing users to be able to read but not edit a recipe. Those users might still want to leave a note / comment.

**Comment by hay-kot** [comment]
I see notes and comments as different things. I see a comment as a place to put alternative methods, or things to keep in mind. Comments, to me, are more of a place for discussion and user interaction. I'm just getting into setting up authentication and will be looking at implementing this in the feature.

I'm leaning towards having an optional comments field under the recipe where any user can comment, and have the notes be restricted to users who have editing privileges.

**Comment by hay-kot** [comment]
Since I've added comment support, I'm going to close this. I think that that meets the intent of the issue here while still allowing users to have notes that can't be edited freely.
