### ISSUE TITLE
Empty line in "Notes" crashing

### ISSUE THREAD

**Issue by karabays** [hay-kot/mealie#8]
Hi, 
first of all.. great! thanks for this. 
I think it's not a big deal to fix this but when a recipe is saved by empty note line (by mistake) FastAPI is throwing an error and not loading the recipe. and backs to normal once the empty entry deleted from mongodb

> notes: [
        {
            title: 'OK',
            text: 'This is ok.'
        },
        {
            text: ''
        }

here is the logs, if that helps:

> mealie           | ERROR:    Exception in ASGI application
mealie           | Traceback (most recent call last):
mealie           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/httptools_impl.py", line 390, in run_asgi
mealie           |     result = await app(self.scope, self.receive, self.send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
mealie           |     return await self.app(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 179, in __call__
mealie           |     await super().__call__(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 111, in __call__
mealie           |     await self.middleware_stack(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
mealie           |     raise exc from None
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
mealie           |     await self.app(scope, receive, _send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
mealie           |     raise exc from None
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
mealie           |     await self.app(scope, receive, sender)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 566, in __call__
mealie           |     await route.handle(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 227, in handle
mealie           |     await self.app(scope, receive, send)
mealie           |   File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 41, in app
mealie           |     response = await func(request)
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 182, in app
mealie           |     raw_response = await run_endpoint_function(
mealie           |   File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 133, in run_endpoint_function
mealie           |     return await dependant.call(**values)
mealie           |   File "./routes/recipe_routes.py", line 26, in get_recipe
mealie           |     recipe = Recipe.get_by_slug(recipe_slug)
mealie           |   File "./services/recipe_services.py", line 99, in get_by_slug
mealie           |     return Recipe._unpack_doc(document)
mealie           |   File "./services/recipe_services.py", line 91, in _unpack_doc
mealie           |     return cls(**document)
mealie           |   File "pydantic/main.py", line 346, in pydantic.main.BaseModel.__init__
mealie           | pydantic.error_wrappers.ValidationError: 1 validation error for Recipe
mealie           | notes -> 1 -> title
mealie           |   field required (type=value_error.missing)

**Comment by hay-kot** [comment]
Hmm, looks like a few things need to happen. 

1) Validate JSON on client side. It appears I can use the existing npm package to do that [here](https://github.com/josdejong/jsoneditor/blob/master/docs/api.md#configuration-options?blank) 
2) Prevent updating the database on error and respond with useful user feedback.

#2 should be easy and in the next release, #1 may take some time.

**Comment by hay-kot** [comment]
This has been addressed in v0.1.0
