### ISSUE TITLE
Add user management [Feature Request]

### ISSUE THREAD

**Issue by calgara12** [hay-kot/mealie#82]
First of all, thank you for all your effort!
I would like for not everyone to be able to create a recipe, only registered users, and also a way to disable registration.

Thanks.

**Comment by fosspill** [comment]
I haven't dug too much into it or tested it, but would limiting access to "/api/recipe/create-url/" and "/api/recipe/create/" with password protection from your server work?

**Comment by hay-kot** [comment]
It's ion the roadmap. targeting v1.0. so a ways away. However, with some additional community support, I may be able to shift my focus and work on that as opposed to some other issues/fixes/improvements.

**Comment by dpieski** [comment]
relevant comment: https://github.com/hay-kot/mealie/issues/27#issuecomment-759632159

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
