### ISSUE TITLE
Present users with existing categories and tags, when adding or editing a recipe

### ISSUE THREAD

**Issue by kentora** [hay-kot/mealie#83]
Currently users will have to type in the exact same tag/category to get the (not yet implemented) advantages of tags and categories.

To help the user, they should be presented with existing categories and tags in the combobox. The user should then be able to search and select among the existing (or, of course as it is possible today: add a new one).

**Comment by hay-kot** [comment]
Fixed in the [new release v0.2.0](https://github.com/hay-kot/mealie/releases/tag/v0.2.0) 🎉
