### ISSUE TITLE
Web scraping error

### ISSUE THREAD

**Issue by m-zaw** [hay-kot/mealie#86]
Hi.

Thank you for such a fantastic app!

I've made it a spin with the dev branch as using arm64 platform. Up to date with the latest revision from this morning.
Unfortunately I am not able to web scrap any recipes. The error the fronend pops is "Looks like there was an error parsing the URL. Check the log and debug/last_recipe.json to see what went wrong."
Please see the log below and let me know if you need any other info.

Many thanks in advance!

Mealie log: https://pastebin.com/3TgYrzqg
Last recipe debug: https://pastebin.com/C9yeQWNB

**Comment by Casper9228** [comment]
Same here, using the Dev branch. Got a web scrape error. Please find the details here:
Mealie log: https://pastebin.com/Rr7J2NpG
Last Recipe: https://pastebin.com/q0XCdpkJ

Additionally, this website ( https://www.hellofresh.nl/recipes/romige-linguine-met-broccoli-5f6b33831268ce386f370e83 ) has a slider on the page, indicting a number of persons. Upon moving that slider, the amount of ingredients you need, changes. Any chance this is something that can be incorporated?

**Comment by hay-kot** [comment]
@m-zaw, can you pull the latest image from the dev branch and let me know if you're still experiencing the same issue? If you are, can you provide the URL?

**Comment by m-zaw** [comment]
@hay-kot All working flawlessly! Awesome work!
