### ISSUE TITLE
Feature Request - "Leftovers" and "Ordering out" options for meal planning

### ISSUE THREAD

**Issue by goose-ws** [hay-kot/mealie#97]
It'd be lovely to be able to fill in the calendar days with a placeholder card for leftovers or ordering out, when utilizing the meal planner feature. So that way those days can be planned/don't appear blank, without those items having to take up a recipe slot.

**Comment by nickcj931** [comment]
I just created a few recipe cards - called it “Takeout - Chinse”
“Takeout - Etc”

im sure you can also create one and call it “Leftovers magic meal” 

In my cards I have my favourite takeout restaurants details phone number and website/menu etc.

I’m not sure on the value to have anything else more complicated to exist?

**Comment by goose-ws** [comment]
As a workaround, that does the job, for sure. The advantage in having a built in place holder is that it doesn't show up as a recipe, while still being available to fill a slot in the meal planner.

**Comment by nickcj931** [comment]
I guess it a difference of requirements, to me its not a workaaround, but actually useful card which has actionable content.
I still dont fully understand why having something you cannot interact with that just says Leftovers or Ordering Out, you may as well just leave them not filled out.

Just to understnad, would you just get rid of the "View recipe" link on the weekly view? What do you think should happen if its "Order Out" day and you click on "Dinner Today"? From a UI point of view what do you propose should happen in your scenario?

Personally I think as the platform matures and the Categories become more sortable/searchable #15  which they currently are not, you will be able to have the TakeAway Category label not even show up in your main recipe dashboard if you wished.

**Comment by sephrat** [comment]
I think it could be nice to be able to type free text in such cases (Chinese take out, restaurant xxx, at a friend's, etc.). It has no value inside Mealie but it helps you plan your week without having to deal with a dummy recipe for every case. 
I've seen this in another project and liked it.

**Comment by hay-kot** [comment]
> 
> 
> I think it could be nice to be able to type free text in such cases (Chinese take out, restaurant xxx, at a friend's, etc.). It has no value inside Mealie but it helps you plan your week without having to deal with a dummy recipe for every case.
> I've seen this in another project and liked it.

This was the approach I was planning on taking. Having a card you can enter your own title/description in. Implementation will likely take some time though.

**Comment by hay-kot** [comment]
Closing to consolidate feature requests into a mega-issue. [See new Issue](https://github.com/hay-kot/mealie/issues/122). Your request has been added to the initial list.
